# Random Variables

A random variable is a function that assigns a numerical value to each outcome of a random experiment, used to *model* the behaviour of random processes. Random variables are notated using *capital letters*, such as $X$ and $Y$, whilst the *specific values* that they can take are notated with corresponding small letters such as $x$ and $y$. Random variables can be used to model either *discrete* or *continuous* quantitative variables.

### Discrete Random Variables {-}

If a random variable takes *discrete* numerical values, and a probability is assigned to each, then it is a **discrete random variable**. Discrete values are those that can be listed (either finitely or countably infinitely). Some examples of discrete random variables are:

\begin{center}
\renewcommand{\arraystretch}{2}
\begin{tabular}{ l  l } 
     \textbf{Random variable} (e.g. $X$) & \textbf{Discrete values} (e.g. $x$)     \\ 
     The outcome of a roll of a cubical die & $\text{1}, \text{2}, \text{3}, \text{4}, \text{5}, \text{6}$     \\ 
     The number of goals scored in a game of football & $\text{0},\text{1},\text{2},\text{3},\text{4},\text{5},\text{6},\text{7}...$     \\ 
     The value of a randomly picked UK coin, in pounds & $\text{0.01},\text{0.02},\text{0.05},\text{0.1},\text{0.2},\text{0.5},\text{1},\text{2}$     \\ 
\end{tabular}
\end{center}

The probability that a discrete random variable $X$ takes the value $x$ is notated as:

\[\text{P}(X=x)\]

For example, if random variable $X$ is used to represent the outcome of the roll of a fair, six-sided die, then: 

\[\text{P}(X=\text{5})=\frac{\text{1}}{\text{6}}\]

\pagebreak

## Probability Distributions for Discrete Random Variables

A *probability function* assigns probabilities to each possible value of a discrete random variable, and completely describes its behaviour. There are a number of ways of presenting the *probability distribution* created. For example, consider a discrete random variable $X$ that takes the value 3 with probability 0.2, the value 4 with probability 0.5 and the value 5 with probability 0.3. Below, the probability distribution for $X$ has been *tabulated* and *graphed*.

\begin{figure}[H]
  \centering
\captionsetup[figure]{labelformat=empty}%
\begin{minipage}{.5\textwidth}
\textit{Tabulated:}
\begin{center}
\begin{tabular}{ c | c c c }
      $x$ & 3 & 4 & 5\\
  \hline
      $\text{P}(X=x)$ & 0.2 & 0.5 & 0.3
\end{tabular}
\end{center}

\vspace{0.01cm}

A discrete probability distribution must define \textit{mutually exclusive} and \textit{exhaustive} outcomes, and so \textit{the sum of all probabilities must equal 1}.

\vspace{-0.2cm}

\begin{center}
\begin{tabular}{c c c}
      $0\leqslant \text{P}(X=x_i)\leqslant \text{1}$ for all $i$ & and & $\sum \text{P}(X=x_i)=\text{1}$
\end{tabular}
\end{center}

\end{minipage}%
  \centering
\begin{minipage}{.2\textwidth}
  \centering
\end{minipage}%
  \centering
\begin{minipage}{.5\textwidth}
  \centering
  \textit{Graphed:}\\[-0.5em]
\begin{tikzpicture}
\pgfplotsset{
    standard/.style={
    axis line style = thick,
    trig format=rad,
    enlargelimits,
    axis x line=middle,
    axis y line=middle,
    every axis x label/.style={at={(current axis.right of origin)},anchor=north west},
    every axis y label/.style={at={(current axis.above origin)},anchor=south east}
    }
}
    \begin{axis}[standard,x label style={at={(current axis.right of origin)},anchor=west},y label style={at={(current axis.above origin)},anchor=south}, height = 4.5cm, width = 7cm, ybar,bar width=10pt, xmin=2.5,xmax=5.5,ymin=0,ymax=0.6, 
    xtick={3,4,5},
    xticklabels={3,4,5},
    ytick={0,0.1,0.2,0.3,0.4,0.5},
    yticklabels={0,0.1,0.2,0.3,0.4,0.5},
    xlabel=$x$,ylabel=probability]
        \addplot[fill=black!25, draw=black] coordinates {
    (3,0.2) 
    (4,0.5) 
    (5,0.3) 
};
    \end{axis}
\end{tikzpicture}
\end{minipage}
\end{figure}


\vspace{-0.3cm}

From both the table and the graph, it can be seen that, for example, $\text{P}(X=\text{3})=\text{0.2}$.

Probabilities such as $\text{P}(X\leqslant\text{4})$ can be calculated by adding the probability of each outcome (since they are mutually exclusive), or by subtracting from 1 (since they are exhaustive).

\vspace{-0.3cm}

\[\text{P}(X\leqslant \text{4})=\text{P}(X = \text{3})+\text{P}(X= \text{4})=\text{0.2}+\text{0.5}=\text{0.7}\]

\vspace{-0.7cm}

\[\text{or}\]

\vspace{-0.7cm}

\[\text{P}(X\leqslant \text{4})=\text{1}-\text{P}(X=\text{5})=\text{1}-\text{0.3}=\text{0.7}\]

\vspace{-0.2cm}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} The probability distribution table for the discrete random variable $D$ is shown below.

\begin{center}
\begin{tabular}{ c | c c c c c }
      $d$ & 6 & 7 & 8 & 9 & 10\\
  \hline
      $\text{P}(D=d)$ & 0.35 & 0.3 & $c$ & 0.2 & 0.1 
\end{tabular}
\end{center}

\vspace{-0.2cm}

\text{(a)   }Calculate the value of $c$.\\
  \\[-0.3em]
\text{(b)   }Calculate $\text{P}(D\leqslant\text{7})$.\\
  \\[-0.3em]
\text{(c)   }Calculate $\text{P}(D>\text{7})$.

\tcblower
\textbf{Solution:}

\text{(a)   }$c=\text{1}-(\text{0.35}+\text{0.3}+\text{0.2}+\text{0.1})=\text{0.05}$

\begin{center}
\begin{tabular}{ c | c c c c c }
      $d$ & 6 & 7 & 8 & 9 & 10\\
  \hline
      $\text{P}(D=d)$ & 0.35 & 0.3 & 0.05 & 0.2 & 0.1 
\end{tabular}
\end{center}

\vspace{-0.5cm}

\begin{flalign*}
\text{(b)   }\text{P}(D\leqslant\text{7})&=\text{P}(D=\text{6})+\text{P}(D=\text{7}) &\\
&=\text{0.35}+\text{0.3}\\
&=\text{0.65}
\end{flalign*}

\hspace{9cm}
\begin{tikzpicture}[overlay]
\pgfplotsset{
    standard/.style={
    axis line style = thick,
    trig format=rad,
    enlargelimits,
    axis x line=middle,
    axis y line=middle,
    every axis x label/.style={at={(current axis.right of origin)},anchor=north west},
    every axis y label/.style={at={(current axis.above origin)},anchor=south east}
    }
}
    \begin{axis}[standard,x label style={at={(current axis.right of origin)},anchor=west},y label style={at={(current axis.above origin)},anchor=south}, height = 3.5cm, width = 7cm, ybar,bar width=10pt, xmin=5,xmax=11,ymin=0,ymax=0.5, 
    xtick={6,7,8,9,10},
    ytick={0,0.1,0.2,0.3,0.4},
    xticklabels={6,7,8,9,10},
    yticklabels={0,0.1,0.2,0.3,0.4},
    xlabel=$d$,ylabel=probability]
        \addplot[fill=black!40, draw=black] coordinates {
    (6,0.35) 
    (7,0.3) 
    (8,0.05) 
    (9,0.2) 
    (10,0.1) 
};
    \end{axis}
\end{tikzpicture}

\vspace{-1.2cm}

\begin{flalign*}
\text{(c)   }\text{P}(D>\text{7})&=\text{1}-\text{P}(D\leqslant\text{7}) &\\
&=\text{1}-\text{0.65}\\
&=\text{0.35}
\end{flalign*}
\end{tcolorbox}

\pagebreak

[]{#ex61q}

#### [Exercise 6.1](#ex61a) {-}

\begin{enumerate}
    \item Explain why each of the following tables do not represent a tabulated probability distribution. 
    \begin{enumerate}
        \begin{multicols}{2}
        \item[(a)]
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c }
            $a$ & 7 & 8 & 9\\
          \hline
            $\text{P}(A=a)$ & 0.6 & 0.3 & 0.2 
        \end{tabular}
        \egroup
        \item[(c)] 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c }
            $c$ & red & blue & green\\
          \hline
            $\text{P}(C=c)$ & $\frac{\text{1}}{\text{3}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{2}}$ 
        \end{tabular}
        \egroup
        \item[(b)] 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c }
            $b$ & 2 & 5 & 10\\
          \hline
            $\text{P}(B=b)$ & $\frac{\text{1}}{\text{5}}$ & $\frac{\text{1}}{\text{5}}$ & $\frac{\text{2}}{\text{5}}$
        \end{tabular}
        \egroup
        \item[(d)] 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c }
            $d$ & 2 & 4 & 6\\
          \hline
            $\text{P}(D=d)$ & 0.9 & $-\text{0.3}$ & 0.4 
        \end{tabular}
        \egroup
        \end{multicols}
    \end{enumerate}
    \item Each table below represents the probability distribution of a discrete random variable. Determine the value of $k$ for each.
    \begin{enumerate}
        \begin{multicols}{2}
        \item[(a)]
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c }
            $q$ & 1 & 2 & 3 & 4\\
          \hline
            $\text{P}(Q=q)$ & 0.3 & 0.2 & $k$ & 0.1 
        \end{tabular}
        \egroup
        \item[(c)] 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c }
            $s$ & 5 & 10 & 15\\
          \hline
            $\text{P}(S=s)$ & $\frac{\text{1}}{\text{10}}$ & $\frac{\text{7}}{\text{10}}$ & $k$ 
        \end{tabular}
        \egroup
        \item[(b)] 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c }
            $r$ & 0 & 1 & 2\\
          \hline
            $\text{P}(R=r)$ & 0.4 & $\text{2}k$ & $k$
        \end{tabular}
        \egroup
        \item[(d)] 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c }
            $t$ & 1 & 2 & 3 & 4\\
          \hline
            $\text{P}(T=t)$ & $\text{2}k$ & $\text{4}k$ & $\text{6}k$ & $\text{8}k$ 
        \end{tabular}
        \egroup
        \end{multicols}
    \end{enumerate}
    \item The discrete random variable $X$ has probability distribution:
    \begin{center}
    \bgroup
    \def\arraystretch{1.5}
    \begin{tabular}{ c | c c c c c c c c }
        $x$ & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\
      \hline
        $\text{P}(X=x)$ & 0.15 & 0.2 & 0.1 & 0.05 & $c$ & 0.1 & 0.08 & 0.02 
    \end{tabular}
    \egroup
    \end{center}
    Calculate:
    \begin{enumerate}
        \begin{multicols}{4}
        \item The value of $c$.
        \item $\text{P}(X=\text{4})$.
        \item $\text{P}(X<\text{4})$.
        \item $\text{P}(X\leqslant\text{4})$.
        \item $\text{P}(X>\text{4})$.
        \item $\text{P}(X\geqslant\text{4})$.
        \item $\text{P}(\text{2}<X<\text{5})$.
        \item $\text{P}(\text{2}\leqslant X\leqslant \text{5})$.
        \end{multicols}
    \end{enumerate}
    \item A bag contains nine counters numbered 1 to 9. Two are selected at random, without replacement. Tabulate the probability distribution for the random variable $E$, representing the number of even numbers selected.
    \item The discrete random variable $X$ has probability distribution given by the function $\text{P}(X=x)=k(x+\text{1})$, where $k$ is a constant and $X$ takes values $x=\text{0},\text{1},\text{2},\text{3}$.
    \begin{enumerate}
        \item Tabulate the probability distribution for $X$.
        \item Find $\text{P}(X\geqslant\text{2})$.
    \end{enumerate}
    \item The discrete random variable $X$ has probability distribution given by the function $\text{P}(X=x)=kx^\text{2}$, where $k$ is a constant and $X$ takes values $x=\text{1},\text{2},\text{3},\text{4}$.
    \begin{enumerate}
        \item Tabulate the probability distribution for $X$.
        \item Find $\text{P}(X<\text{4})$.
    \end{enumerate}
    \item Tabulate the probability distribution of each of the following discrete random variables:
    \begin{enumerate}
        \item $F$, the number of fives obtained when two cubical dice are rolled.
        \item $T$, the number of tails obtained when three coins are tossed.
        \item $S$, the sum obtained when two cubical dice are rolled.
    \end{enumerate}
\end{enumerate}

\pagebreak

## The Expectation of a Discrete Random Variable

Whilst a single roll of a die is equally likely to land on any of the numbers from 1 to 6, if it is rolled many times and the *mean* of the observed values is calculated, it is very likely to be around 3.5. Letting random variable $X$ represent the result of one roll of the die, the *long-run mean* of repeated observations of $X$ will tend towards 3.5. This can be referred to as the *mean*, $\mu$, of $X$, the **expectation** of $X$, or $\text{E}(X)$.

\begin{centering}
\tcbset{width=10cm}
\begin{tcolorbox}[adjusted title=The expectation $\mu$ of discrete random variable $X$:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
$\text{E}(X)=\sum{x_i\text{P}(X=x_i)}$
\end{tcolorbox}
\end{centering}

The calculated mean of a finite number of observations of a random variable is likely to not be perfectly equal to the true *expected value*. However, the mean of repeated observations will tend towards the expected value as the number of observations increases. This is an illustration of the *law of large numbers*.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Given the probability distribution of random variable $X$ tabulated below, calculate $\text{E}(X)$.

\vspace{-0.2cm}

\begin{center}
\bgroup
\def\arraystretch{1.5}
\begin{tabular}{ c | c c c c }
      $x$ & 3 & 4 & 5 & 6\\
  \hline
      $\text{P}(X=x)$ & $\tfrac{\text{1}}{\text{8}}$ & $\tfrac{\text{1}}{\text{4}}$ & $\tfrac{\text{1}}{\text{2}}$ & $\tfrac{\text{1}}{\text{8}}$ 
\end{tabular}
\egroup
\end{center}

\tcblower
\textbf{Solution:}
$$\text{E}(X) = \text{3}\times \dfrac{\text{1}}{\text{8}} + \text{4}\times \dfrac{\text{1}}{\text{4}} + \text{5}\times \dfrac{\text{1}}{\text{2}} + \text{6}\times \dfrac{\text{1}}{\text{8}}= \dfrac{\text{37}}{\text{8}}=\text{4.625}$$

\vspace{-0.3cm}

\end{tcolorbox}

Note that the expected value is not necessarily a value that the random variable can actually take.

Problems may require a probability distribution to first be tabulated, such as by using a tree diagram.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} A bag contains 4 blue and 6 red cubes. One is drawn at random, followed by another without replacing the first. Let discrete random variable $X$ represent the number of red cubes drawn. Find $\text{E}(X)$.

\tcblower
\textbf{Solution: }
\vskip 0.5cm
\begin{tikzpicture}[grow=right]
\tikzstyle{level 1}=[level distance=3.5cm, sibling distance=3.5cm]
\tikzstyle{level 2}=[level distance=3.5cm, sibling distance=2cm]
\tikzstyle{bag} = [text width=4em, text centered]
\tikzstyle{end} = [circle, minimum width=3pt,fill, inner sep=0pt]
\node[bag] {}
    child {
        node[bag] {red}        
            child {
                node[end, label=right:
                    {red\hspace{1.2cm}$\implies\frac{\text{30}}{\text{90}}=\frac{\text{1}}{\text{3}}$}] {}
                edge from parent
                node[above] {}
                node[below]  {$\frac{\text{5}}{\text{9}}$}
            }
            child {
                node[end, label=right:
                    {blue\hspace{1cm}$\implies\frac{\text{24}}{\text{90}}=\frac{\text{4}}{\text{15}}$}] {}
                edge from parent
                node[above] {$\frac{\text{4}}{\text{9}}$}
                node[below]  {}
            }
            edge from parent 
            node[above] {}
            node[below]  {$\frac{\text{6}}{\text{10}}$}
    }
    child {
        node[bag] {blue}        
        child {
                node[end, label=right:
                    {red\hspace{1.2cm}$\implies\frac{\text{24}}{\text{90}}=\frac{\text{4}}{\text{15}}$}] {}
                edge from parent
                node[above] {}
                node[below]  {$\frac{\text{6}}{\text{9}}$}
            }
            child {
                node[end, label=right:
                    {blue\hspace{1cm}$\implies\frac{\text{12}}{\text{90}}=\frac{\text{2}}{\text{15}}$}] {}
                edge from parent
                node[above] {$\frac{\text{3}}{\text{9}}$}
                node[below]  {}
            }
        edge from parent         
            node[above] {$\frac{\text{4}}{\text{10}}$}
            node[below]  {}
    };
\end{tikzpicture}

\vspace{-0.3cm}

\bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c }
            $x$ & 0 & 1 & 2\\
          \hline
            $\text{P}(X=x)$ & $\tfrac{\text{2}}{\text{15}}$ & $\tfrac{\text{8}}{\text{15}}$ & $\tfrac{\text{1}}{\text{3}}$ 
        \end{tabular}
        \egroup
$$\text{E}(X)=\text{0}\times \frac{\text{2}}{\text{15}}+\text{1}\times \frac{\text{8}}{\text{15}}+\text{2}\times \frac{\text{1}}{\text{3}}=\frac{\text{6}}{\text{5}}=\text{1.2}$$
\end{tcolorbox}

\pagebreak

[]{#ex62q}

#### [Exercise 6.2](#ex62a) {-}

\begin{enumerate}
    \item Calculate the expected value for each of the probability distributions below.
    \begin{enumerate}
        \begin{multicols}{2}
        \item
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c }
            $x$ & 2 & 4 & 6 & 8\\
          \hline
            $\text{P}(X=x)$ & 0.25 & 0.4 & 0.2 & 0.15 
        \end{tabular}
        \egroup
        \item 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c c }
            $y$ & 1 & 2 & 3 & 4 & 5\\
          \hline
            $\text{P}(Y=y)$ & $\frac{\text{1}}{\text{20}}$ & $\frac{\text{7}}{\text{20}}$ & $\frac{\text{3}}{\text{20}}$ & $k$ & $\frac{\text{1}}{\text{20}}$ 
        \end{tabular}
        \egroup
        \end{multicols}
    \end{enumerate}
    \item The random variable $X$ represents the result of a roll of a fair, octahedral die with sides numbered 1 to 8.
    \begin{enumerate}
        \item Tabulate the probability distribution of $X$.
        \item State $\text{P}(\text{4}\leqslant X\leqslant \text{6})$.
        \item Calculate $\text{E}(X)$.
    \end{enumerate}
    \item A discrete random variable $X$ can assume values 10 and 20 only. Given $\text{E}(X)=\text{16}$, tabulate the probability distribution of $X$.
    \item A box contains 3 red marbles and 5 green marbles. Two marbles are taken at random without replacement, and $X$ is the number of green marbles obtained. Find the expectation of $X$.
    \item A box contains 3 red marbles and 5 green marbles. Two marbles are taken at random with replacement, and $Y$ is the number of green marbles obtained. Find the expectation of $Y$.
    \item In the UKMT Senior Maths Challenge, 4 points are gained for a question answered correctly and 1 point is lost for a question answered incorrectly. A candidate guesses two questions, picking at random from the 5 choices for each question. Let random variable $Y$ represent the points gained from those two questions.
    \begin{enumerate}
        \item Tabulate the probability distribution of $Y$.
        \item Calculate $\text{E}(Y)$.
    \end{enumerate}
    \item A bag contains three £1 coins and two £2 coins. Two coins are taken at random, without replacement. Let discrete random variable $M$ represent the amount of money that is taken from the bag, in pounds.
    \begin{enumerate}
        \item Tabulate the probability distribution of $M$.
        \item Calculate $\mu$, the mean value of $M$.
    \end{enumerate}
    \item A game costs £4 to enter and consists of tossing a coin three times.
    \begin{itemize}
        \item £8 is paid out if the coin comes up tails three times.
        \item £5 is paid out if the coin comes up tails exactly twice.
        \item £2 is paid out if the coin only comes up tails once.
        \item Nothing is paid out if the coin shows heads three times.
    \end{itemize}
    Let the random variable $W$ represent the profit, in pounds, that a player makes if the game is played once.  
    \begin{enumerate}
        \item Tabulate the probability distribution for $W$. 
        \item Calculate $\text{E}(W)$.
    \end{enumerate}
    \item The probability distribution of the discrete random variable $X$ is tabulated below.
    \begin{center}
    \begin{tabular}{ c | c c c c c }
        $x$ & 1 & 3 & 5 & 8 & 10\\
      \hline
        $\text{P}(X=x)$ & 0.1 & $a$ & 0.3 & $b$ & 0.2 
    \end{tabular}
    \end{center}
    Given that $\text{E}(X)=\text{6.3}$, find the values of $a$ and $b$.
\end{enumerate}

\pagebreak

## The Law of Expectation

If discrete random variable $X$ takes values ${x_\text{1},x_\text{2},\dots ,x_n}$ with probabilities $\text{P}(X=x_i)$, then random variable \mbox{$Y=\text{2}X$} takes values ${\text{2}x_\text{1},\text{2}x_\text{2},\dots,\text{2}x_n}$ with probabilities $\text{P}(X=x_i)$. For example, let $X$ represent the roll of a die:

\begin{figure}[H]
  \centering
\captionsetup[figure]{labelformat=empty}%
\begin{minipage}{.45\textwidth}
\centering
\begin{center}
\bgroup
\def\arraystretch{1.5}
\begin{tabular}{ c | c c c c c c }
      $x$ & 1 & 2 & 3 & 4 & 5 & 6\\
  \hline
      $\text{P}(X=x)$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ 
\end{tabular}
\egroup
\end{center}
\captionof{figure}{$\text{E}(X)=\text{1}\times \frac{\text{1}}{\text{6}}+...+\text{6}\times \frac{\text{1}}{\text{6}}=\text{3.5}$}
  \label{fig:expx}
\end{minipage}%
  \centering
\begin{minipage}{.1\textwidth}
  \centering
\end{minipage}%
  \centering
\begin{minipage}{.45\textwidth}
  \centering
\begin{center}
\bgroup
\def\arraystretch{1.5}
\begin{tabular}{ c | c c c c c c }
      $y$ & 2 & 4 & 6 & 8 & 10 & 12\\
  \hline
      $\text{P}(Y=y)$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ 
\end{tabular}
\egroup
\end{center}
\captionof{figure}{$\text{E}(\text{2}X)=\text{E}(Y)=\text{2}\times \frac{\text{1}}{\text{6}}+...+\text{12}\times \frac{\text{1}}{6}=7$}
  \label{fig:exp2x}
\end{minipage}
\end{figure}

(Note that the distribution of $2X$ is *not* that of the sum of two *independent* dice rolls.)

It can be seen here that $\text{E}(2X)=2\text{E}(X)$. The expectation of a random variable that is a *linear transformation* of another random variable can be calculated using following law:

\begin{centering}
\tcbset{width=10cm}
\begin{tcolorbox}[adjusted title=For random variable $X$ with constants $a$ and $b$:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
$\text{E}(aX\pm b)=a\text{E}(X)\pm b$
\end{tcolorbox}
\end{centering}

This shows that expectation is *linear*, distributing over addition and multiplication by constants.

Proof:

\vspace{-0.4cm}

\begin{align*}
    \text{E}(aX+ b)&=\sum{(ax_i + b)\text{P}(X=x_i)}\\[0.3em]
    &=\sum{(ax_i)\text{P}(X=x_i)}+ \sum{b{\text{P}(X=x_i)}}\\[0.3em]
    &=a\sum{x_i\text{P}(X=x_i)}+ b\sum{\text{P}(X=x_i)}\\[0.3em]
    &=a\text{E}(X)+ b
\end{align*}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Let $X$ be the random variable such that $\text{E}(X)=\text{3}$. Calculate $\text{E}(\text{4}X-\text{1})$.

\tcblower
\textbf{Solution:}

\vspace{-0.8cm}
\begin{align*}
\text{E}(\text{4}X-\text{1})&=\text{4}\text{E}(X)-1\\
&=\text{4}\times \text{3}-\text{1}\\
&=\text{11}
\end{align*}

\end{tcolorbox}

Given the value $\text{E}(aX\pm b)$, the expectation of $X$ may be determined.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Given that $\text{E}(\text{10}-\text{2}Y)=\text{50}$, determine the value of $\text{E}(Y)$.
\tcblower
\textbf{Solution:}

\vspace{-0.8cm}
\begin{align*}
\text{E}(\text{10}-\text{2}Y)&=\text{50}\\
\text{E}(-\text{2}Y+\text{10})&=\text{50}\\
-\text{2}\text{E}(Y)+\text{10}&=\text{50}\\
-\text{2}\text{E}(Y)&=\text{40}\\
\text{E}(Y)&=-\text{20}
\end{align*}

\end{tcolorbox}

\pagebreak

[]{#ex63q}

#### [Exercise 6.3](#ex63a) {-}

\begin{enumerate}
    \item Calculate:
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\text{E}(X+\text{4})$ given $\text{E}(X)=\text{3}$
        \item $\text{E}(Y-\text{3})$ given $\text{E}(Y)=\text{0.4}$
        \item $\text{E}(\text{2}+Z)$ given $\text{E}(Z)=-\text{5}$
    \end{multicols}
    \end{enumerate}
    \item Find:
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\text{E}(\text{3}X)$ given $\text{E}(X)=\text{2.5}$
        \item $\text{E}(-\frac{\text{1}}{\text{2}}Y)$ given $\text{E}(Y)=\text{8}$
        \item $\text{E}(-W)$ given $\text{E}(W)=-\frac{\text{2}}{\text{3}}$
    \end{multicols}
    \end{enumerate}
    \item Determine the value of:
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\text{E}(\text{2}X-\text{3})$ given $\text{E}(X)=-\text{4}$
        \item $\text{E}(-\frac{\text{1}}{\text{3}}Y+\text{2})$ given $\text{E}(Y)=\text{12}$
        \item $\text{E}(\text{3}-\text{4}C)$ given $\text{E}(C)=\frac{\text{1}}{\text{2}}$
    \end{multicols}
    \end{enumerate}
    \item Determine:
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\text{E}(X)$ given $\text{E}(\text{4}X+\text{3})=\text{15}$
        \item $\text{E}(Y)$ given $\text{E}(\text{4}-Y)=\text{2.4}$
        \item $\text{E}(Q)$ given $\text{E}(\text{5}+\frac{\text{2}}{\text{3}}Q)=-\text{1}$
    \end{multicols}
    \end{enumerate}
    \item The probability distribution of $X$ is tabulated as follows:
    \begin{center}
    \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c }
            $x$ & 4 & 5 & 6 & 7\\
          \hline
            $\text{P}(X=x)$ & 0.3 & 0.5 & $k$ & 0.05 
        \end{tabular}
    \egroup
    \end{center}
    Determine the values of:
    \begin{enumerate}
    \begin{multicols}{4}
        \item $k$
        \item $\text{P}(\text{4}<X\leqslant \text{6})$
        \item $\text{E}(X)$
        \item $\text{E}(\text{4}X+\text{1})$
    \end{multicols}
    \end{enumerate}
    \item In a board game a fair, tetrahedral die with faces numbered from 1 to 4 is thrown, and the result is multiplied by 3 to give the number of places a player can move. Let random variable $M$ represent the number of places a player can move. Determine the mean, $\mu$, of $M$.
    \item Random variables $X$ and $Y$ are defined such that the mean of $X$ is $\frac{\text{1}}{\text{4}}$ and $Y=\text{6}X+\text{4}$. Determine the mean of $Y$.
    \item A betting game involves a player rolling a fair, octagonal die with faces numbered from 1 to 8. Let $X$ represent the result of a roll of the die.
    \begin{enumerate}
    \item Determine $\text{E}(X)$.
    \end{enumerate}
    Each game costs £10 to enter, with the number obtained of a single roll of the die being multiplied by 2 to give an amount in pounds that the player receives. Let $Y$ represent the \textit{profit} a player makes from playing the game a single time.
    \begin{enumerate}[resume]
        \item State an equation linking $Y$ and $X$.
        \item Determine the value of $\text{E}(Y)$.
        \item Explain what this suggests will happen if a player plays the game repeatedly.
    \end{enumerate}
    \item Random variables $X$ and $Y$ are defined such that the mean of $Y$ is $-\text{5}$ and $Y=\text{2}X-\text{10}$. Determine the mean of $X$.
\end{enumerate}

\pagebreak

## The Variance of a Random Variable

The *variance* of the values observed from repeated rolls of a fair cubical die will tend towards a fixed value in the long-run. Letting the random variable $X$ represent the result of a roll of a die, the **variance**, $\sigma^\text{2}$, of $X$ is $\frac{\text{35}}{\text{12}}$, or $\text{V}(X)=\frac{\text{35}}{\text{12}}$.

\begin{centering}
\tcbset{width=10cm}
\begin{tcolorbox}[adjusted title=The variance $\sigma^\text{2}$ of random variable $X$:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
$\text{V}(X)=\text{E}(X^\text{2})-\left(\text{E}(X)\right)^\text{2}$
\end{tcolorbox}
\end{centering}

As a reminder, the variance measures how spread out the values of a random variable are about the mean.

Note that $\text{E}\left(X^\text{2}\right)$ is not equal to $\left(\text{E}(X)\right)^\text{2}$.

Proof:

\vspace{-0.4cm}

\begin{align*}
    \text{V}(X)&=\text{E}[(X-\mu)^\text{2}]\\[0.3em]
    &=\text{E}[(X-\mu)(X-\mu)]\\[0.3em]
    &=\text{E}[X^\text{2}-\text{2}\mu X+\mu^\text{2}]\\[0.3em]
    &=\text{E}(X^\text{2})-\text{2}\mu \text{E}(X)+\mu^\text{2}\\[0.3em]
    &=\text{E}(X^\text{2})-\text{2}(\text{E}(X))^\text{2} +(\text{E}(X))^\text{2}\\[0.3em]
    &=\text{E}(X^\text{2})-\left(\text{E}(X)\right)^\text{2}
\end{align*}

Knowing the *expectation* and *variance* of random variables help statisticians better understand the *long-run* behaviour of repeated observations:

\begin{itemize}
    \item $\text{E}(X)=\mu_X$, the \textit{long-run mean} of the distribution of $X$.
    \item $\text{V}(X)=\sigma_X^\text{2}$, the \textit{variance} of the distribution of $X$.
\end{itemize}

The standard deviation, $\sigma$, of a random variable $X$, notated $\text{SD}(X)$, is the square root of the variance:

$$\text{SD}(X)=\sqrt{\text{V}(X)}\qquad\text{and}\qquad \text{SD}(X),\text{V}(X)\geqslant\text{0}$$

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} The probability distribution of random variable $X$ is given below: 

\begin{center}
\begin{tabular}{ c | c c c c }
      $x$ & 0 & 1 & 2 & 3\\
  \hline
      $\text{P}(X=x)$ & 0.3 & 0.4 & 0.1 & 0.2 
\end{tabular}
\end{center}

Calculate $\text{E}(X)$ and $\text{V}(X)$

\tcblower
\textbf{Solution:}\textit{ (Remember that $\text{E}(X^\text{2})$ is not the variance.)}

\vspace{-0.3cm}
\begin{align*}
\text{E}(X) &= \text{0}\times \text{0.3} + \text{1}\times \text{0.4} + \text{2}\times \text{0.1} + \text{3}\times \text{0.2}= \text{1.2}\\[1em]
\text{E}(X^\text{2}) &= \text{0}^\text{2}\times \text{0.3} + \text{1}^\text{2}\times \text{0.4} + \text{2}^\text{2}\times \text{0.1} + \text{3}^\text{2}\times \text{0.2}= \text{2.6}\\[1em]
\text{V}(X) &= \text{E}(X^\text{2})-\text{E}^\text{2}(X)\\
&= \text{2.6} - \text{1.2}^\text{2}\\
&= \text{1.16}
\end{align*}

\end{tcolorbox}

\pagebreak

[]{#ex64q}

#### [Exercise 6.4](#ex64a) {-}

\begin{enumerate}
    \item Calculate the mean and variance of each of the following probability distributions.
    \begin{enumerate}
        \begin{multicols}{2}
        \item
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c }
            $x$ & 1 & 2 & 5 & 10\\
          \hline
            $\text{P}(X=x)$ & 0.4 & 0.3 & 0.2 & 0.1 
        \end{tabular}
        \egroup
        \item 
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c c }
            $y$ & 0 & 1 & 2 & 3 & 4\\
          \hline
            $\text{P}(Y=y)$ & $\frac{\text{1}}{\text{10}}$ & $\frac{\text{1}}{\text{5}}$ & $\frac{\text{1}}{\text{4}}$ & $k$ & $\frac{\text{2}}{\text{5}}$ 
        \end{tabular}
        \egroup
        \end{multicols}
    \end{enumerate}
    \item The random variable $X$ represents the result of a roll of a fair, tetrahedral die with sides numbered 1 to 4.
    \begin{enumerate}
        \item Tabulate the probability distribution of $X$.
        \item Find $\text{E}(X)$.
        \item Calculate $\text{V}(X)$.
    \end{enumerate}
    \item A box contains 6 pink marbles and 4 orange marbles. Two marbles are taken at random without replacement, and $X$ is the number of pink marbles obtained. Find the expectation and variance of $X$.
    \item A box contains 2 red marbles and 6 green marbles. Two marbles are selected at random with replacement, and $Y$ is the number of green marbles obtained. Find $\text{E}(Y)$ and $\text{V}(Y)$.
    \item A discrete random variable $X$ can assume values 4 and 12 only. Given $\text{E}(X)=\text{10}$, determine the variance of $X$.
    \item A multiple-choice quiz gives four possible answers for each question, with 4 marks awarded for a correct answer and 1 mark taken away for an incorrect answer. Determine the expected gain in marks when the answer to a single question is guessed, and the variance in the number of marks gained.
    \item A game costs £10 to enter, and the player rolls two fair, cubical dice together. If both dice show a six the player wins £50, a single six means the player gets £10 back and no sixes means the player gets nothing. Determine the mean and variance in the amount of profit for playing the game once.
    \item A fair coin is tossed three times. Let random variable $X$ represent the number of tails shown.
    \begin{enumerate}
        \item Tabulate the probability distribution of $X$.
        \item Find $\text{E}(X)$ and $\text{V}(X)$.
    \end{enumerate}
    \item The random variable $X$ takes values 7, 8 and 9. Given $\text{P}(X=\text{8})=p$ and $\text{P}(X=\text{7})=\text{P}(X=\text{9})$:
    \begin{enumerate}
        \item Determine $\text{E}(X)$.
        \item Given $\text{V}(X)=\text{0.8}$, determine the value of $p$.
    \end{enumerate}
    \item Random variable $Y$ takes the value 1 with probability 0.9 and otherwise takes the value $k$. Determine the value of $k$ if $\text{V}(Y)=\text{0}$.
\end{enumerate}

\pagebreak

## The Law of Variance

Since variance is based on *squared* differences from the mean, $\text{V}(\text{2}X)\ne\text{2}\text{V}(X)$.

\begin{centering}
\tcbset{width=10cm}
\begin{tcolorbox}[adjusted title=For random variable $X$ with constants $a$ and $b$:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
$\text{V}(aX\pm b)=a^\text{2}\text{V}(X)$
\end{tcolorbox}
\end{centering}

This shows that multiplying a random variable by a constant changes its variance by the square of that constant, while adding a constant does not affect the variance. In contrast to expectation, variance is *not linear* and does not distribute over addition or multiplication by constants.

Proof:

\vspace{-0.4cm}

\begin{align*}
    \text{V}(aX + b) &= \text{E}\big[(aX + b - \text{E}(aX + b))^\text{2}\big]\\[0.5em]
    &=\text{E}\big[(aX+b-a\text{E}(X)-b)^\text{2}\big]\\[0.5em]
    &=\text{E}\big[(aX-a\text{E}(X))^\text{2}\big]\\[0.5em]
    &=\text{E}\big[(a(X-\text{E}(X)))^\text{2}\big]\\[0.5em]
    &=\text{E}[a^\text{2}(X-\text{E}(X))^\text{2}]\\[0.5em]
    &=a^\text{2} \text{E}[(X-\text{E}(X))^\text{2}]\\[0.5em]
    &=a^\text{2} \text{V}(X)
\end{align*}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Let $X$ be the random variable such that $\text{E}(X)=-\text{7}$ and $\text{V}(X)=\text{4}$. Calculate $\text{V}(\text{2}-\text{3}X)$.

\tcblower
\textbf{Solution:}\textit{ (It helps to rearrange into the form $aX\pm b$.)}

\vspace{-0.1cm}

\begin{align*}
\text{V}(\text{2}-\text{3}X)&=\text{V}(-\text{3}X+\text{2})\\
&=(-\text{3})^\text{2}\text{V}(X)\\
&=\text{9}\times \text{4}\\
&=\text{36}
\end{align*}

\vspace{-0.3cm}

\end{tcolorbox}

Note that any laws relating to the *standard deviation* of a linear transformation ($\text{SD}(aX\pm b)$) cannot be expressed as concisely, so such problems must be tackled by *first finding the variance* ($\text{V}(aX\pm b)$).

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Random variable $Y$ has mean 1.5 and standard deviation 0.8.\\ Determine the standard deviation of $\text{10}Y+\text{25}$.

\tcblower
\textbf{Solution:}

\vspace{-0.3cm}

\begin{align*}
\text{V}(\text{10}Y+\text{25})&=\text{10}^\text{2}\text{V}(Y)\\
&=\text{100}\times \text{0.8}^\text{2}\\
&=\text{64}\\
\text{SD}(\text{10}Y+\text{25})&=\text{8}
\end{align*}

\vspace{-0.3cm}

\end{tcolorbox}

\pagebreak

[]{#ex65q}

#### [Exercise 6.5](#ex65a) {-}

\begin{enumerate}
    \item Given $\text{E}(X)=\text{6}$ and $\text{V}(X)=\text{8}$, determine the values of:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(\text{2}X)$
            \item $\text{V}(\text{2}X)$
            \item $\text{SD}(\text{2}X)$
        \end{multicols}
    \end{enumerate}
    \item Given $\text{E}(X)=-\text{2}$ and $\text{V}(X)=\text{3}$, determine the values of:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(X+\text{5})$
            \item $\text{V}(X+\text{5})$
            \item $\text{SD}(X+\text{5})$
        \end{multicols}
    \end{enumerate}
    \item Given $\text{E}(X)=\text{1.25}$ and $\text{SD}(X)=\text{0.64}$, determine the values of:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(\text{3}X-\text{2})$
            \item $\text{V}(\text{3}X-\text{2})$
            \item $\text{SD}(\text{3}X-\text{2})$
        \end{multicols}
    \end{enumerate}
    \item Given $\text{E}(X)=\text{500}$ and $\text{V}(X)=\text{400}$, determine the values of:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(\text{0.1}X+\text{10})$
            \item $\text{V}(\text{0.1}X+\text{10})$
            \item $\text{SD}(\text{0.1}X+\text{10})$
        \end{multicols}
    \end{enumerate}
    \item The discrete random variable $X$ has the following probability distribution.
        \begin{center}
        \bgroup
        \def\arraystretch{1.5}
        \begin{tabular}{ c | c c c c }
            $x$ & 1 & 2 & 4 & 8\\
          \hline
            $\text{P}(X=x)$ & 0.1 & 0.5 & 0.3 & 0.1 
        \end{tabular}
        \egroup
        \end{center}
        \begin{enumerate}
        \begin{multicols}{3}
            \item Calculate $\text{E}(X)$ and $\text{V}(X)$.
            \item Find $\text{E}(\text{2}X+\text{1})$.
            \item Find $\text{V}(\text{2}X+\text{1})$.
        \end{multicols}
        \end{enumerate}
        \item Given $\text{E}(Y)=-\text{5}$ and $\text{V}(Y)=\text{3}$, determine the values of:
        \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(-\text{3}Y-\text{2})$
            \item $\text{V}(-\text{3}Y-\text{2})$
            \item $\text{SD}(-\text{3}Y-\text{2})$
        \end{multicols}
        \end{enumerate}
        \item Random variable $X$ has a mean of 2.4 and a standard deviation of 0.8. Find:
        \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(\text{1}-\text{10}X)$
            \item $\text{V}(\text{1}-\text{10}X)$
            \item $\text{SD}(\text{1}-\text{10}X)$
        \end{multicols}
        \end{enumerate}
        \item Given random variable $X$ such that $\text{E}(\text{4}X-\text{1})=\text{23}$ and $\text{V}(\text{4}X-\text{1})=\text{80}$, determine the values of $\text{E}(X)$ and $\text{V}(X)$.
        \item Given random variable $Y$ such that $\text{E}(\text{3}Y+\text{12})=\text{0}$ and $\text{V}(\text{3}Y+\text{12})=\text{81}$, determine the mean and standard deviation of $Y$.
        \item Given random variables $X$ and $Z$ such that $\text{E}(Z)=\text{0}$, $\text{V}(Z)=\text{1}$ and $X=a+bZ$:
        \begin{enumerate}
            \item State $\text{SD}(Z)$.
            \item Find $\text{E}(X)$.
            \item Determine the values of $\text{V}(X)$ and $\text{SD}(X)$.
        \end{enumerate}
\end{enumerate}

\pagebreak

## Combining Random Variables

As well as linear transformations of a single random variable, new variables can be created by adding (or subtracting) random variables. Given random variables $X$ and $Y$, for example, $W = X + Y$ is a new random variable formed from them. When studying the long-run behaviour of combined random variables, by considering their expectation and variance, it is important to consider whether the variables are *independent*. The laws relating to variance below *only* apply when the variables are independent.

\begin{centering}
\begin{tcolorbox}[adjusted title=For random variables $X$ and $Y$:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\vspace{-0.3cm}
\begin{equation*}
  \begin{split}
    \text{For all }&X\text{ and }Y\text{:}\\[7pt]
    \text{E}(X+Y) &= \text{E}(X)+\text{E}(Y)\\[7pt]
    \text{E}(X-Y) &= \text{E}(X)-\text{E}(Y)\\[7pt]
    \text{E}(aX\pm bY) &= a\text{E}(X)\pm b\text{E}(Y)
  \end{split}
\quad\text{ and }\quad
  \begin{split}
    \text{For independent }&X\text{ and }Y\text{:}\\[7pt]
    \text{V}(X+Y) &= \text{V}(X)+\text{V}(Y)\\[7pt]
    \text{V}(X-Y) &= \text{V}(X)+\text{V}(Y)\\[7pt]
    \text{V}(aX\pm bY) &= a^\text{2}\text{V}(X)+ b^\text{2}\text{V}(Y)
  \end{split}
\end{equation*}

\end{tcolorbox}
\end{centering}

If $X$ and $Y$ are not independent variables then determining $\text{V}(X\pm Y)$ is beyond the scope of the course.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Two independent random variables $F$ and $G$ have means of 15 and 12 and standard deviations of 3 and 4 respectively. Calculate $\text{E}(\text{3}G-\text{2}F)$ and $\text{V}(F-G)$.

\tcblower
\textbf{Solution:}\text{ ($\text{E}(F)=\text{15},\text{E}(G)=\text{12},\text{SD}(F)=\text{3},\text{SD}(G)=\text{4}$)}

\vspace{-1.2cm}
\begin{multicols}{2}
\null\vfill
\begin{align*}
\text{E}(\text{3}G-\text{2}F)&=\text{3}\text{E}(G)-\text{2}\text{E}(F)\\
&=\text{3}\times \text{12} - \text{2}\times \text{15}\\
&=\text{36}-\text{30}\\
&=\text{6}
\end{align*}
\vfill\null
\columnbreak
\null\vfill
\begin{align*}
\text{V}(F)&=\text{3}^\text{2}=\text{9}\\
\text{V}(G)&=\text{4}^\text{2}=\text{16}\\
\text{V}(F-G)&=\text{V}(F)+\text{V}(G)\\
&=\text{9}+\text{16}\\
&=\text{25}
\end{align*}
\vfill\null
\end{multicols}

\vspace{-1.4cm}

\end{tcolorbox}

Random variables **independently and identically distributed (i.i.d)** with the same distribution as $X$ are denoted as $X_\text{1},X_\text{2},X_{3},\dots$

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Books in the fiction section of a library have a mean thickness of 3.1cm with standard deviation 0.2cm. If three books are randomly selected from the fiction section and stacked together, determine the mean and standard deviation of the total thickness of the three books, stating one assumption required.

\tcblower
\textbf{Solution:} Let $X$ represent the thickness of a book, so $\text{E}(X)=\text{3.1}$ and $\text{V}(X)=\text{0.2}^\text{2}=\text{0.04}$\\\vskip 0.1cm

Total thickness $T=X_\text{1}+X_\text{2}+X_\text{3}$. Assuming that the thickness of each book is independent:\\\vskip 0.05cm

$\text{E}(T)=\text{E}(X_\text{1}+X_\text{2}+X_\text{3})=\text{E}(X_\text{1})+\text{E}(X_\text{2})+\text{E}(X_\text{3})=\text{3.1}+\text{3.1}+\text{3.1}=\text{9.3}$\\\vskip 0.05cm

$\text{V}(T)=\text{V}(X_\text{1}+X_\text{2}+X_\text{3})=\text{V}(X_\text{1})+\text{V}(X_\text{2})+\text{V}(X_\text{3})=\text{0.04}+\text{0.04}+\text{0.04}=\text{0.12}$\\\vskip 0.05cm

$\text{SD}(T)=\sqrt{\text{V}(T)}=\sqrt{\text{0.12}}=\text{0.346}$\\\vskip 0.1cm

Hence the mean total thickness of the three books is 9.3cm, and the standard deviation is 0.346cm.

\end{tcolorbox}

\pagebreak

[]{#ex66q}

#### [Exercise 6.6](#ex66a) {-}

\begin{enumerate}
    \item Random variables $J$ and $K$ are defined such that $\text{E}(J)=\text{3}$ and $\text{E}(K)=-\text{2}$.
    \begin{enumerate}
        \item State the information required to be known about $J$ and $K$ in order to determine whether the laws introduced on the previous page may be applied.
        \item Assuming that $J$ and $K$ are such that those laws may be applied, find:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(J+K)$
            \item $\text{E}(J-K)$
            \item $\text{E}(\text{2}K-\text{3}J)$
        \end{multicols}
    \end{enumerate}
    \item Assuming that $J$ and $K$ are such that those laws may be applied, find:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{V}(J+K)$
            \item $\text{V}(J-K)$
            \item $\text{V}(\text{2}K-\text{3}J)$
        \end{multicols}
    \end{enumerate}
    \end{enumerate}
    \item Independent random variables $X$ and $Y$ are defined such that $\text{E}(X)=\text{5}$, $\text{V}(X)=\text{6}$, $\text{E}(Y)=\text{3}$ and $\text{V}(Y)=\text{8}$. Determine the values of:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\text{E}(\text{2}X+\text{6}Y)$
            \item $\text{V}(\text{2}X+\text{6}Y)$
            \item $\text{E}(\text{4}X+\text{5}Y)$
            \item $\text{V}(\text{4}X+\text{5}Y)$
            \item $\text{E}(\frac{\text{1}}{\text{2}}Y-\text{2}X)$
            \item $\text{V}(\frac{\text{1}}{\text{2}}Y-\text{2}X)$
        \end{multicols}
    \end{enumerate}
    \item Random variables $F$ and $G$ have means of 3 and 2 respectively, and standard deviations of 5 and 6 respectively. State the information that is missing which means that it is not currently possible to determine the values of $\text{E}(\text{2}F+G)$ and $\text{V}(\text{2}F+G)$.
    \item Independent random variables $A$ and $B$ have means of 1.5 and 1.2 respectively, and standard deviations of 1 and 0.8 respectively. Determine the values of $\text{E}(A-B)$ and $\text{V}(A-B)$.
    \item Random variable $X$ is defined such that $\text{E}(X)=\text{10}$ and $\text{V}(X)=\text{3}$. Random variables \{$X_\text{1}, X_\text{2}, X_\text{3} \dots$\} represent independent observations of $X$. Determine the mean and variance of $X_\text{1}+X_\text{2}+X_\text{3}+X_\text{4}$, representing the sum of four such observations of $X$.
    \item A spreadsheet contains a large amount of cells, each containing numbers such that the mean of the numbers is 12 and the standard deviation is 1.2. Five numbers from the spreadsheet are selected at random, with replacement. Determine the mean and standard deviation of the total of the five numbers.  
    \item It is known that the mean volume of coffee poured per cup in a staffroom for teachers is 250ml, with a standard deviation of 10ml. Determine the mean and standard deviation of the total volume of coffee used for six cups, stating an assumption required.
    \item Let random variable $X$ represent the number obtained when a fair, cubical die numbered 1 to 6 is thrown, and random variable $Y$ the number obtained when a fair, tetrahedral die numbered 1 to 4 is thrown.
    \begin{enumerate}
        \item Find $\text{E}(X)$ and $\text{E}(Y)$.
        \item Find $\text{V}(X)$ and $\text{V}(Y)$.
        \item Obtain the mean and variance of the result when both dice are thrown and the scores are added together.
    \end{enumerate}
    \item The mean length of a car is 4.5 metres, with a standard deviation of 30 centimetres. Drivers arriving to queue for a ferry are told to line up one in front of another leaving as small a gap as possible between cars. When they do this, the mean gap they leave is 40 centimetres, with a standard deviation of 10 centimetres. Stating two assumptions required, determine the mean and standard deviation of the total length of a line of eight cars asked to line up in this way.
\end{enumerate}

\pagebreak

[]{#re6q}

## [Review Exercise](#re6a) {-}

\begin{enumerate}
    \item A trial consists of tossing two unbiased coins. Let the random variable $X$ represent the number of heads obtained.
    \begin{enumerate}
        \item Tabulate the probability distribution of $X$ after one trial.
        \item Calculate:
        \begin{enumerate}
            \item $\text{E}(X)$.
            \item $\text{V}(X)$.
            \item $\text{SD}(X)$.
        \end{enumerate}
    \end{enumerate}
    \item Two independent random variables $P$ and $Q$ have means 5 and 10 and standard deviations 2 and 3 respectively. Find the mean and variance of each of the random variables:
    \begin{enumerate}
        \item $\text{4}P-\text{8}$.
        \item $\text{3}Q-P$.
    \end{enumerate}
    \item A box contains 4 blue marbles and 5 red marbles. Three marbles are taken from the box without replacement. Let the random variable $X$ represent the number of red marbles taken.
    \begin{enumerate}
        \item Tabulate the probability distribution of $X$.
        \item Calculate the mean and variance of $X$.
    \end{enumerate}
    \item Given that $\text{E}(\text{2}X+\text{6})=\text{16}$ and $\text{V}(\text{2}X+\text{6})=\text{12}$:
    \begin{enumerate}
        \item Calculate $\text{E}(X)$.
        \item Calculate $\text{V}(X)$.
    \end{enumerate}
    \item Two independent random variables $A$ and $B$ have means 53 and 21 and standard deviations 6 and 5 respectively. Find the mean and standard deviations of each of the following random variables:
    \begin{enumerate}
        \item $\text{5}B+\text{6}$.
        \item $\text{2}A-\text{3}B$.
    \end{enumerate}
    \item It is known that items of hand luggage carried by passengers on an airline have mean mass of 5.6kg and a standard deviation of 2.0kg, and that their hold luggage has a mean mass of 22.0kg and a standard deviation 5.0kg.
    \begin{enumerate}
        \item Calculate the mean and standard deviation of the total luggage mass for one passenger, stating an assumption you have made.
    \end{enumerate}
    The passengers themselves have masses with mean 75kg and standard deviation 12kg. A small plane carries 10 passengers.
    \begin{enumerate}[resume]
        \item Calculate the mean and standard deviation of the total load, including passengers and their luggage.
    \end{enumerate}
\end{enumerate}

\pagebreak
