# Discrete Distributions

\begin{center}
\say{\textit{All models are wrong, but some models are useful.}}
\end{center}

### Models, Conditions and Assumptions {-}

The above quote, attributed to the statistician George Box, highlights that no mathematical or statistical *model* can perfectly describe the behaviour of something in the real world. Nevertheless, if a model can get *close enough* then results obtained using it can be sufficiently accurate and useful.

In this chapter, three *discrete probability distributions* that can model real-life data will be introduced:

\begin{itemize}
    \item The Discrete Uniform Distribution
    \item The Binomial Distribution
    \item The Poisson Distribution
\end{itemize}

Studying a problem in context and identifying an appropriate model to use is an important skill for anyone working with data. The validity of the use of a model is based on a number of *conditions* being met. When using a model it is vital to consider the conditions required for its use, and specifically whether they are each satisfied. In this chapter, and subsequent chapters introducing more probability distributions and hypothesis testing, the *conditions for the valid use* of models and tests are clearly indicated as they are introduced.

Sometimes it will be clear that a particular condition has been met, but there will be times when it is unclear. Whenever it is not clear that a condition has been met, statisticians must ask whether they can reasonably make an *assumption* that the condition is satisfied. It should always be recognised when an assumption is required, and it may be necessary to *justify* the use of an assumption in a context.

\pagebreak

## The Discrete Uniform Distribution

Consider the discrete random variables $X$ and $Y$, representing the scores obtained from a cubical die numbered $\{\text{1},\text{2},\text{3},\text{4},\text{5},\text{6}\}$ and a tetrahedral die numbered $\{\text{1},\text{2},\text{3},\text{4}\}$ respectively. Their probability distributions have been tabulated and graphed below, and the expectation and variance calculated for each:

\begin{figure}[H]
  \centering
\captionsetup[figure]{labelformat=empty}%
\begin{minipage}{.45\textwidth}
\begin{center}
\bgroup
\def\arraystretch{1.5}
\begin{tabular}{ c | c c c c c c }
      $x$ & 1 & 2 & 3 & 4 & 5 & 6\\
  \hline
      $\text{P}(X=x)$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$ & $\frac{\text{1}}{\text{6}}$
\end{tabular}
\egroup
\end{center}

\begin{tikzpicture}
\pgfplotsset{
    standard/.style={
    axis line style = thick,
    trig format=rad,
    enlargelimits,
    axis x line=middle,
    axis y line=middle,
    every axis x label/.style={at={(current axis.right of origin)},anchor=north west},
    every axis y label/.style={at={(current axis.above origin)},anchor=south east}
    }
}
    \begin{axis}[standard,x label style={at={(current axis.right of origin)},anchor=west},y label style={at={(current axis.above origin)},anchor=south}, height = 4cm, width = 8cm, ybar,bar width=10pt, xmin=0.5,xmax=6.5,ymin=0,ymax=0.4, xtick={1,2,3,4,5,6},ytick={0,0.1666},yticklabels={0,$\frac{\text{1}}{\text{6}}$},
    xticklabels={$\text{1}$,$\text{2}$,$\text{3}$,$\text{4}$,$\text{5}$,$\text{6}$},
    xlabel=$x$,ylabel=probability]
        \addplot[fill=black!25, draw=black] coordinates {
    (1,0.1666) 
    (2,0.1666) 
    (3,0.1666)
    (4,0.1666) 
    (5,0.1666) 
    (6,0.1666) 
};
    \end{axis}
\end{tikzpicture}

\captionof{figure}{$\text{E}(X)=\text{3.5}\text{ and }\text{V}(X)=\frac{\text{35}}{\text{12}}$}
  \label{fig:discunif}

\end{minipage}%
  \centering
\begin{minipage}{.1\textwidth}
  \centering
\end{minipage}%
  \centering
\begin{minipage}{.45\textwidth}
  \centering

\begin{center}
\bgroup
\def\arraystretch{1.5}
\begin{tabular}{ c | c c c c }
      $y$ & 1 & 2 & 3 & 4\\
  \hline
      $\text{P}(Y=y)$ & $\frac{\text{1}}{\text{4}}$ & $\frac{\text{1}}{\text{4}}$ & $\frac{\text{1}}{\text{4}}$ & $\frac{\text{1}}{\text{4}}$
\end{tabular}
\egroup
\end{center}
  
\begin{tikzpicture}
\pgfplotsset{
    standard/.style={
    axis line style = thick,
    trig format=rad,
    enlargelimits,
    axis x line=middle,
    axis y line=middle,
    every axis x label/.style={at={(current axis.right of origin)},anchor=north west},
    every axis y label/.style={at={(current axis.above origin)},anchor=south east}
    }
}
    \begin{axis}[standard,x label style={at={(current axis.right of origin)},anchor=west},y label style={at={(current axis.above origin)},anchor=south}, height = 4cm, width = 8cm, ybar,bar width=10pt, xmin=4.5,xmax=8.5,ymin=0,ymax=0.4, xtick={5,6,7,8},xticklabels={$\text{1}$,$\text{2}$,$\text{3}$,$\text{4}$},ytick={0,0.25},yticklabels={0,$\frac{\text{1}}{\text{4}}$},xlabel=$x$,ylabel=probability]
        \addplot[fill=black!25, draw=black] coordinates {
    (5,0.25)
    (6,0.25) 
    (7,0.25) 
    (8,0.25) 
};
    \end{axis}
\end{tikzpicture}

\captionof{figure}{$\text{E}(Y)=\text{2.5}\text{ and }\text{V}(Y)=\frac{\text{5}}{\text{4}}$}
  \label{fig:discunif21}

\end{minipage}
\end{figure}

Whilst $X$ and $Y$ do not follow the same distribution, they share key characteristics, namely that they both take a *finite number of integer values*, $\{\text{1},\text{2},\text{3},\dots,k\}$, and that *each of these values is equally likely*. It is these *shared characteristics* that define the *discrete uniform distribution*.

\vspace{0.5cm}

\begin{centering}
\tcbset{width=11cm}
\begin{tcolorbox}[adjusted title=The Discrete Uniform Distribution:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\begin{itemize}
    \item Notated $X\sim \text{U}(k)$, defined by the single parameter $k$.
    \item $X$ takes integer values from 1 to $k$: $\{\text{1},\text{2},\text{3},\dots,k\}$. 
    \item Each outcome is \textit{equally likely}, with probability $\dfrac{\text{1}}{k}$.
\end{itemize}
\end{tcolorbox}
\end{centering}

\vspace{0.5cm}

Parameters define the precise form of a distribution within a *family of distributions*. Here, we can say that $X$ *"is distributed uniformly*" with parameter $k=\text{6}$ (with values from 1 to 6). Using $\sim$, or *"tilde"*, to mean *"is distributed..."*, such statements can be written more efficiently:

$$X\sim \text{U}(\text{6})\quad\text{ and }\quad Y\sim \text{U}(\text{4})$$

The  Data Booklet (**page 4**) gives the formulae to calculate *expectation* and *variance* for the discrete uniform distribution. For $X\sim \text{U}(k)$:

$$\text{E}(X)=\frac{k+\text{1}}{\text{2}}\quad \text{ and }\quad \text{V}(X)=\frac{k^\text{2}-\text{1}}{\text{12}}$$

The previously stated values for the expectation and variance of $X$ and $Y$ can be quickly obtained using these formulae. It also provides the *probability function* (**pf**) for the distribution $\text{U}(k)$ as $\frac{\text{1}}{k}$. Probability functions show how to calculate the probability of any given outcome for a discrete random variable. Here, the probability depends *only on the parameter* $k$.

\pagebreak

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Given $T\sim \text{U}(\text{10})$ and $W=\text{3}T+\text{1}$, calculate $\text{E}(W)$ and $\text{V}(W)$.

\tcblower
\textbf{Solution:}

\vspace{-0.5cm}
\begin{multicols}{2}
\begin{align*}
\text{(a)}\quad \text{E}(T)&=\frac{\text{10}+\text{1}}{\text{2}}=\text{5.5} &\\
\text{E}(W)&=\text{E}(\text{3}T+\text{1})\\
&=\text{3}\text{E}(T)+\text{1}\\
&=\text{3}\times \text{5.5} + \text{1}\\
&=\text{17.5}
\end{align*}

\begin{align*}
\text{(b)}\quad \text{V}(T)&=\frac{\text{10}^\text{2}-\text{1}}{\text{12}}=\text{8.25} &\\
\text{V}(W)&=\text{V}(\text{3}T+\text{1})\\
&=\text{3}^\text{2}\text{V}(T)\\
&=\text{9}\times \text{8.25}\\
&=\text{74.25}
\end{align*}
\end{multicols}

\end{tcolorbox}

[]{#ex71q}

#### [Exercise 7.1](#ex71a) {-}

\begin{enumerate}
    \item Let $X\sim \text{U}(\text{5})$. Calculate the mean and variance of $X$.
    \item Let $X\sim \text{U}(\text{15})$. Calculate the mean and variance of $X$.
    \item A discrete random variable is uniformly distributed such that $\text{P}(X=x)=\frac{\text{1}}{k}$, with $k=\text{8}$.
    \begin{enumerate}
        \item Calculate $\text{E}(X)$ and $\text{V}(X)$.
        \item Evaluate $\text{E}(\text{2}X+\text{5})$ and $\text{V}(\text{2}X+\text{5})$.
    \end{enumerate}
    \item A regular, unbiased icosahedral die is rolled. Let the random variable $X$ be the score on the topmost face.
    \begin{enumerate}
        \item State the distribution of $X$.
        \item Determine the values of $\text{E}(X)$ and $\text{V}(X)$.
        \item Evaluate $\text{E}(\text{1}-\text{3}X)$ and $\text{V}(\text{1}-\text{3}X)$.
    \end{enumerate}
    \item Two independent random variables $X$ and $Y$ are defined such that $X\sim \text{U}(\text{3})$ and $Y \sim \text{U}(\text{5})$.
    \begin{enumerate}
        \item Calculate $\text{E}(X-Y)$.
        \item Calculate $\text{V}(X-Y)$.
    \end{enumerate}
    \item Given $X\sim \text{U}(k)$ such that $\text{E}(X)=\text{5.5}$:
    \begin{enumerate}
        \item Determine the value of $k$.
        \item State $\text{P}(\text{2}\leqslant X<\text{6})$.
        \item Find the standard deviation of $X$.
    \end{enumerate}
    \item Given $Y \sim \text{U}(k)$ such that the standard deviation of $Y$ is $\frac{\sqrt{\text{21}}}{\text{2}}$:
    \begin{enumerate}
        \item Determine the value of $k$.
        \item Find $\text{E}(\text{1}-\text{2}Y)$.
    \end{enumerate}
    \item Discrete, independent random variables $X$ and $Y$ are uniformly distributed such that:
    \begin{itemize}
        \item $\text{P}(X=\text{1})<\text{P}(Y=\text{1})$
        \item $\text{E}(X-Y)=\text{2}$ and $\text{V}(X-Y)=\text{14}$
    \end{itemize}
    Determine the distributions of $X$ and $Y$.
\end{enumerate}

\pagebreak

## The Binomial Distribution

A *Bernoulli trial* is an experiment in which each trial has only two possible outcomes, such as a coin landing on either *heads* or *tails*, or asking a *yes or no* question in a survey. These responses can be more generally referred to as *successes* or *failures*. The *binomial distribution* models the **number of successes** obtained from a *fixed number* of *independent* Bernoulli trials. 

A simple example is tossing a coin three times and counting the number of *heads* obtained:

\begin{center}
    \begin{tikzpicture}
        \def\r{0.5cm}
        \foreach \y in {0,1.2,2.4}{
        \draw[shift={(\y,0)},thick, rounded corners=2pt] 
        (0:\r) \foreach \x in {51.43, 102.86, ..., 359} {
        -- (\x:\r)
        } -- cycle;
        }
        \node at (0,0) {\textbf{H}};
        \node at (1.2,0) {T};
        \node at (2.4,0) {\textbf{H}};
        \node at (7,0) {\textbf{two} successes (two heads showing)};
    \end{tikzpicture}
\end{center}

If $X$ represents the number of heads shown then it is a *discrete random variable* with outcomes $\{\text{0},\text{1},\text{2},\text{3}\}$.

\begin{centering}
\tcbset{width=13.5cm}
\begin{tcolorbox}[adjusted title=The Binomial Distribution:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\begin{itemize}
    \item Notated $X\sim \text{B}(n,p)$, defined by the two parameters $n$ and $p$.
    \item $X$ represents the \textbf{number of successes} in a \textbf{fixed number of trials}, $n$, and takes integer values $\{\text{0},\text{1},\text{2},\dots,n\}$.
    \item Each trial has only \textbf{two possible outcomes}: success or failure.
    \item Each trial is independent, with a \textbf{constant probability of success}, $p$.
\end{itemize}
\end{tcolorbox}
\end{centering}

For the coin tosses above (assuming the coin is fair):

\begin{itemize}[itemsep=0.5pt]
    \item There are a fixed number of trials ($n=\text{3}$).
    \item Each trial results in one of two outcomes: success (heads) or failure (tails).
    \item The outcome of each trial is independent (since one coin toss does not affect another).
    \item The probability of success (heads) for each trial is constant ($p=\text{0.5}$).
    \item The number of successes (heads) is being counted.
\end{itemize}

If $X$ is the number of heads obtained from three coin tosses, then $X$ is *binomially distributed* with $X\sim \text{B}(\text{3},\text{0.5})$.

[]{#ex72q}

#### [Exercise 7.2](#ex72a) {-}

For each, if $X$ is a binomially distributed random variable then state its distribution, such as $X\sim \text{B}\left(\text{8},\frac{\text{2}}{\text{3}}\right)$. Otherwise, explain clearly which condition(s) for a binomial distribution are not satisfied.

\begin{enumerate}
    \item A student spends one minute rolling a die. Let $X$ represent the number of times the die showed a six.
    \item A student rolls a die 20 times. Let $X$ represent the number of times the die showed a six.
    \item A bag contains 30 red counters and 30 blue counters. A student selects a counter from the bag at random, notes the colour, then \textbf{replaces it} into the bag. In total, they do this 12 times. Let random variable $X$ represent the number of times that the counter selected is red.
    \item A bag contains 30 red counters and 30 blue counters. A student selects a counter from the bag at random, notes the colour, then \textbf{does not replace it} into the bag. In total, they do this 12 times. Let random variable $X$ represent the number of times that the counter selected is red.
    \item Bob takes twelve observations from a $\text{U}(\text{10})$ distribution. Each time the outcome is at least 8, he writes down the value observed. Let $X$ represent the values he writes down.
\end{enumerate}

\pagebreak

## The Binomial Probability Function

Unlike the discrete uniform distribution, the binomial distribution has a probability function that is less obvious. It is therefore useful to understand where the formula comes from.

Consider a spinning wheel that lands on a shaded sector with probability $\frac{\text{2}}{\text{5}}$, or 0.4. Let random variable $X$ represent the number of times the wheel will land on the shaded sector in 6 trials, with possible values from 0 to 6. Here $X$ is *binomially distributed*, with $n=\text{6}$ (number of trials) and $p=\text{0.4}$ (probability of success), or: $X\sim \text{B}(\text{6},\text{0.4})$

\vspace{-0.5cm}
\begin{figure}[H]
  \centering
\captionsetup[figure]{labelformat=empty}%
\begin{minipage}{.4\textwidth}

\begin{tikzpicture}[scale=0.7]
\fill[black!25] (0,0) -- (50:2.5) arc (50:122:2.5) -- (0,0);
\fill[black!25] (0,0) -- (122:2.5) arc (122:194:2.5) -- (0,0);
\draw[thick] (0,0) circle (2.5)
      (50:2.5) -- (0,0)
      (122.13:2.5) -- (0,0)
      (194.13:2.5) -- (0,0)
      (266.13:2.5) -- (0,0)
      (338.13:2.5) -- (0,0);
\fill[black] (0,0) circle (0.15);
\draw[-stealth, line width = 1mm] (0,0) -- (0,2); 
\end{tikzpicture}

\end{minipage}%
  \centering
\begin{minipage}{.1\textwidth}
  \centering
\end{minipage}%
  \centering
\begin{minipage}{.5\textwidth}
  \centering
\begin{tikzpicture}[scale=1]
\pgfplotsset{
    standard/.style={
    axis line style = thick,
    trig format=rad,
    enlargelimits,
    axis x line=middle,
    axis y line=middle,
    every axis x label/.style={at={(current axis.right of origin)},anchor=north west},
    every axis y label/.style={at={(current axis.above origin)},anchor=south east}
    }
}
    \begin{axis}[standard,x label style={at={(current axis.right of origin)},anchor=west},y label style={at={(current axis.above origin)},anchor=south}, height = 5cm, width = 7.5cm, ybar,bar width=10pt, xmin=1,xmax=9,ymin=0,ymax=0.4, xtick={2,3,4,5,6,7,8},xticklabels={$\text{0}$,$\text{1}$,$\text{2}$,$\text{3}$,$\text{4}$,$\text{5}$,$\text{6}$},
    ytick={0,0.1,0.2,0.3},
    yticklabels={$\text{0}$,$\text{0.1}$,$\text{0.2}$,$\text{0.3}$},xlabel=$x$,ylabel=probability]
        \addplot[fill=black!25, draw=black] coordinates {
    (2,0.047)
    (3,0.187) 
    (4,0.311) 
    (5,0.276)
    (6,0.138)
    (7,0.037)
    (8,0.004)
};
    \end{axis}
    \node at (3,-1) {Number of successes ($X$)};
\end{tikzpicture}
\end{minipage}
\end{figure}

\vspace{-0.5cm}

One way of obtaining *exactly two successes* is for the first two spins to be successes and the remaining four to be failures. Since each trial is independent:

$$\text{P}(\text{success, success, fail, fail, fail, fail})=\text{0.4}\times\text{0.4}\times\text{0.6}\times\text{0.6}\times\text{0.6}\times\text{0.6}=\text{0.4}^\text{2}\times\text{0.6}^\text{4}=\text{0.0207}$$

However, this is only one of many possible arrangements that contain exactly two successes. For example, the successes could occur on spins 1 and 3, spins 2 and 5, and so on. Since each arrangement contains two successes and four failures, each has probability 0.0207. The number of ways of choosing the $x$ trials on which success occurs from the $n$ trials is given by the binomial coefficient, ${}^{n}\text{C}_{x}$. For 6 trials with exactly 2 successes, the number of possible arrangements is ${}^{\text{6}}\text{C}_{\text{2}}$.

$$\text{P}(X=\text{2})={}^{\text{6}}\text{C}_{\text{2}}\times\text{0.4}^\text{2}\times\text{0.6}^\text{4}=\text{0.3110}$$

The same reasoning applies generally. To obtain exactly $x$ successes from $n$ independent trials, there are ${}^{n}\text{C}_{x}$ possible arrangements of the successes, each with probability $p^x\times (\text{1}-p)^{n-x}$. The probability function for the binomial distribution $X\sim\text{B}(n,p)$ is given on **page 4** of the Data Booklet as:

\[\text{P}(X=x)={}^{n}\text{C}_{x}\times p^x\times (\text{1}-p)^{n-x}\]

[]{#ex73q}

#### [Exercise 7.3](#ex73a) {-}

\begin{enumerate}
    \item Given that $X\sim \text{B}(\text{10},\text{0.25})$, calculate $\text{P}(X=\text{3})$.
    \item Given that $X\sim \text{B}(\text{8},\text{0.6})$, calculate $\text{P}(X=\text{5})$.
    \item Given that $Y\sim \text{B}(\text{13},\text{0.4})$, calculate $\text{P}(Y\leqslant\text{2})$. (\textit{Hint: use} $\text{P}(Y=\text{0})$, $\text{P}(Y=\text{1})$ \textit{and} $\text{P}(Y=\text{2})$).
    \item 5\% of bluebells have white flowers. The remainder have blue flowers. Determine the probability that a random sample of twelve bluebell plants includes \textbf{none} with white flowers.
    \item In Bob's form class of 20 pupils, their form teacher assigns each pupil a number from 1 to 20 using the order listed on the register and, each morning, uses a random number generator to select which pupil should be responsible for read out notices. Calculate the probability that Bob is selected \textbf{at least once} in one school week.
\end{enumerate}

\pagebreak

## The Binomial Distribution using Cumulative Probability Tables

In practice, it will seldom be necessary to calculate binomial probabilities using the formula. Graphical calculators can be used to calculate both *individual* ($\text{P}(X=x)$) and *cumulative* ($\text{P}(X\leqslant x)$) probabilities. On **page 7**, the Data Booklet provides **cumulative probability tables**, giving **"less than or equal to"** probabilities.

It is therefore important to be able to write any given probability that uses an inequality in terms of a *less than or equal to* probability.

Consider discrete random variable $X$ taking values $x=\{\text{0},\text{1},\text{2},\text{3},\text{4},\text{5},\text{6}\}$:

\vspace{-1cm}
\begin{center}
\begin{align*}
\text{P}(X<\text{5})=&\text{P}(X\leqslant \text{4}) & & \color{black!25}\{\color{black}\text{0},\text{1},\text{2},\text{3},\text{4}\color{black!25},\text{5},\text{6}\}\\
\text{P}(X>\text{5})=&\text{1}-\text{P}(X\leqslant \text{5}) & & \color{black!25}\{\text{0},\text{1},\text{2},\text{3},\text{4},\text{5},\color{black}\text{6}\color{black!25}\}\\
\text{P}(X=\text{5})=&\text{P}(X\leqslant \text{5})-\text{P}(X\leqslant \text{4}) & & \color{black!25}\{\text{0},\text{1},\text{2},\text{3},\text{4},\color{black}\text{5}\color{black!25}\color{black!25},\text{6}\}\\
\text{P}(\text{1}<X<\text{5})=&\text{P}(X\leqslant \text{4}) - \text{P}(X\leqslant \text{1}) & & \color{black!25}\{\text{0},\text{1},\color{black}\text{2},\text{3},\text{4}\color{black!25},\text{5},\text{6}\}
\end{align*}
\end{center}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} It is estimated that around 10\% of people are left-handed. Taking this percentage to be accurate, calculate the probability that, in a random sample of 12 people, at least two of them will be left-handed.

\tcblower
\textbf{Solution:} \textit{(Define a random variable, in context, and define the problem in probability terms.)}\\

Let random variable $X$ represent the number of left-handed people out of the sample of 12.\\[1em]
$p=\text{0.1}$ and $n=\text{12}$\\[1em]
$X\sim \text{B}(\text{12},\text{0.1})$\\[1em]
$\text{P}(X\geqslant \text{2})=\text{1}-\text{P}(X\leqslant \text{1})=\text{1}-\text{0.6590}=\text{0.3410}$

\end{tcolorbox}

[]{#ex74q}

#### [Exercise 7.4](#ex74a) {-}

\begin{enumerate}
    \item Given that $X\sim \text{B}(\text{10},\text{0.3})$, calculate:
    \begin{enumerate}
        \begin{multicols}{5}
        \item $\text{P}(X\leqslant\text{6})$
        \item $\text{P}(X=\text{6})$
        \item $\text{P}(X<\text{6})$
        \item $\text{P}(X>\text{6})$
        \item $\text{P}(X\geqslant\text{6})$
        \end{multicols}
    \end{enumerate}
    \item Given that $X\sim \text{B}(\text{6},\text{0.15})$, calculate:
    \begin{enumerate}
        \begin{multicols}{3}
        \item $\text{P}(X\leqslant\text{2})$
        \item $\text{P}(X\geqslant\text{2})$
        \item $\text{P}(1\leqslant X<\text{3})$
        \end{multicols}
    \end{enumerate}
    \item Given that $X\sim \text{B}(\text{14},\text{0.45})$, calculate:
    \begin{enumerate}
        \begin{multicols}{3}
        \item $\text{P}(X<\text{8})$
        \item $\text{P}(X>\text{12})$
        \item $\text{P}(\text{3}<X\leqslant\text{6})$
        \end{multicols}
    \end{enumerate}
    \item Given that $X\sim \text{B}(\text{8},\text{0.8})$, calculate:
    \begin{enumerate}
        \begin{multicols}{3}
        \item $\text{P}(X=\text{5})$
        \item $\text{P}(X\geqslant\text{7})$
        \item $\text{P}(\text{3}<X<\text{6})$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## The Mean and Variance of the Binomial Distribution

The Data Booklet gives the formulae for the *mean* and *variance* of the binomial distribution on **page 4**.

Given random variable $X\sim \text{B}(n,p)$:

$$\text{E}(X)=np \qquad \text{and} \qquad \text{V}(X)=npq$$

Where $q=\text{1}-p$, representing the *probability of failure*.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} A multiple choice quiz is comprised of eight questions, each with four possible choices. Let random variable $X$ represent the number of correct answers obtained out of eight from a student guessing completely at random. Calculate the mean and variance of $X$.

\tcblower
\textbf{Solution:}

Since the student is guessing randomly, the probability of a correct answer is $p=\tfrac{\text{1}}{\text{4}}$.

$X\sim \text{B}(\text{8},\text{0.25})$\\[1em]
$\text{E}(X)=np=\text{8}\times \text{0.25}=\text{2}$\\[1em]
$\text{V}(X)=npq=\text{8}\times \text{0.25} \times \text{0.75}=\text{1.5}$

\end{tcolorbox}

[]{#ex75q}

#### [Exercise 7.5](#ex75a) {-}

\begin{enumerate}
    \item Calculate the mean and variance for each random variable:
    \begin{enumerate}
    \begin{multicols}{4}
        \item $X\sim \text{B}(\text{4},\text{0.2})$
        \item $Y\sim \text{B}(\text{6},\frac{\text{1}}{\text{3}})$
        \item $X\sim \text{B}(\text{4},\text{0.1})$
        \item $Y\sim \text{B}(\text{30},\text{0.4})$
    \end{multicols}
    \end{enumerate}
    \item An octahedral die numbered 1 to 8 is rolled ten times. Let the random variable $S$ represent the number of times the die shows a square number from the ten rolls.
    \begin{enumerate}
        \item State the distribution of $S$.
        \item Calculate $\text{E}(S)$ and $\text{V}(S)$.
        \item Determine $\text{P}(S>\text{5})$.
    \end{enumerate}
    \item Given that $X\sim \text{B}(\text{6},p)$ such that $\text{E}(X)=\text{1.2}$:
    \begin{enumerate}
        \item Determine the value of $p$.
        \item Calculate $\text{SD}(X)$.
    \end{enumerate}
    \item Given that $Y\sim \text{B}(\text{12},p)$ such that $\text{V}(Y)=\frac{\text{8}}{\text{3}}$ and $p>\text{0.5}$:
    \begin{enumerate}
        \item Determine the value of $p$.
        \item Calculate $\text{E}(Y)$.
    \end{enumerate}
    \item Given that $X\sim \text{B}(n,p)$ such that $X$ has mean and variance of 16 and 3.2 respectively:
    \begin{enumerate}
        \item Determine the values of $n$ and $p$.
        \item Calculate $\text{P}(\text{5}<X<\text{10})$.
    \end{enumerate}
\end{enumerate}

\pagebreak

## The Poisson Distribution

Consider a mobile network's customer support department looking at how many call agents to have on duty at any one time. The mean rate of calls may be well known, such as 2.5 per hour. However, in any one hour there may be 4 calls, 10 calls, no calls at all, and so on. Let the random variable $X$ represent the number of calls in any particular hour. If the conditions for a Poisson model are satisfied, then $X$ follows a **Poisson distribution** with mean rate $\lambda=\text{2.5}$.

\begin{centering}
\tcbset{width=15.5cm}
\begin{tcolorbox}[adjusted title=The Poisson Distribution:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\begin{itemize}
    \item Notated $X\sim \text{Po}(\lambda)$, defined by one parameter $\lambda$ \textit{("lambda")}.
    \item $X$ represents the \textbf{number of events occurring} in a set amount of time or space, with events occuring randomly throughout the interval.
    \item $\lambda$ represents the \textbf{constant mean rate} of events per unit of time or space.
    \item Each event must be \textbf{independent} and \textbf{occur singly}.
\end{itemize}
\end{tcolorbox}
\end{centering}

Assume that the mean rate of 2.5 phone calls per hour is *constant* across the opening hours of the customer support department, and that there is no major network-wide event causing calls to become *not independent* of each other. The Poisson distribution can then be used to calculate, for example, the probability that there are exactly 4 calls in any one hour. Note that the graph below is truncated, and the Poisson distribution has non-zero probabilities for any non-negative integer $\{\text{0},\text{1},\text{2},\text{3},\dots\}$.

\begin{center}
\begin{tikzpicture}
\pgfplotsset{
    standard/.style={
    axis line style = thick,
    trig format=rad,
    enlargelimits,
    axis x line=middle,
    axis y line=middle,
    every axis x label/.style={at={(current axis.right of origin)},anchor=north west},
    every axis y label/.style={at={(current axis.above origin)},anchor=south east}
    }
}
    \begin{axis}[standard,x label style={at={(current axis.right of origin)},anchor=west},y label style={at={(current axis.above origin)},anchor=south}, height = 5cm, width = 7cm, ybar,bar width=10pt, xmin=1,xmax=12,ymin=0,ymax=0.35, xtick={2,3,4,5,6,7,8,9,10,11},xticklabels={0,1,2,3,4,5,6,7,8,9},ytick={0,0.1,0.2,0.3},
    yticklabels={0,0.1,0.2,0.3},
    xlabel=$x$,ylabel=probability]
        \addplot[fill=black!25, draw=black] coordinates {
    (2,0.0821)
    (3,0.2502)
    (4,0.2565) 
    (5,0.2138)
    (6,0.1336)
    (7,0.0668)
    (8,0.0278)
    (9,0.0099)
    (10,0.0031)
    (11,0.0009)
};
    \end{axis}
    \draw[stealth-stealth] (7,3.5) -- (11,3.5);
    \node[fill=white] at (9,3.5) {one hour, $\lambda=\text{2.5}$};
    \draw (7,2) rectangle (11,2.8);
    \node[right] at (11,2.4) {3 calls in one hour};
    \draw (7,1) rectangle (11,1.8);
    \node[right] at (11,1.4) {5 calls in one hour};
    \draw (7,0) rectangle (11,0.8);
    \node[right] at (11,0.4) {0 calls in one hour};
    \draw[fill] (7.9,2.4) circle (0.05);
    \draw[fill] (8.4,2.4) circle (0.05);
    \draw[fill] (10.3,2.4) circle (0.05);
    \draw[fill] (7.5,1.4) circle (0.05);
    \draw[fill] (8.8,1.4) circle (0.05);
    \draw[fill] (9,1.4) circle (0.05);
    \draw[fill] (9.6,1.4) circle (0.05);
    \draw[fill] (10.7,1.4) circle (0.05);
\end{tikzpicture}
\end{center}

As with the binomial distribution, individual Poisson probabilities can be calculated using its its *probability function* (**pf**), provided on **page 4** of the Data Booklet. The derivation of this formula relies on mathematics beyond the scope of this course.

Given random variable $X\sim \text{Po}(\lambda)$:

\vspace{-0.4cm}

$$\text{P}(X=x)=\frac{e^{-\lambda} \times \lambda^x}{x!}$$

For example $\text{P}(X=\text{4})$ in the probability distribution above (where $\lambda=\text{2.5}$) can be calculated as:

$$\text{P}(X=\text{4})=\frac{e^{-\text{2.5}} \times \text{2.5}^\text{4}}{\text{4}!}=\text{0.1336}$$

\pagebreak

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} During a spell of rain, drops of rain fall on a lawn at a constant mean rate of 6 drops per square metre per second. Calculate the probability that exactly 10 drops fall in one square metre of the lawn in a second.

\tcblower
\textbf{Solution:} \textit{(Define a random variable, in context, and define the problem in probability terms.)}\\

Let random variable $X$ represent the number of drops of rain.\\[1em]

$X\sim \text{Po}(\text{6})$

\vspace{-0.5cm}

$$\text{P}(X=\text{10})=\frac{e^{-\text{6}} \times \text{6}^{\text{10}}}{\text{10}!}=\text{0.0413}$$

\end{tcolorbox}

As with the binomial distribution, in general it is much faster to use the cumulative probability tables from **page 10** of the Data Booklet, or a graphical calculator, to calculate Poisson probabilities.

[]{#ex76q}

#### [Exercise 7.6](#ex76a) {-}

\begin{enumerate}
    \item Given random variable $X$ such that $X\sim \text{Po}(\text{2.5})$, use the formula to calculate:
    \begin{multicols}{4}
    \begin{enumerate}
        \item $\text{P}(X=\text{4})$.
        \item $\text{P}(X=\text{0})$.
        \item $\text{P}(X<\text{2})$.
        \item $\text{P}(X\geqslant\text{2})$.
    \end{enumerate}
    \end{multicols}
    \item Let random variable $X$ represent the number of goals in a game of Sunday League football, known to follow a Poisson distribution with a mean of 4 goals.
    \begin{enumerate}
        \item State the distribution of $X$.
        \item Use the formula to calculate the probability that a game finishes without any goals being scored.
    \end{enumerate}
    \item The random variable $X$ follows a Poisson distribution with mean 6. Use the tables to calculate:
    \begin{enumerate}
    \begin{multicols}{4}
        \item $\text{P}(X<\text{4})$.
        \item $\text{P}(X>\text{5})$.
        \item $\text{P}(X\leqslant\text{2})$.
        \item $\text{P}(X\geqslant\text{7})$.
    \end{multicols}
    \end{enumerate}
    \item The random variable $Y$ follows a Poisson distribution with mean 1.5. Use the tables to calculate:
    \begin{enumerate}
    \begin{multicols}{4}
        \item $\text{P}(Y<\text{1})$.
        \item $\text{P}(\text{3}<Y<\text{6})$.
        \item $\text{P}(\text{1}\leqslant Y\leqslant \text{6})$.
        \item $\text{P}(Y\geqslant\text{3})$.
    \end{multicols}
    \end{enumerate}
    \item Whilst watching a section of the night sky, the number of visible shooting stars is known to follow a Poisson distribution with a mean rate of one per hour. Let random variable $X$ represent the number of shooting stars seen in an hour.
    \begin{enumerate}
        \item State the distribution of $X$.
        \item Calculate the probability of more than three shooting stars being seen in any given hour.
    \end{enumerate}
\end{enumerate}

\pagebreak

## Combining Poisson Random Variables

The mean and variance of a Poisson distribution are stated on **page 4** of the Data Booklet. Given $X\sim \text{Po}(\lambda)$:

$$\text{E}(X)=\text{V}(X)=\lambda \qquad \text{and} \qquad \text{SD}(X)=\sqrt{\lambda}$$

A key feature of the Poisson distribution is that the mean and variance are equal. 
This can help to identify whether a Poisson model is appropriate when analysing data.

Given two **independent** random variables $X$ and $Y$ such that $X\sim \text{Po}(\lambda_X)$ and $Y\sim \text{Po}(\lambda_Y)$, the *sum* of $X$ and $Y$ is also a Poisson random variable, for which $\lambda=\lambda_X+\lambda_Y$.

\begin{center}
\begin{tikzpicture}
    \draw [decorate,decoration={brace,amplitude=5pt,raise=1ex}]
  (0.1,0.8) -- (3.9,0.8) node[midway,above,yshift=0.3cm]{$X\sim \text{Po}\left(\lambda_{X}\right)$};
  \draw [decorate,decoration={brace,amplitude=5pt,raise=1ex}]
  (4.1,0.8) -- (9.9,0.8) node[midway,above,yshift=0.3cm]{$Y\sim \text{Po}\left(\lambda_{Y}\right)$};
    \draw (0,0) rectangle (10,0.8);
    \draw (4,0) -- (4,0.8);
    \draw [decorate,decoration={brace,mirror,amplitude=5pt,raise=1ex}]
  (0.1,0) -- (9.9,0) node[midway,below,yshift=-0.3cm]{$X+Y\sim \text{Po}\left(\lambda_{X}+\lambda_{Y}\right)$};
  \fill (0.8,0.4) circle (0.05);
  \fill (1.2,0.4) circle (0.05);
  \fill (3.5,0.4) circle (0.05);
  \fill (5.1,0.4) circle (0.05);
  \fill (5.8,0.4) circle (0.05);
  \fill (6.8,0.4) circle (0.05);
  \fill (7.3,0.4) circle (0.05);
  \fill (9.0,0.4) circle (0.05);
  \node[left] at (0,0.4) {events};
\end{tikzpicture}
\end{center}

The same result can be used to extend, or shorten, the time period of interest for a Poisson distribution, provided there is a *constant mean rate* throughout the entire time period. For example, consider a call centre for which the number of calls per hour, $X$, can be modelled using $X\sim \text{Po}(\text{3})$.

For a five-hour shift at the call centre, the number of calls may be modelled as $Y\sim \text{Po}(\text{15})$ since $\lambda = \text{3} \times \text{5}=\text{15}$.

\begin{center}
\begin{tikzpicture}
    \foreach \x in {1,2,3,4,5}{
    \draw [decorate,decoration={brace,amplitude=5pt,raise=1ex}]
  (3*\x-3+0.1,0.8) -- (3*\x-3+2.8,0.8) node[midway,above,yshift=0.3cm]{$X_\x \sim \text{Po}\left(\text{3}\right)$};
    }
    \draw (0,0) rectangle (15,0.8);
    \foreach \x in {1,2,...,5}{
    \draw (3*\x,0) -- (3*\x,0.8);
    }
    \draw [decorate,decoration={brace,mirror,amplitude=5pt,raise=1ex}]
  (0.1,0) -- (14.9,0) node[midway,below,yshift=-0.3cm]{$Y\sim \text{Po} \left(\text{15}\right)$};
  \fill (1.3,0.4) circle (0.05);
  \fill (1.7,0.4) circle (0.05);
  \fill (3.3,0.4) circle (0.05);
  \fill (4.2,0.4) circle (0.05);
  \fill (5.5,0.4) circle (0.05);
  \fill (5.7,0.4) circle (0.05);
  \fill (7.3,0.4) circle (0.05);
  \fill (8.3,0.4) circle (0.05);
  \fill (8.6,0.4) circle (0.05);
  \fill (12.6,0.4) circle (0.05);
  \fill (13.4,0.4) circle (0.05);
  \fill (14.3,0.4) circle (0.05);
  \node[left] at (0,0.4) {events};
\end{tikzpicture}
\end{center}

This assumes that the number of calls received in each time period is independent.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Betty has observed that the number of work emails she receives on weekdays between 10am and 11am follows a Poisson distribution with a mean rate of 7 emails. The number of personal emails she receives in this time is also Poisson distributed with a mean rate of 3 emails. Calculate the probability that she receives fewer than 8 emails in total on a weekday between 10am and 11am. 

\tcblower
\textbf{Solution:}

Let random variable $X$ represent the number of work emails, and $Y$ the number of personal emails.\\

$\lambda_X=\text{7}$ and $X\sim \text{Po}(\text{7}$\\

$\lambda_Y=\text{3}$ and $Y\sim \text{Po}(\text{3})$\\

Let random variable $T$ represent the total number of emails in an hour:\\

$\lambda_X+\lambda_Y=\text{7}+\text{3}=\text{10}$, so $T\sim \text{Po}(\text{10})$\\

$\text{P}(T<\text{8})=\text{P}(T\leqslant \text{7})=\text{0.2202}$

\end{tcolorbox}

So there is a roughly 22\% probability that Betty receives fewer than 8 emails in total between 10am and 11am, assuming that each event (an email arriving) is independent. This would not be the case if some emails she receives are duplicated between her work and email accounts, such as subscriptions to services emailing all the addresses a customer has registered with them.

\pagebreak

[]{#ex77q}

#### [Exercise 7.7](#ex77a) {-}

\begin{enumerate}
    \item Given independent random variables $X\sim \text{Po}(\text{1.6})$ and $Y\sim \text{Po}(\text{0.4})$, calculate $\text{P}(X+Y\leqslant\text{4})$.
    \item Given $F\sim \text{Po}(\text{3.3})$ and $G\sim \text{Po}(\text{1.2})$, with $F$ and $G$ independent, calculate $\text{P}(F+G\geqslant\text{2})$.
    \item The number of wickets taken in a morning session of country cricket in a league in Scotland follows a Poisson distribution with a mean of 3.5. In an afternoon session, the mean is 2.5. 
    \begin{enumerate}
        \item Calculate the probability that fewer than 4 wickets are taken in a \textbf{morning} session.
        \item Find the probability that exactly 8 wickets are taken in a full day, comprising of a morning session and an afternoon session.
        \item State an assumption required for the calculation in part (b).
    \end{enumerate}
    \item For a restaurant's Glasgow branch, the number of bottles of champagne sold on a Saturday night follows a Poisson distribution with a mean rate of 3 per night. The number sold for their Edinburgh branch is Poisson distributed with a mean of 5 per night. Stating an assumption required, calculate the probability at least 10 but fewer than 15 bottles of champagne are sold on a Saturday night between the two branches.
    \item Shooting stars can be seen in a section of night sky at a mean rate of 1 per hour, and the number visible in an hour is Poisson distributed. Calculate the probability of watching the night sky for two hours and not seeing a single shooting star.
    \item A city is experiencing problems with the number of pieces of chewing gum stuck to pavements. A worker from the council's environmental health department notes that in the city's main pedestrian square, the mean number of pieces of chewing gum per square paving stone was 1.5.\\[0.5em]
    It may be assumed that the number of pieces on a paving stone, $X$, follows a Poisson distribution. 
    \begin{enumerate}
        \item State the distribution of $X$.
        \item Use the Data Booklet to calculate the probability that a randomly selected paving stone contains at least one piece of chewing gum.
    \end{enumerate}
    The worker counts the number of pieces of chewing gum on a grid of 18 paving stones. The diagram below is for illustration, and does not show what the actual number of pieces the worker observed.
    \begin{center}
        \begin{tikzpicture}[scale=0.8]
            \draw[step=2] (0,0) grid (12,6);
            \draw[fill=black!15] (1.81610648809231,2.28512724598794) circle (0.06);
\draw[fill=black!15] (0.983776184910955,2.31330584603028) circle (0.06);
\draw[fill=black!15] (7.9119049617031,4.31463598771149) circle (0.06);
\draw[fill=black!15] (10.888537125237,5.24203498769731) circle (0.06);
\draw[fill=black!15] (1.78466415599035,4.00912775153914) circle (0.06);
\draw[fill=black!15] (5.01452369767634,2.29004709740606) circle (0.06);
\draw[fill=black!15] (9.02451508014978,2.0744740268897) circle (0.06);
\draw[fill=black!15] (8.7384299566202,0.625915658835329) circle (0.06);
\draw[fill=black!15] (9.23035948349878,1.77366076894073) circle (0.06);
\draw[fill=black!15] (5.22086077191008,1.77030038983797) circle (0.06);
\draw[fill=black!15] (7.2740947892201,1.65874930627853) circle (0.06);
\draw[fill=black!15] (7.45686902798285,3.46468668704474) circle (0.06);
\draw[fill=black!15] (6.37571126206989,4.13929773281825) circle (0.06);
\draw[fill=black!15] (1.36268069915271,0.345894547977273) circle (0.06);
\draw[fill=black!15] (3.73021957614899,3.09439364798087) circle (0.06);
\draw[fill=black!15] (11.5565405342891,5.17953756090361) circle (0.06);
\draw[fill=black!15] (10.3074812215872,0.229944104267416) circle (0.06);
\draw[fill=black!15] (7.13496881340819,1.92962571154649) circle (0.06);
\draw[fill=black!15] (8.22060440296903,3.4442678973737) circle (0.06);
\draw[fill=black!15] (0.688646604553531,4.84206581133751) circle (0.06);
\draw[fill=black!15] (3.68061164611793,0.403999309101427) circle (0.06);
\draw[fill=black!15] (11.7628004012925,2.43395299514079) circle (0.06);
        \end{tikzpicture}
    \end{center}
    \begin{enumerate}[resume]
        \item Calculate the probability that a selection of 18 paving stones contains exactly 30 pieces of chewing gum in total, stating an assumption required.
    \end{enumerate}
    \item A data storage company using a large number of hard drives has seen that the number of drives failing per day follows a Poisson distribution with a constant mean rate of 1.5 per day. The company has staff monitoring the servers that contain the drives 24 hours per day, working in three separate 8-hour shifts each day. Calculate the probability of more than 2 drives failing during one shift.
\end{enumerate}

\pagebreak

[]{#re7q}

## [Review Exercise](#re7a) {-}

\begin {enumerate}
    \item Given that $X\sim \text{U}(\text{8})$, calculate:
    \begin{enumerate}
        \item $\text{P}(X<\text{6})$.
        \item The mean and variance of $X$.
    \end{enumerate}
    \item Given that $X\sim \text{B}(\text{12},\text{0.35})$:
    \begin{enumerate}
        \item Find $\text{P}(X=\text{3})$.
        \item Find $\text{P}(\text{5}<X<\text{9})$.
    \end{enumerate}
    \item $X$ and $Y$ are independent random variables such that $X\sim \text{Po}(\text{1.7})$ and $Y\sim \text{Po}(\text{6.8})$, find:
    \begin{enumerate}
        \item $\text{P}(X+Y=\text{7})$.
        \item $\text{P}(X+Y\geqslant\text{9})$.
    \end{enumerate}
    \item The random variable $X$ follows a Poisson distribution with standard deviation 2. Find $\text{P}(X\leqslant\text{3})$.
    \item A gardener plants seeds in batches of 20 and knows that only 85\% of seeds actually germinate.
    \begin{enumerate}
        \item Find the chance of more than 15 seeds in the batch germinating.
        \item Find the mean and standard deviation of the number of seeds that germinate.
        \item State one assumption required for the valid use of the probability distribution used.
    \end{enumerate}
    \item A restaurant has two food mixers, A and B. The number of times per week that mixer A breaks down has a Poisson distribution with mean 0.4, while independently the number of times that mixer B breaks down has a Poisson distribution with mean 0.1. Calculate the probability that in the next three weeks:
    \begin{enumerate}
        \item Mixer A will not break down at all.
        \item There will be a total of 2 breakdowns.
    \end{enumerate}
    \item A restaurant menu contains 20 dishes, consisting of starters, main courses and desserts. The table below breaks down the number of dishes for each course and by whether or not they are vegetarian:
    \begin{center}
    \begin{tabular}{c|ccc}
         & Starter & Main & Dessert\\
      \hline
        Vegetarian & 2 & 2 & 6\\
      \hline
        Not Vegetarian & 4 & 6 & 0\\
    \end{tabular}
    \end{center}
    Each week, the owner chooses one dish at random to check that the quality is up to standard. Each dish is equally likely to be selected, and a dish being chosen one week does not change the probability that it will be chosen in the following weeks.
    \begin{enumerate}
        \item[(a) ] Given that a dish selected to be checked is vegetarian, state the probability that it is a main course.
    \end{enumerate}
    Let random variable $X$ represent the number of the dishes checked over an 8 week period that are desserts.
    \begin{enumerate}
        \item[(b) ] State the distribution of $X$.
        \item[(c) ] Calculate the probability that more than half of the dishes checked in the 8 week period are dessert dishes.
    \end{enumerate}
    \item For each random variable, calculate the probability of the value of an observation being greater than one standard deviation above the mean.
    \begin{enumerate}
        \item $X\sim \text{U}(\text{20})$.
        \item $Y\sim \text{Po}(\text{6})$.
        \item $Q\sim \text{B}(\text{16},\text{0.2})$.
    \end{enumerate}
\end{enumerate}

\pagebreak
