# Control Charts

In any manufacturing process, performance must be monitored to ensure that the products being manufactured are not faulty or that the process remains stable. A common tool used to monitor performance is a *control chart*, in which a series of samples are taken over time, measured and plotted against calculated limits to detect unusual variation.

\begin{center}
\begin{tikzpicture}[scale=0.9]
    \node at (5,3) {\textit{A simplified control chart:}};
    \draw (0,0) -- (12,0);
    \node[left] at (0,0) {$\mu$};
    \draw[dashed] (0,2) -- (12,2);
    \node[left] at (0,2) {Upper Control Limit};
    \draw[dashed] (0,-2) -- (12,-2);
    \node[left] at (0,-2) {Lower Control Limit};
    \coordinate (A) at (1,0.3);
    \coordinate (B) at (2,0.6);
    \coordinate (C) at (3,-0.1);
    \coordinate (D) at (4,-0.3);
    \coordinate (E) at (5,0.4);
    \coordinate (F) at (6,-0.6);
    \coordinate (G) at (7,0.2);
    \coordinate (H) at (8,-0.2);
    \coordinate (I) at (9,-2.3);
    \coordinate (J) at (10,-2.4);
    \coordinate (K) at (11,-2.6);
    \draw[fill=black] (A) circle (2pt);
    \draw[fill=black] (B) circle (2pt);
    \draw[fill=black] (C) circle (2pt);
    \draw[fill=black] (D) circle (2pt);
    \draw[fill=black] (E) circle (2pt);
    \draw[fill=black] (F) circle (2pt);
    \draw[fill=black] (G) circle (2pt);
    \draw[fill=black] (H) circle (2pt);
    \draw[fill=black] (I) circle (2pt);
    \draw[fill=black] (J) circle (2pt);
    \draw[fill=black] (K) circle (2pt);
    \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K);
    \draw[decoration={brace,mirror},decorate]
  (0.7,-3.2) -- (8.3,-3.2);
  \draw[decoration={brace,mirror},decorate]
  (8.7,-3.2) -- (11.3,-3.2);
    \node[below] at (4.5,-3.3) {Process};
    \node[below] at (4.5,-3.8) {\textit{in statistical control}};
    \node[below] at (10,-3.3) {Process};
    \node[below] at (10,-3.8) {\textit{out of control}};
\end{tikzpicture}
\end{center}

Variation naturally occurs as a result of random causes in most processes, referred to as **common cause variation**, and often there is no need for this to be investigated or corrected. This could be, for example, because the variation is within tolerable limits, or the cost of reducing the variation would outweigh the potential benefit of doing so. A process performing in this manner is said to be *in control*.

However, if something occurs within the process that results in variation that is not consistent with the typical random variation of the process, a system, such as a control chart, is used to signal that the process may be *out of control*. The process can then be reviewed and any possible **special cause variation** investigated, such as machine wear and tear, poor raw materials, poorly trained operatives, or an accident or malfunction.

\pagebreak

### The Principle of a Control Chart {-}

The control chart was invented in the 1920s by Walter Shewhart, who was working for a communications company whose engineers wanted to improve the reliability of their telephone transmission systems. His theory was based around the bell-shaped curve of the normal distribution.

The Advanced Higher Statistics course covers two types of control charts:

\begin{itemize}
    \item A Shewhart $x$-bar chart for the sample \textbf{mean}.
    \item A Shewhart $p$-chart for the sample \textbf{proportion}.
\end{itemize}

In either case, random samples from the process are taken at regular intervals and the sample means or sample proportions are plotted onto the control chart. A line on the chart is drawn to indicate the target value for the population mean or population proportion, as well as 1-sigma , 2-sigma and 3-sigma lines either side of the target value where $\sigma$ represents the population standard deviation of the process.

The 3-sigma (3$\sigma$) limits are often referred to as the *upper* and *lower control limits*, with the other limits called *warning lines*. The diagram below indicates the probability that a sample statistic falls within each set of limits, assuming the process is *in control* and certain conditions are met.

\begin{center}
\begin{tikzpicture}[scale=0.9,declare function={gaussy(\x,\y,\z)=1/(\y*sqrt(2*pi))*exp(-((\x-\z)^2)/(2*\y^2));}]
\draw[smooth,domain=-4.8:4.8]  plot ({25*gaussy(\x,1.5,0)+11.2},\x);
    \draw[very thick] (0,0) -- (9,0);
    \node[above right] at (0,0) {$\mathbf{CL}$};
    \node[below right] at (0,0) {Centre Line};
    \draw[very thick, dashed] (0,4.5) -- (9,4.5);
    \node[above right] at (0,4.5) {$\mathbf{UCL}$};
    \node[below right] at (0,4.5) {Upper Control Limit};
    \draw[very thick, dashed] (0,-4.5) -- (9,-4.5);
    \node[above right] at (0,-4.5) {$\mathbf{LCL}$};
    \node[below right] at (0,-4.5) {Lower Control Limit};
    \node[right] at (9,4.5) {$+3\sigma$};
    \node[right] at (9,3) {$+2\sigma$};
    \node[right] at (9,1.5) {$+1\sigma$};
    \node[right] at (9,0) {\textit{mean}};
    \node[right] at (9,-1.5) {$-1\sigma$};
    \node[right] at (9,-3) {$-2\sigma$};
    \node[right] at (9,-4.5) {$-3\sigma$};
    \draw[dash dot] (0,3) -- (9,3);
    \draw[dash dot] (0,1.5) -- (9,1.5);
    \draw[dash dot] (0,-1.5) -- (9,-1.5);
    \draw[dash dot] (0,-3) -- (9,-3);
    \coordinate (A) at (1,0.5);
    \coordinate (B) at (2,1.2);
    \coordinate (C) at (3,0.3);
    \coordinate (D) at (4,-1.7);
    \coordinate (E) at (5,-0.4);
    \coordinate (F) at (6,2.6);
    \coordinate (G) at (7,0.3);
    \coordinate (H) at (8,-0.4);
    \coordinate (I) at (9,0.5);
    \draw[fill=black] (A) circle (3pt);
    \draw[fill=black] (B) circle (3pt);
    \draw[fill=black] (C) circle (3pt);
    \draw[fill=black] (D) circle (3pt);
    \draw[fill=black] (E) circle (3pt);
    \draw[fill=black] (F) circle (3pt);
    \draw[fill=black] (G) circle (3pt);
    \draw[fill=black] (H) circle (3pt);
    \draw[fill=black] (I) circle (3pt);
    \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H)-- (I);
    \draw[very thick] (10.5,0) -- (17.75,0);
    \draw[dash dot] (10.5,1.5) -- (14.75,1.5);
    \draw[dash dot] (10.5,-1.5) -- (14.75,-1.5);
    \draw[dash dot] (10.5,3) -- (11.9,3);
    \draw[dash dot] (10.5,-3) -- (11.9,-3);
    \draw[very thick, dashed] (10.5,4.5) -- (11.1,4.5);
    \draw[very thick, dashed] (10.5,-4.5) -- (11.1,-4.5);
    \draw[decorate, 
	decoration = {brace,
		amplitude=5pt}] (14.95,1.5) --  (14.95,-1.5);
        \draw[white,fill=white] (14.7,-0.7) rectangle (15.35,0.7);
        \node[rotate=270] at (15.05,0) {68.3\%};
    \draw [decorate, 
	decoration = {brace,
		amplitude=6pt}] (11.95,3) --  (11.95,-3);
        \draw[white,fill=white] (11.7,-0.7) rectangle (12.35,0.7);
        \node[rotate=270] at (12.05,0) {95.5\%};
    \draw [decorate, 
	decoration = {brace,
		amplitude=7pt}] (11.1,4.5) --  (11.1,-4.5);
        \draw[white,fill=white] (10.85,-0.7) rectangle (11.5,0.7);
        \node[rotate=270] at (11.2,0) {99.7\%};
\end{tikzpicture}
\end{center}

The Western Electric Company Rules (*WECO Rules*) are commonly used to determine whether a process is *in or out of statistical control*, and are provided on Page 4 of the Data Booklet.

A process may be considered out of statistical control using the WECO Rules when:

\begin{itemize}
  \item \textit{Any} single data point falls outside a 3$\sigma$ limit.
  \item \textit{Two out of three} consecutive points fall beyond the \textit{same }2$\sigma$ limit.
  \item \textit{Four out of five} consecutive points fall beyond the \textit{same }1$\sigma$ limit.
  \item \textit{Eight consecutive} points fall on the \textit{same side of the centre line}.
\end{itemize}

These rules help detect patterns that are unlikely to occur due to random variation alone.

\pagebreak

## Applying the WECO Rules

Each rule must be carefully checked for to determine whether a process is *in statistical control*. If it is *not* in statistical control, it is often necessary to identify the relevant WECO rule and at which point this could be declared. The following examples focus on context-free control charts for the purpose of practising *applying the WECO rules*.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} For the control chart below, determine whether the process is in control. If it is out of control, identify at which sample this could be determined, with justification.

\begin{center}
\begin{tikzpicture}
    \node[text width = 7.35cm] at (12,0) {\textbf{Solution:} The process is out of control, as two out of the three consecutive points (from samples 5 to 7) lie below the lower 2-sigma limit. The process could have been identified as out of control at sample 7.};
    \coordinate (A) at (0.6,0.3);
    \coordinate (B) at (1.2,1);
    \coordinate (C) at (1.8,-0.4);
    \coordinate (D) at (2.4,0.3);
    \coordinate (E) at (3,-1.5);
    \coordinate (F) at (3.6,-0.3);
    \coordinate (G) at (4.2,-1.4);
    \coordinate (H) at (4.8,-0.9);
    \coordinate (I) at (5.4,-0.75);
    \draw[very thick] (0,0) -- (6,0);
    \draw[very thick, dashed] (0,1.8) -- (6,1.8);
    \draw[very thick, dashed] (0,-1.8) -- (6,-1.8);
    \node[right] at (6,1.8) {\small{$+$3$\sigma$}};
    \node[right] at (6,1.2) {\small{$+$2$\sigma$}};
    \node[right] at (6,0.6) {\small{$+$1$\sigma$}};
    \node[right] at (6,0) {\small{\text{mean}}};
    \node[right] at (6,-0.6) {\small{$-$1$\sigma$}};
    \node[right] at (6,-1.2) {\small{$-$2$\sigma$}};
    \node[right] at (6,-1.8) {\small{$-$3$\sigma$}};
    \draw[dash dot] (0,1.2) -- (6,1.2);
    \draw[dash dot] (0,0.6) -- (6,0.6);
    \draw[dash dot] (0,-0.6) -- (6,-0.6);
    \draw[dash dot] (0,-1.2) -- (6,-1.2);
    \draw[fill=black] (A) circle (2pt);
    \draw[fill=black] (B) circle (2pt);
    \draw[fill=black] (C) circle (2pt);
    \draw[fill=black] (D) circle (2pt);
    \draw[fill=black] (E) circle (2pt);
    \draw[fill=black] (F) circle (2pt);
    \draw[fill=black] (G) circle (2pt);
    \draw[fill=black] (H) circle (2pt);
    \draw[fill=black] (I) circle (2pt);
    \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H)-- (I);
    \node[anchor=east] at (0.2,-2.4) {\small{sample}};
    \foreach \x in {1,2,...,9}{
    \node at (0.6*\x,-2.4) {\small{\x}};
    }
\end{tikzpicture}
\end{center}

\end{tcolorbox}

[]{#ex131q}

#### [Exercise 13.1](#ex131a) {-}

*For each control charts below, determine whether the process is in control, with justification.*

\begin{multicols}{2}

\begin{center}
\begin{tikzpicture}
    \node at (-0.6,1.8) {1.};
    \coordinate (A) at (0.6,-0.4);
    \coordinate (B) at (1.2,1);
    \coordinate (C) at (1.8,0.3);
    \coordinate (D) at (2.4,0.9);
    \coordinate (E) at (3,-0.8);
    \coordinate (F) at (3.6,-2);
    \coordinate (G) at (4.2,0.5);
    \coordinate (H) at (4.8,0.9);
    \coordinate (I) at (5.4,-0.3);
    \draw[very thick] (0,0) -- (6,0);
    \draw[very thick, dashed] (0,1.8) -- (6,1.8);
    \draw[very thick, dashed] (0,-1.8) -- (6,-1.8);
    \node[right] at (6,1.8) {\small{$+$3$\sigma$}};
    \node[right] at (6,1.2) {\small{$+$2$\sigma$}};
    \node[right] at (6,0.6) {\small{$+$1$\sigma$}};
    \node[right] at (6,0) {\small{\text{mean}}};
    \node[right] at (6,-0.6) {\small{$-$1$\sigma$}};
    \node[right] at (6,-1.2) {\small{$-$2$\sigma$}};
    \node[right] at (6,-1.8) {\small{$-$3$\sigma$}};
    \draw[dash dot] (0,1.2) -- (6,1.2);
    \draw[dash dot] (0,0.6) -- (6,0.6);
    \draw[dash dot] (0,-0.6) -- (6,-0.6);
    \draw[dash dot] (0,-1.2) -- (6,-1.2);
    \draw[fill=black] (A) circle (2pt);
    \draw[fill=black] (B) circle (2pt);
    \draw[fill=black] (C) circle (2pt);
    \draw[fill=black] (D) circle (2pt);
    \draw[fill=black] (E) circle (2pt);
    \draw[fill=black] (F) circle (2pt);
    \draw[fill=black] (G) circle (2pt);
    \draw[fill=black] (H) circle (2pt);
    \draw[fill=black] (I) circle (2pt);
    \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H)-- (I);
    \node[anchor=east] at (0.2,-2.4) {\small{sample}};
    \foreach \x in {1,2,...,9}{
    \node at (0.6*\x,-2.4) {\small{\x}};
    }
    \draw[white] (-1.5,-2.8) rectangle (7.5,2.5);
\end{tikzpicture}
\end{center}

\begin{center}
\begin{tikzpicture}
    \node at (-0.6,1.8) {3.};
    \coordinate (A) at (0.6,-1);
    \coordinate (B) at (1.2,-0.3);
    \coordinate (C) at (1.8,0.9);
    \coordinate (D) at (2.4,0.8);
    \coordinate (E) at (3,0.2);
    \coordinate (F) at (3.6,-0.4);
    \coordinate (G) at (4.2,0.5);
    \coordinate (H) at (4.8,0.9);
    \coordinate (I) at (5.4,-0.3);
    \draw[very thick] (0,0) -- (6,0);
    \draw[very thick, dashed] (0,1.8) -- (6,1.8);
    \draw[very thick, dashed] (0,-1.8) -- (6,-1.8);
    \node[right] at (6,1.8) {\small{$+$3$\sigma$}};
    \node[right] at (6,1.2) {\small{$+$2$\sigma$}};
    \node[right] at (6,0.6) {\small{$+$1$\sigma$}};
    \node[right] at (6,0) {\small{\text{mean}}};
    \node[right] at (6,-0.6) {\small{$-$1$\sigma$}};
    \node[right] at (6,-1.2) {\small{$-$2$\sigma$}};
    \node[right] at (6,-1.8) {\small{$-$3$\sigma$}};
    \draw[dash dot] (0,1.2) -- (6,1.2);
    \draw[dash dot] (0,0.6) -- (6,0.6);
    \draw[dash dot] (0,-0.6) -- (6,-0.6);
    \draw[dash dot] (0,-1.2) -- (6,-1.2);
    \draw[fill=black] (A) circle (2pt);
    \draw[fill=black] (B) circle (2pt);
    \draw[fill=black] (C) circle (2pt);
    \draw[fill=black] (D) circle (2pt);
    \draw[fill=black] (E) circle (2pt);
    \draw[fill=black] (F) circle (2pt);
    \draw[fill=black] (G) circle (2pt);
    \draw[fill=black] (H) circle (2pt);
    \draw[fill=black] (I) circle (2pt);
    \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H)-- (I);
    \node[anchor=east] at (0.2,-2.4) {\small{sample}};
    \foreach \x in {1,2,...,9}{
    \node at (0.6*\x,-2.4) {\small{\x}};
    }
    \draw[white] (-1.5,-2.8) rectangle (7.5,2.5);
\end{tikzpicture}
\end{center}

\begin{center}
\begin{tikzpicture}
    \node at (-0.6,1.8) {2.};
    \coordinate (A) at (0.6,0.95);
    \coordinate (B) at (1.2,-1.6);
    \coordinate (C) at (1.8,-0.9);
    \coordinate (D) at (2.4,0.85);
    \coordinate (E) at (3,0.75);
    \coordinate (F) at (3.6,0.8);
    \coordinate (G) at (4.2,-0.4);
    \coordinate (H) at (4.8,1.4);
    \coordinate (I) at (5.4,-1);
    \draw[very thick] (0,0) -- (6,0);
    \draw[very thick, dashed] (0,1.8) -- (6,1.8);
    \draw[very thick, dashed] (0,-1.8) -- (6,-1.8);
    \node[right] at (6,1.8) {\small{$+$3$\sigma$}};
    \node[right] at (6,1.2) {\small{$+$2$\sigma$}};
    \node[right] at (6,0.6) {\small{$+$1$\sigma$}};
    \node[right] at (6,0) {\small{\text{mean}}};
    \node[right] at (6,-0.6) {\small{$-$1$\sigma$}};
    \node[right] at (6,-1.2) {\small{$-$2$\sigma$}};
    \node[right] at (6,-1.8) {\small{$-$3$\sigma$}};
    \draw[dash dot] (0,1.2) -- (6,1.2);
    \draw[dash dot] (0,0.6) -- (6,0.6);
    \draw[dash dot] (0,-0.6) -- (6,-0.6);
    \draw[dash dot] (0,-1.2) -- (6,-1.2);
    \draw[fill=black] (A) circle (2pt);
    \draw[fill=black] (B) circle (2pt);
    \draw[fill=black] (C) circle (2pt);
    \draw[fill=black] (D) circle (2pt);
    \draw[fill=black] (E) circle (2pt);
    \draw[fill=black] (F) circle (2pt);
    \draw[fill=black] (G) circle (2pt);
    \draw[fill=black] (H) circle (2pt);
    \draw[fill=black] (I) circle (2pt);
    \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H)-- (I);
    \node[anchor=east] at (0.2,-2.4) {\small{sample}};
    \foreach \x in {1,2,...,9}{
    \node at (0.6*\x,-2.4) {\small{\x}};
    }
    \draw[white] (-1.5,-2.8) rectangle (7.5,2.5);
\end{tikzpicture}
\end{center}

\begin{center}
\begin{tikzpicture}
    \node at (-0.6,1.8) {4.};
    \coordinate (A) at (0.6,-0.9);
    \coordinate (B) at (1.2,1);
    \coordinate (C) at (1.8,0.8);
    \coordinate (D) at (2.4,0.2);
    \coordinate (E) at (3,0.75);
    \coordinate (F) at (3.6,1.6);
    \coordinate (G) at (4.2,0.4);
    \coordinate (H) at (4.8,0.9);
    \coordinate (I) at (5.4,0.25);
    \draw[very thick] (0,0) -- (6,0);
    \draw[very thick, dashed] (0,1.8) -- (6,1.8);
    \draw[very thick, dashed] (0,-1.8) -- (6,-1.8);
    \node[right] at (6,1.8) {\small{$+$3$\sigma$}};
    \node[right] at (6,1.2) {\small{$+$2$\sigma$}};
    \node[right] at (6,0.6) {\small{$+$1$\sigma$}};
    \node[right] at (6,0) {\small{\text{mean}}};
    \node[right] at (6,-0.6) {\small{$-$1$\sigma$}};
    \node[right] at (6,-1.2) {\small{$-$2$\sigma$}};
    \node[right] at (6,-1.8) {\small{$-$3$\sigma$}};
    \draw[dash dot] (0,1.2) -- (6,1.2);
    \draw[dash dot] (0,0.6) -- (6,0.6);
    \draw[dash dot] (0,-0.6) -- (6,-0.6);
    \draw[dash dot] (0,-1.2) -- (6,-1.2);
    \draw[fill=black] (A) circle (2pt);
    \draw[fill=black] (B) circle (2pt);
    \draw[fill=black] (C) circle (2pt);
    \draw[fill=black] (D) circle (2pt);
    \draw[fill=black] (E) circle (2pt);
    \draw[fill=black] (F) circle (2pt);
    \draw[fill=black] (G) circle (2pt);
    \draw[fill=black] (H) circle (2pt);
    \draw[fill=black] (I) circle (2pt);
    \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H)-- (I);
    \node[anchor=east] at (0.2,-2.4) {\small{sample}};
    \foreach \x in {1,2,...,9}{
    \node at (0.6*\x,-2.4) {\small{\x}};
    }
    \draw[white] (-1.5,-2.8) rectangle (7.5,2.5);
\end{tikzpicture}
\end{center}

\end{multicols}

\pagebreak

## Shewhart \textit{x}-bar Charts for the Mean

Suppose that a manufacturing process is working properly and the output of the process is normally distributed, with mean $\mu$ and standard deviation $\sigma$. If samples of size $n$ are taken regularly from the product, and the mean obtained for each sample, then those sample means will themselves also be normally distributed:

\vspace{-0.3cm}

\[\overline{X}\sim \text{N}\left(\mu,\dfrac{\sigma^2}{n}\right)\]

\vspace{-0.2cm}

The standard error of each sample mean obtained is given by $\dfrac{\sigma}{\sqrt{n}}$, and the sigma limits are given by:

\vspace{-0.3cm}

\begin{center}
    \begin{tikzpicture}
        \node at (-5,0) {$1\sigma \text{ limits: }\mu \text{ }\pm \text{ }\dfrac{\sigma}{\sqrt{n}}$};
        \node at (0,0) {$2\sigma \text{ limits: }\mu \text{ }\pm \text{ }2\dfrac{\sigma}{\sqrt{n}}$};
        \node at (5,0) {$3\sigma \text{ limits: }\mu \text{ }\pm \text{ }3\dfrac{\sigma}{\sqrt{n}}$};
        \draw[decorate, 
	decoration = {brace,
		amplitude=7pt}] (1.8,-0.8) --  (-6.8,-0.8);
        \node[below] at (-2.5,-1) {\textit{Warning lines}};
        \draw[decorate, 
	decoration = {brace,
		amplitude=7pt}] (6.8,-0.8) --  (3.2,-0.8);
        \node[below] at (5,-1) {\textit{UCL}\text{ and }\textit{LCL}};
    \end{tikzpicture}
\end{center}

\vspace{-0.5cm}

A control chart is created with horizontal lines indicating the population mean and each of the 6 sigma limits calculated. The sample mean for each of the samples drawn at regular intervals is plotted on the chart, and the *WECO rules* applied to determine if or when the production process is out of control. 

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} A machine fills cans with mean mass 300 grams and standard deviation 5 grams of chopped tomatoes. Every hour a sample of 4 cans is taken, the masses of their contents measured, and the sample mean calculated before being added to an $x$-bar chart. 

\begin{center}
    \begin{tabular}{|c|c|c|c|c|c|c|c|c|}
        \hline
        Sample number & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\
        \hline
        Sample mean & 298 & 293 & 303 & 306 & 301 & 292 & 292 & 302\\
        \hline
    \end{tabular}
\end{center}

\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.8) {sample number};
        \node[rotate=90] at (-1.8,0) {sample mean (g)};
        \node at (6,4) {$x$-bar chart of chopped tomatoes masses};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3);
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0);
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-3) -- (11.9,-3);
        \node[left] at (13.2,3) {UCL};
        \node[left] at (13.2,2) {$+$2$\sigma$};
        \node[left] at (13.2,1) {$+$1$\sigma$};
        \node[left] at (13.2,0) {$\mu$};
        \node[left] at (13.2,-1) {$-$1$\sigma$};
        \node[left] at (13.2,-2) {$-$2$\sigma$};
        \node[left] at (13.2,-3) {LCL};
        \node[right] at (13,3) {$=$ 307.5};
        \node[right] at (13,2) {$=$ 305};
        \node[right] at (13,1) {$=$ 302.5};
        \node[right] at (13,0) {$=$ 300};
        \node[right] at (13,-1) {$=$ 297.5};
        \node[right] at (13,-2) {$=$ 295};
        \node[right] at (13,-3) {$=$ 292.5};
        \foreach \x in {1,2,...,8}{
        \draw (1.5*\x-0.7,-3.5) -- (1.5*\x-0.7,-3.7) node[below] {\x};
        }
        \node[left] at (0,-3.2) {292};
        \node[left] at (0,-2.4) {294};
        \node[left] at (0,-1.6) {296};
        \node[left] at (0,-0.8) {298};
        \node[left] at (0,0) {300};
        \node[left] at (0,0.8) {302};
        \node[left] at (0,1.6) {304};
        \node[left] at (0,2.4) {306};
        \node[left] at (0,3.2) {308};
        \coordinate (A) at (0.8,-0.8);
        \coordinate (B) at (2.3,-2.8);
        \coordinate (C) at (3.8,1.2);
        \coordinate (D) at (5.3,2.4);
        \coordinate (E) at (6.8,0.4);
        \coordinate (F) at (8.3,-3.2);
        \coordinate (G) at (9.8,-3.2);
        \coordinate (H) at (11.3,0.8);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H);
        \end{tikzpicture}
\end{center}

\begin{enumerate}
    \item[(a)] Confirm the 2-sigma limits shown on the control chart.
    \item[(b)] Determine when the process is out of control.
\end{enumerate}

\tcblower
\textbf{Solution:}

\begin{enumerate}
    \item[(a)] $2\sigma$ limits: $\mu \text{ }\pm \text{ } 2\dfrac{\sigma}{\sqrt{n}}=300\text{ }\pm\text{ }2\times\dfrac{5}{\sqrt{4}}=300\text{ }\pm\text{ }5$, so $295$ and $305$.
    \item[(b)] The process is out of statistical control, which can be identified at sample 6 when the sample mean first falls below the lower control limit ($-$3$\sigma$ limit). The process should be stopped and investigated.
\end{enumerate}

\end{tcolorbox}

\pagebreak

[]{#ex132q}

#### [Exercise 13.2](#ex132a) {-}

\begin{enumerate}
    \item Control charts are to be produced for sample means taken to monitor the following processes. If the samples are random, and it can be assumed that the processes can be suitably described by the normal distribution, copy and complete the following tables showing limits for the $x$-bar charts:
    \begin{multicols}{2}
        \begin{enumerate}
            \item Population mean $=$ 80\\
            Population standard deviation $=$ 3\\
            Sample size $=$ 16\\[0.2em]
                \begingroup
                \renewcommand{\arraystretch}{1.5}
                \begin{tabular}{|r|l|}
                \hline
                    Upper Control Limit & \phantom{blahblahblahblah}\\
                    \hline
                    $+$2$\sigma$ Limit & \\
                    \hline
                    $+$1$\sigma$ Limit & \\
                    \hline
                    Target Value & \\
                    \hline
                    $-$1$\sigma$ Limit & \\
                    \hline
                    $-$2$\sigma$ Limit & \\
                    \hline
                    Lower Control Limit & \\
                    \hline
                \end{tabular}
                \endgroup
            \item Population mean $=$ 486\\
            Population standard deviation $=$ 17\\
            Sample size $=$ 12\\[0.2em]
                \begingroup
                \renewcommand{\arraystretch}{1.5}
                \begin{tabular}{|r|l|}
                \hline
                    Upper Control Limit & \phantom{blahblahblahblah}\\
                    \hline
                    $+$2$\sigma$ Limit & \\
                    \hline
                    $+$1$\sigma$ Limit & \\
                    \hline
                    Target Value & \\
                    \hline
                    $-$1$\sigma$ Limit & \\
                    \hline
                    $-$2$\sigma$ Limit & \\
                    \hline
                    Lower Control Limit & \\
                    \hline
                \end{tabular}
                \endgroup
        \end{enumerate}
    \end{multicols}
    \item A factory produces plastic guitar plectrums which are sold with a labelled thickness of 1.4mm. The actual thickness of plectrums produced by the factory's equipment is normally distributed with a mean of 1.4mm and standard deviation 0.1mm. An $x$-bar chart is to be produced to monitor the performance of the process. Calculate the 2-sigma limits for the control chart.
    \item A factory produces plastic guitar plectrums which are sold with a labelled thickness of 1.4mm. The actual thickness of plectrums produced by the factory's equipment is normally distributed with a mean of 1.4mm and standard deviation 0.1mm. An $x$-bar chart is to be produced to monitor the performance of the process, using random samples of size 18. Calculate the 2-sigma limits for the control chart.
    \item A cosmetic company has a machine which dispenses shampoo into bottles. The machine has been calibrated to dispense a mean volume of 230ml into each bottle, and the amount dispensed has been found to be normally distributed with a standard deviation of 4ml. To monitor the performance of the machine, a sample of five bottles is taken each hour, the volume of shampoo measured and an $x$-bar chart created.
\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.8) {sample number};
        \node[rotate=90] at (-1.5,0) {sample mean (ml)};
        \node at (6,4) {$x$-bar chart of mean shampoo volume};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3) node[right] {UCL};
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0) node[right] {target};
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-3) -- (11.9,-3) node[right] {LCL};
        \foreach \x in {1,2,...,12}{
        \draw (\x-0.5,-3.5) -- (\x-0.5,-3.7) node[below] {\x};
        }
        \node[left] at (0,3*2*0.559) {236};
        \node[left] at (0,2*2*0.559) {234};
        \node[left] at (0,1*2*0.559) {232};
        \node[left] at (0,0*2*0.559) {230};
        \node[left] at (0,-1*2*0.559) {228};
        \node[left] at (0,-2*2*0.559) {226};
        \node[left] at (0,-3*2*0.559) {224};
        \coordinate (A) at (1-0.5,0.85);
        \coordinate (B) at (2-0.5,0.3);
        \coordinate (C) at (3-0.5,-0.2);
        \coordinate (D) at (4-0.5,-1.6);
        \coordinate (E) at (5-0.5,0.2);
        \coordinate (F) at (6-0.5,0.85);
        \coordinate (G) at (7-0.5,-0.45);
        \coordinate (H) at (8-0.5,0.2);
        \coordinate (I) at (9-0.5,2.15);
        \coordinate (J) at (10-0.5,1.3);
        \coordinate (K) at (11-0.5,2.34);
        \coordinate (L) at (12-0.5,-1.3);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L);
        \end{tikzpicture}
\end{center}
    \begin{enumerate}
        \item Calculate the 1-sigma limits for the $x$-bar chart.
        \item Determine if the machine is under statistical control during this period.
        \item State an assumption required for the described use of the $x$-bar chart to be appropriate.
    \end{enumerate}
\end{enumerate}

\pagebreak

\begin{enumerate}[resume]
    \item A video game producer monitors the responsiveness of the connections it provides to online gamers by measuring the amount of delay they experience, called their \textit{ping}. This is measured in milliseconds and it is known that the amount of \textit{ping} experienced by gamers is normally distributed with a mean of 144 milliseconds and a standard deviation of 18 milliseconds. Every hour, the ping is recorded for a random sample of 7 gamers, and the results added to an $x$-bar control chart, shown below.
\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.7) {sample time};
        \node[rotate=90] at (-1.8,0) {sample mean (ms)};
        \node at (6,4) {control chart for ping};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3);
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0);
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-3) -- (11.9,-3);
        \node[left] at (13.2,3) {UCL};
        \node[left] at (13.2,2) {$+$2$\sigma$};
        \node[left] at (13.2,1) {$+$1$\sigma$};
        \node[left] at (13.2,-0.05) {$\mu$};
        \node[left] at (13.2,-1) {$-$1$\sigma$};
        \node[left] at (13.2,-2) {$-$2$\sigma$};
        \node[left] at (13.2,-3) {LCL};
        \node[right] at (13,3) {$=$ 164.4};
        \node[right] at (13,2) {$=$ 157.6};
        \node[right] at (13,1) {$=$ 150.8};
        \node[right] at (13,0) {$=$ 144.0};
        \node[right] at (13,-1) {$=$ 137.2};
        \node[right] at (13,-2) {$=$ 130.4};
        \node[right] at (13,-3) {$=$ 123.6};
        \foreach \x in {1,3,...,11}{
        \draw (0.7*\x,-3.5) -- (0.7*\x,-3.7) node[below] {\x am};
        }
        \foreach \x in {1,3}{
        \draw (0.7*\x+8.4,-3.5) -- (0.7*\x+8.4,-3.7) node[below] {\x pm};
        }
        \node[left] at (0,16*0.147) {160};
        \node[left] at (0,6*0.147) {150};
        \node[left] at (0,-4*0.147) {140};
        \node[left] at (0,-14*0.147) {130};
        \draw (0,16*0.147) -- ++(-0.1,0);
        \draw (0,6*0.147) -- ++(-0.1,0);
        \draw (0,-4*0.147) -- ++(-0.1,0);
        \draw (0,-14*0.147) -- ++(-0.1,0);
        \coordinate (A) at (1*0.7,0.523);
        \coordinate (B) at (2*0.7,-0.467);
        \coordinate (C) at (3*0.7,0.666);
        \coordinate (D) at (4*0.7,-1.73);
        \coordinate (E) at (5*0.7,0.039);
        \coordinate (F) at (6*0.7,-1.90);
        \coordinate (G) at (7*0.7,-1.19);
        \coordinate (H) at (8*0.7,-0.149);
        \coordinate (I) at (9*0.7,-0.85);
        \coordinate (J) at (10*0.7,-2.31);
        \coordinate (K) at (11*0.7,1.09);
        \coordinate (L) at (12*0.7,-1.19);
        \coordinate (M) at (13*0.7,0.166);
        \coordinate (N) at (14*0.7,-0.116);
        \coordinate (O) at (15*0.7,-2.214);
        \coordinate (P) at (16*0.7,-1.6);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw[fill=black] (M) circle (2pt);
        \draw[fill=black] (N) circle (2pt);
        \draw[fill=black] (O) circle (2pt);
        \draw[fill=black] (P) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L) -- (M) -- (N) -- (O) -- (P);
        \end{tikzpicture}
\end{center}
\begin{enumerate}
    \item Show the calculation required to obtain the lower control limit shown on the chart.
\end{enumerate}
It can be determined from the control chart that the process is under statistical control for the duration of the times shown, since none of the WECO Rules have been broken.
\begin{enumerate}[resume]
    \item State the range of possible values for the next sample mean, $\bar{x}$, to be taken at 5pm, such that the process would remain in statistical control.
\end{enumerate}
    \item A camera lens manufacturer uses an $x$-bar control chart to monitor the quality of copies of a particular model of lens which it produces. The resolution of the lenses are measured using \textit{MTF testing}, where a higher score indicates a higher resolution, which is desired. The manufacturer knows that the resolution of copies of the lens it produces varies, with a mean of 3600 and standard deviation of 120. Samples are taken at regular intervals, and their sample means plotted on the chart are below.
    \begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.7) {sample number};
        \node[rotate=90] at (-1.8,0) {resolution (MTF)};
        \node at (6,4) {$x$-bar chart for lens resolution};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3);
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0);
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-3) -- (11.9,-3);
        \node[right] at (12,3) {UCL};
        \node[right] at (12,2) {$+$2$\sigma=$ 3680};
        \node[right] at (12,1) {$+$1$\sigma$};
        \node[right] at (12,-0.05) {\phantom{$-$}$\mu$};
        \node[right] at (12,-1) {$-$1$\sigma$};
        \node[right] at (12,-2) {$-$2$\sigma$};
        \node[right] at (12,-3) {LCL};
        \foreach \x in {1,2,3,...,16}{
        \draw (0.7*\x,-3.5) -- (0.7*\x,-3.7) node[below] {\x};
        }
        \node[left] at (0,2.5) {3700};
        \node[left] at (0,1.25) {3650};
        \node[left] at (0,0) {3600};
        \node[left] at (0,-1.25) {3550};
        \node[left] at (0,-2.5) {3500};
        \foreach \y in {-2.5,-1.25,0,1.25,2.5}{
        \draw (0,\y) -- (-0.1,\y);
        }
        \coordinate (A) at (0.7,0.154436860641377);
\coordinate (B) at (1.4,0.321811220337897);
\coordinate (C) at (2.1,-1.37111248654158);
\coordinate (D) at (2.8,0.479119042455258);
\coordinate (E) at (3.5,0.773478705099278);
\coordinate (F) at (4.2,-0.3884358156992);
\coordinate (G) at (4.9,-0.0106885821941205);
\coordinate (H) at (5.6,-1.29623399750069);
\coordinate (I) at (6.3,1.12017796406863);
\coordinate (J) at (7,0.572769916162298);
\coordinate (K) at (7.7,0.41040670415183);
\coordinate (L) at (8.4,0.202306747804308);
\coordinate (M) at (9.1,2.12893972218359);
\coordinate (N) at (9.8,0.3421464501245687);
\coordinate (O) at (10.5,0.608272461080391);
\coordinate (P) at (11.2,2.06833702762749);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw[fill=black] (M) circle (2pt);
        \draw[fill=black] (N) circle (2pt);
        \draw[fill=black] (O) circle (2pt);
        \draw[fill=black] (P) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L) -- (M) -- (N) -- (O) -- (P);
        \end{tikzpicture}
\end{center}
    \begin{enumerate}
        \item Describe the feature of the $x$-bar chart which means the process is out of statistical control, and explain why the lens manufacturers may not be concerned about this in practice.
        \item Use the 2$\sigma$-limit shown to determine the size of each sample of lenses taken.
        \item State two assumptions required for the use of the $x$-bar chart by the manufacturers.
    \end{enumerate}
\end{enumerate}

\pagebreak

\begin{enumerate}[resume]
    \item A coffee company sells canned, chilled `espresso' drinks in supermarkets. The amount of caffeine contained in each can is known to be normally distributed with a mean of 115mg and a standard deviation of 8mg. To comply with legal requirements, the company uses an $x$-bar control chart to monitor the manufacturing process, taking a random sample of 16 cans each hour and measuring the amount of caffeine they contain, recording the sample mean each time. The results of a series of 10 consecutive samples is shown in the table below.
  
\begin{center}
    \begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        \textbf{Sample} & \textbf{1} & \textbf{2} & \textbf{3} & \textbf{4} & \textbf{5} & \textbf{6} & \textbf{7} & \textbf{8} & \textbf{9} & \textbf{10}\\
        \hline
        Caffeine (mg) & 113.7& 119.7 &118.6& 120.9 &114.6 &113.9 &110.4 &113.1 &116.5 & 114.2\\
        \hline
    \end{tabular}
\end{center}
    \begin{enumerate}
        \item Calculate each of the control limits and hence explain why it can be identified that the process is out of statistical control at sample 4.
    \end{enumerate}
    The coffee company has created a new `chilled cappuccino' drink, also sold in cans, and wishes to use an $x$-bar control chart to monitor caffeine content of the cans produced by the manufacturing process. Since at this stage the population mean caffeine content is unknown, its value must be estimated from the \textit{mean of the sample means} of the first batch of sample measurements, known as `$x$ bar bar' ($\bar{\bar{x}}$), as is common when a control chart for a manufacturing process is being set up for the first time.\\[0.1em]
    The results of the first 20 samples are shown in the table below.
\begin{center}
    \begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        \textbf{Sample} & \textbf{1} & \textbf{2} & \textbf{3} & \textbf{4} & \textbf{5} & \textbf{6} & \textbf{7} & \textbf{8} & \textbf{9} & \textbf{10}\\
        \hline
        Caffeine (mg) & 96.3 &92.1& 97.4 &89.8& 98.0 &92.4 &90.5 &90.2 &90.6 &95.2\\
        \hline
        \textbf{Sample} & \textbf{11} & \textbf{12} & \textbf{13} & \textbf{14} & \textbf{15} & \textbf{16} & \textbf{17} & \textbf{18} & \textbf{19} & \textbf{20}\\
        \hline
        Caffeine (mg) &  92.1& 90.3 &94.4 &91.7& 88.9& 91.4& 90.4 &88.3 &90.7& 89.3\\
        \hline
    \end{tabular}
\end{center}
\begin{enumerate}[resume]
    \item Determine $\bar{\bar{x}}$, an estimate for the population mean caffeine content of the production process.
    \item Given that the population standard deviation is subsequently determined to be 6mg, determine the values of the upper and lower control limits for samples of size 4.
\end{enumerate}
\item Control charts are to be produced for sample means taken to monitor the following processes. If the samples are random, and it can be assumed that the processes can be suitably described by the normal distribution, copy and complete the following tables for the $x$-bar charts:
    \begin{multicols}{2}
        \begin{enumerate}
            \item \phantom{ }\\
                \begingroup
                \renewcommand{\arraystretch}{1.5}
                \begin{tabular}{|r|l|}
                \hline
                    Population mean & \\
                    \hline
                    Standard deviation & \\
                    \hline
                    Sample size & 25\\
                    \hline
                    \hline
                    Upper Control Limit & \phantom{blahblahblahblah}\\
                    \hline
                    $+$2$\sigma$ Limit & 78\\
                    \hline
                    $+$1$\sigma$ Limit & \\
                    \hline
                    Target Value & \\
                    \hline
                    $-$1$\sigma$ Limit & \\
                    \hline
                    $-$2$\sigma$ Limit & 66\\
                    \hline
                    Lower Control Limit & \\
                    \hline
                \end{tabular}
                \endgroup
            \item \phantom{ }\\
                \begingroup
                \renewcommand{\arraystretch}{1.5}
                \begin{tabular}{|r|l|}
                \hline
                    Population mean & 2800\\
                    \hline
                    Standard deviation & 60\\
                    \hline
                    Sample size & \\
                    \hline
                    \hline
                    Upper Control Limit & \phantom{blahblahblahblah}\\
                    \hline
                    $+$2$\sigma$ Limit & \\
                    \hline
                    $+$1$\sigma$ Limit & \\
                    \hline
                    Target Value & \\
                    \hline
                    $-$1$\sigma$ Limit & \\
                    \hline
                    $-$2$\sigma$ Limit & 2760\\
                    \hline
                    Lower Control Limit & \\
                    \hline
                \end{tabular}
                \endgroup
        \end{enumerate}
    \end{multicols}
\end{enumerate}

\pagebreak

## Shewhart \textit{p} Charts for a Proportion

For some quality control processes the attribute of interest will be a *quality* rather than a numerical value, hence calculating a mean is not possible. For such cases, a control chart for $x$-bar is not appropriate. Such a *quality* typically takes the form of a binary outcome, such as *defective* or *not defective*. The *proportion* of products within each random sample (of size $n$) that take a particular outcome (such as *defective*) may instead be calculated, and a control chart for proportion, or $p$-chart, created.

For $np>5$ and $nq>5$ the sampling distribution of the sample proportion may be described by $\hat{P}\approx \text{N}\left(p,\dfrac{pq}{n}\right)$.

This leads to the 3-sigma control limits for a $p$-chart, for population proportion $p$, of $p\text{ }\pm \text{ }3\sqrt{\dfrac{pq}{n}}$.

Similarly, the $1\sigma$ and $2\sigma$ limits can be calculated respectively as $p\text{ }\pm \text{ }\sqrt{\dfrac{pq}{n}}$ and $p\text{ }\pm \text{ }2\sqrt{\dfrac{pq}{n}}$.

It should be noted that, depending on the value of $p$, it is not unusual for the lower control limit to be negative or the upper control limit to be greater than 1. When this happens the lower control limit should be given as 0 or the upper control limit given as 1.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} A machine produces packs of football stickers. 15\% of the packs are supposed to contain a \textit{`shiny'} sticker. Every 30 minutes a sample of 60 packs are taken and the number containing a `shiny' is counted, with the proportion for each sample plotted on a $p$-chart.

\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.8) {sample number};
        \node[rotate=90] at (-1.8,0) {sample proportion};
        \node at (6,4) {$p$-chart of proportion of packs containing a `shiny'};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3) node[right] {UCL};
        \draw[dashed] (0.1,2) -- (11.9,2) node[right] {$+2\sigma$};
        \draw[dashed] (0.1,1) -- (11.9,1) node[right] {$+1\sigma$};
        \draw[thick] (0.1,0) -- (11.9,0) node[right] {target};
        \draw[dashed] (0.1,-1) -- (11.9,-1) node[right] {$-1\sigma$};
        \draw[dashed] (0.1,-2) -- (11.9,-2) node[right] {$-2\sigma$};
        \draw[thick, densely dashed] (0.1,-3) -- (11.9,-3) node[right] {LCL};
        \foreach \x in {1,2,...,12}{
        \draw (\x-0.5,-3.5) -- (\x-0.5,-3.7) node[below] {\x};
        }
        \node[left] at (0,3*1.08465) {0.30};
        \node[left] at (0,2*1.08465) {0.25};
        \node[left] at (0,1*1.08465) {0.20};
        \node[left] at (0,0*1.08465) {0.15};
        \node[left] at (0,-1*1.08465) {0.10};
        \node[left] at (0,-2*1.08465) {0.05};
        \node[left] at (0,-3*1.08465) {0.00};
        \coordinate (A) at (0.5,-0.723101526062187);
\coordinate (B) at (1.5,0);
\coordinate (C) at (2.5,0.361550763031094);
\coordinate (D) at (3.5,-0.361550763031094);
\coordinate (E) at (4.5,-0.723101526062187);
\coordinate (F) at (5.5,-0.361550763031094);
\coordinate (G) at (6.5,-0.723101526062187);
\coordinate (H) at (7.5,0.723101526062187);
\coordinate (I) at (8.5,2.16930457818656);
\coordinate (J) at (9.5,0.723101526062187);
\coordinate (K) at (10.5,2.53085534121766);
\coordinate (L) at (11.5,2.16930457818656);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L);
        \end{tikzpicture}
\end{center}

Calculate the $3\sigma$ limits and determine if the $p$-chart is in statistical control for the samples given.

\tcblower
\textbf{Solution:}

$3\sigma$ limits: $p \text{ }\pm \text{ } 3\times\sqrt{\dfrac{pq}{n}}=0.15\text{ }\pm\text{ }3\times\sqrt{\dfrac{0.15\times0.85}{60}}=0.15\text{ }\pm\text{ }0.1383$, so $0.0117$ and $0.2883$.\\[0.1em]
The process is out of statistical control at sample 11 as two out of three consecutive sample proportions (from 9 to 11) lie above the upper 2$\sigma$ limit. The process needs to be stopped and investigated.

\end{tcolorbox}

If no historical value of the population proportion has been suggested, then it may be appropriate to calculate an overall sample proportion $\hat{p}$ from initial data, to be used as an estimate for the population proportion $p$.

\pagebreak

[]{#ex133q}

#### [Exercise 13.3](#ex133a) {-}

\begin{enumerate}
    \item Control charts are to be produced for sample proportions taken to monitor the following processes. If the samples are random, copy and complete the following tables showing limits for the $p$-charts:
    \begin{multicols}{2}
        \begin{enumerate}
            \item Population proportion $=$ 0.6\\
            Sample size $=$ 24\\[0.2em]
                \begingroup
                \renewcommand{\arraystretch}{1.5}
                \begin{tabular}{|r|l|}
                \hline
                    Upper Control Limit & \phantom{blahblahblahblah}\\
                    \hline
                    $+$2$\sigma$ Limit & \\
                    \hline
                    $+$1$\sigma$ Limit & \\
                    \hline
                    Target Value & \\
                    \hline
                    $-$1$\sigma$ Limit & \\
                    \hline
                    $-$2$\sigma$ Limit & \\
                    \hline
                    Lower Control Limit & \\
                    \hline
                \end{tabular}
                \endgroup
            \item Population proportion $=$ 0.16\\
            Sample size $=$ 50\\[0.2em]
                \begingroup
                \renewcommand{\arraystretch}{1.5}
                \begin{tabular}{|r|l|}
                \hline
                    Upper Control Limit & \phantom{blahblahblahblah}\\
                    \hline
                    $+$2$\sigma$ Limit & \\
                    \hline
                    $+$1$\sigma$ Limit & \\
                    \hline
                    Target Value & \\
                    \hline
                    $-$1$\sigma$ Limit & \\
                    \hline
                    $-$2$\sigma$ Limit & \\
                    \hline
                    Lower Control Limit & \\
                    \hline
                \end{tabular}
                \endgroup
        \end{enumerate}
    \end{multicols}
    \item A manufacturer of kitchenware knows that 8\% of the mugs produced by one of its factory lines do not meet the quality threshold. It has been determined that taking steps to reduce this proportion is not cost effective, but they want to monitor this proportion of `defective' mugs using a control chart. One supervisor suggests checking the first 30 mugs each shift, calculating the proportion of `defective' mugs each time and monitoring the results using a $p$-chart.
    \begin{enumerate}
        \item Give two reasons why the supervisor's suggestion would not be suitable for creating a $p$-chart.
    \end{enumerate}
    The manufacturer decides to take samples of 75 mugs each shift, and the results after the first week of monitoring are shown on the $p$-chart below.
    \begin{center}
    \begin{tikzpicture}[scale=1]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.8) {sample number};
        \node[rotate=90] at (-1.8,0) {sample proportion};
        \node at (6,4) {$p$-chart of proportion of defective mugs};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3) node[right] {UCL};
        \draw[dashed] (0.1,2) -- (11.9,2) node[right] {$+$2$\sigma$};
        \draw[dashed] (0.1,1) -- (11.9,1) node[right] {$+$1$\sigma$};
        \draw[thick] (0.1,0) -- (11.9,0) node[right] {target};
        \draw[dashed] (0.1,-1) -- (11.9,-1) node[right] {$-$1$\sigma$};
        \draw[dashed] (0.1,-2) -- (11.9,-2) node[right] {$-$2$\sigma$};
        \draw[thick, densely dashed] (0.1,-8*0.32) -- (11.9,-8*0.32) node[right] {LCL};
        \draw[thick] (0.1,-8*0.32) -- (11.9,-8*0.32) node[right] {LCL};
        \foreach \x in {1,2,...,16}{
        \draw (0.7*\x,-3.5) -- (0.7*\x,-3.7) node[below] {\x};
        }
        \node[left] at (0,8*0.32) {0.16};
        \node[left] at (0,4*0.32) {0.12};
        \node[left] at (0,0*0.32) {0.08};
        \node[left] at (0,-4*0.32) {0.04};
        \node[left] at (0,-8*0.32) {0.00};
        \coordinate (A) at (0.7,1.62);
\coordinate (B) at (1.4,-0.32);
\coordinate (C) at (2.1,-1.29);
\coordinate (D) at (2.8,0.32);
\coordinate (E) at (3.5,-1.29);
\coordinate (F) at (4.2,-0.32);
\coordinate (G) at (4.9,-1.29);
\coordinate (H) at (5.6,-0.92);
\coordinate (I) at (6.3,-0.32);
\coordinate (J) at (7,-0.64);
\coordinate (K) at (7.7,0.97);
\coordinate (L) at (8.4,1.62);
\coordinate (M) at (9.1,-0.32);
\coordinate (N) at (9.8,1.29);
\coordinate (O) at (10.5,0.65);
\coordinate (P) at (11.2,-0.32);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw[fill=black] (M) circle (2pt);
        \draw[fill=black] (N) circle (2pt);
        \draw[fill=black] (O) circle (2pt);
        \draw[fill=black] (P) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L) -- (M) -- (N) -- (O) -- (P);
        \end{tikzpicture}
\end{center}
    \begin{enumerate}[resume]
        \item Calculate the 2-sigma limits for the $p$-chart.
        \item Determine whether the manufacturing process is in statistical control.
    \end{enumerate}
\end{enumerate}

\pagebreak

\begin{enumerate}[resume]
    \item A company selling seeds for a commonly grown garden flower wishes to use a control chart to monitor the quality of its process. It is known that 11\% of the seeds will fail to germinate even under ideal conditions. To monitor the rate of seeds that fail to germinate, the company randomly selects 50 seeds from each weekly batch and sows them individually in ideal conditions, recording the proportion of seeds which fail to germinate for each sample on a $p$-chart. The results of 12 such consecutive samples are shown below.
    \begin{center}
    \begin{tikzpicture}[scale=1]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.8) {sample number};
        \node[rotate=90] at (-1.8,0) {sample proportion};
        \node at (6,4) {$p$-chart of proportion of failed seeds};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3);
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0);
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-11*0.226) -- (11.9,-11*0.226);
        \draw[thick] (0.1,-11*0.226) -- (11.9,-11*0.226);
        \node[left] at (13.2,3) {UCL};
        \node[left] at (13.2,2) {$+$2$\sigma$};
        \node[left] at (13.2,1) {$+$1$\sigma$};
        \node[left] at (13.2,-0.05) {target};
        \node[left] at (13.2,-1) {$-$1$\sigma$};
        \node[left] at (13.2,-2) {$-$2$\sigma$};
        \node[left] at (13.2,-11*0.226) {LCL};
        \node[right] at (13,3) {$=$ 0.2427};
        \node[right] at (13,0) {$=$ 0.11};
        \node[right] at (13,-11*0.226) {$=$ 0};
        \foreach \x in {1,2,...,12}{
        \draw (\x-0.5,-3.5) -- (\x-0.5,-3.7) node[below] {\x};
        }
        \node[left] at (0,14*0.226) {0.25};
        \node[left] at (0,9*0.226) {0.20};
        \node[left] at (0,4*0.226) {0.15};
        \node[left] at (0,-1*0.226) {0.10};
        \node[left] at (0,-6*0.226) {0.05};
        \node[left] at (0,-11*0.226) {0.00};
        \coordinate (A) at (0.5,1.58);
\coordinate (B) at (1.5,-0.23);
\coordinate (C) at (2.5,-1.58);
\coordinate (D) at (3.5,0.25);
\coordinate (E) at (4.5,-1.58);
\coordinate (F) at (5.5,-1.13);
\coordinate (G) at (6.5,-1.58);
\coordinate (H) at (7.5,-0.68);
\coordinate (I) at (8.5,-0.23);
\coordinate (J) at (9.5,-0.68);
\coordinate (K) at (10.5,0.25);
\coordinate (L) at (11.5,1.58);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L);
        \end{tikzpicture}
\end{center}
\begin{enumerate}
    \item Show the calculation required to determine that the upper control limit is 0.2427.
    \item Explain the use of the lower control limit of 0.
    \item State how it can be observed that the process is out of statistical control.
    \item Explain why the company will likely not be concerned about this.
\end{enumerate}
    \item A car insurance provider sets a target for 80\% of claims to be processed and resolved within two weeks. To monitor this, each month 60 claims are randomly selected to be tracked, and the proportion of these claims resolved within two weeks recorded on a $p$-chart. Below is the data for 2024.
    \vspace{-0.5cm}
    \begin{center}
        \begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|c|}
            \hline
            Month & Jan & Feb & Mar & Apr & May & Jun & Jul & Aug & Sept & Oct & Nov & Dec\\
            \hline
            $\hat{p}$ & 0.817 & 0.783 & 0.75 & 0.683 & 0.767 & 0.717 & 0.733 & 0.783 & 0.7 & 0.833 & 0.8 & 0.767\\
            \hline
        \end{tabular}
    \end{center}
    \begin{enumerate}
        \item Determine the value of the upper and lower control limits for the $p$-chart.
        \item Without performing any further calculations, explain why the data for 2024 shows that the processing and resolving of claims is out of statistical control.
    \end{enumerate}
    After working on staff training and the efficiency of its systems, the car insurance provider is able to bring its proportion of claims resolved within two weeks up to 83\%, where it remains steady throughout the year. For 2026, they wish to reduce the number of claims to sample each month, whilst still having a sufficient size for appropriate use of a $p$-chart.
    \begin{enumerate}[resume]
        \item Determine the minimum sample size required for a $p$-chart with a population proportion of 83\%.
    \end{enumerate}
\end{enumerate}

\pagebreak

\begin{enumerate}[resume]
    \item A factory uses a machine to insert rubber corks to seal bottles of wine. When this process fails, the bottle is diverted back into the line of bottles waiting to be sealed, slowing down the process. The factory wishes to set up a $p$-chart to monitor the proportion of bottles which fail to be sealed on the first attempt, especially since an increase may suggest the machine is in need of additional maintenance. Each day over the course of two weeks, a random sample of 50 bottles are tagged and monitored, and the number of bottles for each sample which fail to be sealed on the first attempt is recorded. A table showing the results is shown below.
    \begin{center}
        \begin{tabular}{|c|c|c|c|c|c|c|c|}
            \hline
            Week 1 & Mon & Tue & Wed & Thu & Fri & Sat & Sun\\
            \hline
            Failures & 8 & 5 & 7 & 5 & 6 & 6 & 4\\
            \hline
            \hline
            Week 2 & Mon & Tue & Wed & Thu & Fri & Sat & Sun\\
            \hline
            Failures & 7 & 8 & 4 & 5 & 7 & 6 & 6\\
            \hline
        \end{tabular}
    \end{center}
    It is decided that this data is sufficient to allow a $p$-chart to be created to monitor the proportion of bottles which fail to be sealed by the machine, taking the total sample proportion $\hat{p}$ for the two weeks as a reliable estimator for the population proportion, $p$.
    \begin{enumerate}
        \item Calculate the value of $\hat{p}$ from the table above, to be used as an estimator for $p$.
        \item Show the calculations required to obtain 2-sigma limits for the $p$-chart of 0.028 and 0.212.
    \end{enumerate}
    A $p$-chart is constructed and data from the next two weeks is plotted on the chart.
    \begin{center}
    \begin{tikzpicture}[scale=1]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.8) {sample number};
        \node[rotate=90] at (-1.8,0) {sample proportion};
        \node at (6,4) {$p$-chart of proportion of failed bottles};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3);
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0);
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-13*0.2176) -- (11.9,-13*0.2176);
        \draw[thick] (0.1,-12*0.2176) -- (11.9,-12*0.2176);
        \node[left] at (13.2,3) {UCL};
        \node[left] at (13.2,2) {$+$2$\sigma$};
        \node[left] at (13.2,1) {$+$1$\sigma$};
        \node[left] at (13.2,-0.05) {target};
        \node[left] at (13.2,-1) {$-$1$\sigma$};
        \node[left] at (13.2,-2) {$-$2$\sigma$};
        \node[left] at (13.2,-13*0.2176) {LCL};
        \node[left] at (13.2,-12*0.2176) {LCL};
        \node[right] at (13,2) {$=$ 0.212};
        \node[right] at (13,0) {$=$ 0.12};
        \node[right] at (13,-2) {$=$ 0.028};
        \foreach \x in {1,2,...,14}{
        \draw (0.8*\x,-3.5) -- (0.8*\x,-3.7) node[below] {\x};
        }
        \node[left] at (0,13*0.2176) {0.25};
        \node[left] at (0,8*0.2176) {0.20};
        \node[left] at (0,3*0.2176) {0.15};
        \node[left] at (0,-2*0.2176) {0.10};
        \node[left] at (0,-7*0.2176) {0.05};
        \node[left] at (0,-13*0.2176) {0.00};
        \node[left] at (0,-12*0.2176) {0.00};
\coordinate (A) at (1*0.8,21.76*0.02*8-0.12*21.76);
\coordinate (B) at (2*0.8,21.76*0.02*3-0.12*21.76);
\coordinate (C) at (3*0.8,21.76*0.02*2-0.12*21.76);
\coordinate (D) at (4*0.8,21.76*0.02*6-0.12*21.76);
\coordinate (E) at (5*0.8,21.76*0.02*7-0.12*21.76);
\coordinate (F) at (6*0.8,21.76*0.02*6-0.12*21.76);
\coordinate (G) at (7*0.8,21.76*0.02*3-0.12*21.76);
\coordinate (H) at (8*0.8,21.76*0.02*7-0.12*21.76);
\coordinate (I) at (9*0.8,21.76*0.02*8-0.12*21.76);
\coordinate (J) at (10*0.8,21.76*0.02*0-0.12*21.76);
\coordinate (K) at (11*0.8,21.76*0.02*8-0.12*21.76);
\coordinate (L) at (12*0.8,21.76*0.02*6-0.12*21.76);
\coordinate (M) at (13*0.8,21.76*0.02*2-0.12*21.76);
\coordinate (N) at (14*0.8,21.76*0.02*7-0.12*21.76);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw[fill=black] (M) circle (2pt);
        \draw[fill=black] (N) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L) -- (M) -- (N);
        \end{tikzpicture}
\end{center}
    \begin{enumerate}[resume]
        \item Determine whether the process is in statistical control during the two week period.
    \end{enumerate}
    \item A $p$-chart is created using regular random samples.\newline The 2-sigma limits are calculated as 0.4 and 0.8.\newline
    Determine:
    \item A $p$-chart is created using regular, random samples. The 2-sigma limits are calculated as 0.4 and 0.8.
    
    \begin{enumerate}
        \item State the value of the population proportion, $p$.
        \item Calculate the upper and lower control limits.
        \item Determine the size of each sample.
        \item Show that the sample size and the proportion meet the requirements for constructing a $p$-chart.
    \end{enumerate}
\end{enumerate}

\pagebreak

[]{#re18q}

## [Review Exercise](#re18a) {-}

\begin{enumerate}
    \item Eggs are grouped according to size by a machine, and the eggs sorted into the \textit{medium} category are known to have a mean mass of 58 grams with standard deviation 3 grams. To monitor the performance of the machine, eight eggs are randomly selected every fifteen minutes and the mean mass for each sample recorded on an $x$-bar chart, shown below.
\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.7) {sample time};
        \node[rotate=90] at (-1.8,0) {sample mean (g)};
        \node at (6,4) {$x$-bar chart for medium egg mass};
        \draw[thick, densely dashed] (0.1,3) -- (11.9,3);
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0);
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-3) -- (11.9,-3);
        \node[left] at (13.4,3) {UCL};
        \node[left] at (13.4,2) {$+$2$\sigma$};
        \node[left] at (13.4,1) {$+$1$\sigma$};
        \node[left] at (13.4,-0.05) {mean};
        \node[left] at (13.4,-1) {$-$1$\sigma$};
        \node[left] at (13.4,-2) {$-$2$\sigma$};
        \node[left] at (13.4,-3) {LCL};
        \foreach \x in {1,3,...,15}{
        \draw (0.7*\x,-3.5) -- (0.7*\x,-3.7) node[below] {\x};
        }
        \foreach \x in {2,4,...,16}{
        \draw (0.7*\x,-3.5) -- (0.7*\x,-3.7);
        }
        \foreach \x in {55,56,...,61}{
        \draw (0,\x*0.942809-58*0.942809) -- (-0.1,\x*0.942809-58*0.942809) node[left] {\x};
        }
        \coordinate (A) at (1*0.7,-0.11);
        \coordinate (B) at (2*0.7,0.67);
        \coordinate (C) at (3*0.7,-0.74);
        \coordinate (D) at (4*0.7,-0.88);
        \coordinate (E) at (5*0.7,-0.39);
        \coordinate (F) at (6*0.7,-0.54);
        \coordinate (G) at (7*0.7,2.06);
        \coordinate (H) at (8*0.7,0.15);
        \coordinate (I) at (9*0.7,-2.17);
        \coordinate (J) at (10*0.7,-0.37);
        \coordinate (K) at (11*0.7,0.35);
        \coordinate (L) at (12*0.7,-2.12);
        \coordinate (M) at (13*0.7,2.80);
        \coordinate (N) at (14*0.7,-3.13);
        \coordinate (O) at (15*0.7,-2.52);
        \coordinate (P) at (16*0.7,-1.33);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw[fill=black] (M) circle (2pt);
        \draw[fill=black] (N) circle (2pt);
        \draw[fill=black] (O) circle (2pt);
        \draw[fill=black] (P) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L) -- (M) -- (N) -- (O) -- (P);
        \end{tikzpicture}
\end{center}
\begin{enumerate}
    \item Calculate the 2-sigma limits for the $x$-bar chart
    \item Determine whether the process is under statistical control for the 16 samples shown.
\end{enumerate}
    \item A large company which employs tens of thousands of people uses $p$-charts to monitor its employee satisfaction. Each month, 50 employees are selected at random and asked to complete a short questionnaire, including being asked to rate their current satisfaction with their job. It is known that historically 88\% of employees respond that they are either \textit{satisfied} or \textit{very satisfied}. The results of the last 14 months data is below, which is found to be \textit{under statistical control}.
    \begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw (0,-3.5) rectangle (12,3.5);
        \node at (6,-4.8) {sample number};
        \node[rotate=90] at (-1.8,0) {sample proportion};
        \node at (6,4) {$p$-chart of proportion of satisfied/very satisfied employees};
        \draw[thick] (0.1,12*0.2176) -- (11.9,12*0.2176);
        \draw[dashed] (0.1,2) -- (11.9,2);
        \draw[dashed] (0.1,1) -- (11.9,1);
        \draw[thick] (0.1,0) -- (11.9,0);
        \draw[dashed] (0.1,-1) -- (11.9,-1);
        \draw[dashed] (0.1,-2) -- (11.9,-2);
        \draw[thick, densely dashed] (0.1,-3) -- (11.9,-3);
        \node[left] at (13.2,2) {$+$2$\sigma$};
        \node[left] at (13.2,1) {$+$1$\sigma$};
        \node[left] at (12.6,-0.05) {$p$};
        \node[left] at (13.2,-1) {$-$1$\sigma$};
        \node[left] at (13.2,-2) {$-$2$\sigma$};
        \node[left] at (13.2,-3) {LCL};
        \node[right] at (12.4,0) {$=$ 0.88};
        \foreach \x in {1,2,...,14}{
        \draw (0.8*\x,-3.5) -- (0.8*\x,-3.7) node[below] {\x};
        }
        \node[left] at (0,12*0.2176) {1.00};
        \node[left] at (0,7*0.2176) {0.95};
        \node[left] at (0,2*0.2176) {0.90};
        \node[left] at (0,-3*0.2176) {0.85};
        \node[left] at (0,-8*0.2176) {0.80};
        \node[left] at (0,-13*0.2176) {0.75};
\coordinate (A) at (1*0.8,21.76*0.02*45-0.88*21.76);
\coordinate (B) at (2*0.8,21.76*0.02*44-0.88*21.76);
\coordinate (C) at (3*0.8,21.76*0.02*42-0.88*21.76);
\coordinate (D) at (4*0.8,21.76*0.02*46-0.88*21.76);
\coordinate (E) at (5*0.8,21.76*0.02*49-0.88*21.76);
\coordinate (F) at (6*0.8,21.76*0.02*44-0.88*21.76);
\coordinate (G) at (7*0.8,21.76*0.02*45-0.88*21.76);
\coordinate (H) at (8*0.8,21.76*0.02*43-0.88*21.76);
\coordinate (I) at (9*0.8,21.76*0.02*39-0.88*21.76);
\coordinate (J) at (10*0.8,21.76*0.02*41-0.88*21.76);
\coordinate (K) at (11*0.8,21.76*0.02*40-0.88*21.76);
\coordinate (L) at (12*0.8,21.76*0.02*38-0.88*21.76);
\coordinate (M) at (13*0.8,21.76*0.02*41-0.88*21.76);
\coordinate (N) at (14*0.8,21.76*0.02*42-0.88*21.76);
        \draw[fill=black] (A) circle (2pt);
        \draw[fill=black] (B) circle (2pt);
        \draw[fill=black] (C) circle (2pt);
        \draw[fill=black] (D) circle (2pt);
        \draw[fill=black] (E) circle (2pt);
        \draw[fill=black] (F) circle (2pt);
        \draw[fill=black] (G) circle (2pt);
        \draw[fill=black] (H) circle (2pt);
        \draw[fill=black] (I) circle (2pt);
        \draw[fill=black] (J) circle (2pt);
        \draw[fill=black] (K) circle (2pt);
        \draw[fill=black] (L) circle (2pt);
        \draw[fill=black] (M) circle (2pt);
        \draw[fill=black] (N) circle (2pt);
        \draw (A) -- (B)-- (C) -- (D) -- (E) -- (F) -- (G) -- (H) -- (I) -- (J) -- (K) -- (L) -- (M) -- (N);
        \end{tikzpicture}
\end{center}
    \begin{enumerate}
        \item Calculate the 1-sigma limits for the control chart.
        \item Given that the process remains to be in statistical control after the next month's data, state the range of possible values for the sample proportion $\hat{p}$ obtained from sample 15.
    \end{enumerate}
\end{enumerate}

\pagebreak
