# Two-Sample Parametric Tests

\vspace{-0.5cm}

Chapter 10 introduced three hypothesis tests which use a single sample of data to assess the evidence for claims relating to a population parameter. For example, a study on the longevity of a brand's light bulbs might check a random sample of such bulbs, to assess whether there is sufficient evidence to suggest the population mean lifespan is greater than 1000 hours. The data from the sample is shown below, with the sample mean $\bar{x}$ indicated:

\begin{figure}[H]
  \centering
\captionsetup[figure]{labelformat=empty}%
\begin{minipage}[c]{.2\textwidth}
  \centering

\begin{center}
\begin{math}
\begin{array}{ll}
      \text{H}_0: & \mu=1000\\[0.5em]
      \text{H}_1: & \mu>1000
    \end{array}
\end{math}
\end{center}

\end{minipage}%
\begin{minipage}[c]{.1\textwidth}
  \centering
  \qquad \qquad
\end{minipage}%
  \centering
\begin{minipage}[c]{.7\textwidth}
  \centering

\begin{center}
\begin{tikzpicture}

\draw[semithick] (0,0) -- (10,0);
\foreach \x in {0.5,1.5,...,9.5}
\draw[semithick] (\x,0) -- (\x,-0.1);
\foreach \x in {900,1000,...,1200}
\node at (0.03*\x-26.5,-0.3) {\x};
\draw[semithick,dashed] (0.03*1056.25-26.5,0) -- (0.03*1056.25-26.5,1.2);
\node at (0.03*1056.25-26.5,1.4) {$\bar{x}$};

\draw[fill=black!25] (0.03*955-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*920-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1030-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1110-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1165-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1065-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1010-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1195-26.5,0.5) circle (3pt);

\end{tikzpicture}
\end{center}

\end{minipage}
\end{figure}

This use of a *one* sample of data, investigating *one* population's parameter, requires a **one-sample test**.

Should a study instead wish to compare the longevity of *two different brands' light bulbs* they would instead take *two samples* of data: one sample from *Brand A* and one sample from *Brand B*. In such a case, a typical set of hypotheses might instead ask whether there is sufficient evidence to suggest that there is a difference between the population mean lifespan for Brand A, $\mu_\text{A}$, and the population mean lifespan for Brand B, $\mu_\text{B}$. The data from the samples are shown below, with the sample means $\bar{x}_\text{A}$ and $\bar{x}_\text{B}$ indicated:

\vspace{-0.2cm}

\begin{figure}[H]
  \centering
\captionsetup[figure]{labelformat=empty}%
\begin{minipage}[c]{.2\textwidth}
  \centering

\begin{center}
\begin{math}
\begin{array}{ll}
      \text{H}_0: & \mu_\text{A}=\mu_\text{B}\\[0.5em]
      \text{H}_1: & \mu_\text{A}\ne\mu_\text{B}
    \end{array}
\end{math}
\end{center}

\end{minipage}%
\begin{minipage}[c]{.1\textwidth}
  \centering
  \qquad \qquad
\end{minipage}%
  \centering
\begin{minipage}[c]{.7\textwidth}
  \centering

\begin{center}
\begin{tikzpicture}

\draw[semithick] (10,0) -- (0,0) node[left] {\textit{Brand A}};
\foreach \x in {0.5,2,...,9.5}
\draw[semithick] (\x,0) -- (\x,-0.1);
\foreach \x in {900,1000,...,1200}
\node at (0.03*\x-26.5,-0.3) {\x};
\draw[semithick,dashed] (0.03*1010-26.5,0) -- (0.03*1010-26.5,1.2);
\node at (0.03*1010-26.5,1.4) {$\bar{x}_\text{A}$};

\draw[fill=black!25] (0.03*925-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*960-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1020-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1105-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1130-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*905-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1030-26.5,0.5) circle (3pt);
\draw[fill=black!25] (0.03*1045-26.5,0.5) circle (3pt);

\draw[semithick] (10,-2) -- (0,-2) node[left] {\textit{Brand B}};
\foreach \x in {0.5,2,...,9.5}
\draw[semithick] (\x,-2) -- (\x,-2.1);
\foreach \x in {900,1000,...,1200}
\node at (0.03*\x-26.5,-2.3) {\x};
\draw[semithick,dashed] (0.03*1059-26.5,-2) -- (0.03*1059-26.5,-0.8);
\node at (0.03*1059-26.5,-0.6) {$\bar{x}_\text{B}$};

\draw[fill=black!25] (0.03*950-26.5,-1.5) circle (3pt);
\draw[fill=black!25] (0.03*970-26.5,-1.5) circle (3pt);
\draw[fill=black!25] (0.03*995-26.5,-1.5) circle (3pt);
\draw[fill=black!25] (0.03*1045-26.5,-1.5) circle (3pt);
\draw[fill=black!25] (0.03*1070-26.5,-1.5) circle (3pt);
\draw[fill=black!25] (0.03*1095-26.5,-1.5) circle (3pt);
\draw[fill=black!25] (0.03*1155-26.5,-1.5) circle (3pt);
\draw[fill=black!25] (0.03*1190-26.5,-1.5) circle (3pt);


\end{tikzpicture}
\end{center}

\end{minipage}
\end{figure}

Such a test, comparing the parameters of *two* populations by using *two samples*, requires a **two-sample test**.  Either one-tailed or two-tailed tests can be performed:

\begin{center}
    \begin{tabular}{ccccc}
        $\text{H}_0:\mu_\text{A}=\mu_\text{B}$ & \qquad \qquad & $\text{H}_0:\mu_\text{A} = \mu_\text{B}$ & \qquad \qquad & $\text{H}_0:\mu_\text{A}=\mu_\text{B}$\\
        $\text{H}_1:\mu_\text{A} \ne \mu_\text{B}$ & & $\text{H}_1:\mu_\text{A}>\mu_\text{B}$ & & $\text{H}_1:\mu_\text{A}<\mu_\text{B}$ 
    \end{tabular}
\end{center}

Within calculations and hypotheses, populations can be numbered (e.g. $\mu_1$ and $\mu_2$), given letters (e.g. $\mu_\text{A}$ and $\mu_\text{B}$), or named with words to aid readability (e.g. $\mu_\text{cat}$ and $\mu_\text{dog}$).

\pagebreak

## Two-Sample \textit{z}-test for Population Means

If **independent** random samples of sizes $n_1$ and $n_2$ are obtained from each of two normally distributed populations which have population means $\mu_1$ and $\mu_2$ respectively, and population standard deviations $\sigma_1$ and $\sigma_2$ respectively, then the difference in sample means $\bar{X}_1$ and $\bar{X}_2$ is also normally distributed, as below:

\[\overline{X}_1\sim \text{N}\left(\mu_1,\frac{\sigma_1^2}{n_1}\right) \quad \text{and} \quad \overline{X}_2\sim \text{N}\left(\mu_2,\frac{\sigma_2^2}{n_2}\right)\quad\implies\quad\overline{X}_1-\overline{X}_2\sim \text{N}\left(\mu_1-\mu_2,\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}\right)\]

This leads to the test statistic for the *two-sample* $z$*-test for population means* given in the data booklet. Under the typical null hypothesis of no difference between the population means, or $\mu_1-\mu_2=0$, the test statistic in the box may be used. From the Data Booklet:

\vspace{-0.2cm}

\begin{multicols}{2}

\[Z\sim\dfrac{(\overline{X}_1-\overline{X}_2)-(\mu_1-\mu_2)}{\sqrt{\dfrac{\sigma_1^2}{n_1}+\dfrac{\sigma_2^2}{n_2}}}\]

\vfill\null
\columnbreak

\begin{centering}
\begin{tcolorbox}[adjusted title=For a two-sample $z$-test for means:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
Test statistic: $z=\dfrac{\overline{x}_1-\overline{x}_2}{\sqrt{\dfrac{\sigma_1^2}{n_1}+\dfrac{\sigma_2^2}{n_2}}}$
\end{tcolorbox}
\end{centering}

\end{multicols}

\vspace{-0.4cm}

\begin{centering}
\tcbset{width=14cm}
\begin{tcolorbox}[adjusted title=Conditions for valid use of the two-sample $z$-test for population means:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\begin{itemize}
    \item The \textit{populations} are \textbf{normally distributed}.
    \item The \textit{population standard deviations}, $\sigma_1$ and $\sigma_2$, are \textbf{known}.
    \item The data was obtained through \textbf{random} and \textbf{independent samples}.
\end{itemize}
\end{tcolorbox}
\end{centering}

Note that when sample sizes $n_1$ and $n_2$ are greater than 20 the *Central Limit Theorem*, can be invoked. For large sample sizes, the sample standard deviations $s_1$ and $s_2$ may be used as estimates of $\sigma_1$ and $\sigma_2$, allowing an approximate $z$-test to be performed.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} To compare the battery life of two brands' mobile phones, a random sample of nine phones from \textit{Apfel} and seven phones from \textit{Ubhal} are tested. The sample of Apfel phones had a mean battery life of 34 hours, with a mean battery life of 36 hours for Ubhal. Assuming that the battery life for both populations of phones is known to be normally distributed, with a standard deviation of 3.5 hours, use a parametric test to determine whether there is evidence for a difference in battery life between the brands.

\tcblower
\textbf{Solution:}
$\bar{x}_\text{apfel}=34$, $\bar{x}_\text{ubhal}=36$, $\sigma_\text{apfel}=3.5$, $\sigma_{\text{ubhal}}=3.5$, $n_\text{apfel}=9$, $n_{\text{ubhal}}=7$\\[0.1em]

\begin{math}
\begin{array}{ll}
      H_0: & \mu_\text{apfel}=\mu_\text{ubhal}\\
      H_1: & \mu_\text{apfel}\ne \mu_\text{ubhal}
    \end{array}
\end{math}

\vspace{0.5cm}

Test statistic: $z=\dfrac{34-36}{\sqrt{\dfrac{3.5^2}{9}+\dfrac{3.5^2}{7}}}=-1.13$
\hspace{4cm}
\begin{tikzpicture}[overlay]
\begin{axis}[
  no markers, 
  domain=-3:3, 
  samples=100,
  ymin=0,
  axis lines*=left, 
  every axis y label/.style={at=(current axis.above origin),anchor=south},
  every axis x label/.style={at=(current axis.right of origin),anchor=west},
  height=3cm, 
  width=6.5cm,
  xtick=\empty, 
  ytick=\empty,
  enlargelimits=false, 
  clip=false, 
  axis on top,
  grid = major,
  hide y axis
  ]
\addplot [draw=none, fill=black!50, domain=-3:-1.96] {gauss(x, 0, 1)} \closedcycle;
\addplot [draw=none, fill=black!50, domain=1.96:3] {gauss(x, 0, 1)} \closedcycle;
 \addplot [semithick] {gauss(x, 0, 1)};
\pgfmathsetmacro\valueA{gauss(-1.96,0,1)}
\pgfmathsetmacro\valueB{gauss(0,0,1)}
\pgfmathsetmacro\valueC{gauss(1.96,0,1)}
\draw [semithick, black]  (axis cs:-1.96,0) -- (axis cs:-1.96,\valueA);
\draw [semithick, black]  (axis cs:1.96,0) -- (axis cs:1.96,\valueC);
\node[below] at (axis cs: 0,0)  {$0$}; 
\node[below] at (axis cs: -1.96, 0) {$-1.96$};
\node[above] at (axis cs: -2.4,\valueA) {2.5\%};
\node[below] at (axis cs: 1.96, 0) {$1.96$};
\node[above] at (axis cs: 2.4,\valueC) {2.5\%};
\node[above] at (axis cs: 0,\valueB)  {$z$};
\draw[very thick] (axis cs: -1.13,0) -- (axis cs: -1.13,0.44) node[above] {$-1.13$};
\end{axis}
\end{tikzpicture}\\[0.1em]

Critical value: $z=-1.96$\\

Since $-1.13>-1.96$, do not reject $\text{H}_0$ at the 5\% level of significance. There is insufficient evidence to suggest a difference in the mean battery life of the two brands' mobile phones.

\end{tcolorbox}

\pagebreak

[]{#ex151q}

#### [Exercise 15.1](#ex151a) {-}

\begin{enumerate}
    \item A two-sample $z$-test for a difference in population means is to be carried out based on two independent random samples of data taken from normally distributed populations (A and B). The sample mean for A is 87 based on a sample size of 11, whilst the sample mean for B is 92 based on a sample size of 13. Populations A and B have standard deviations 7 and 5 respectively.
    \begin{enumerate}
        \item State suitable null and alternative hypotheses.
        \item Show the calculation required to obtain a test statistic of $z=-1.98$.
        \item Conclude the test at the 5\% level of significance.
    \end{enumerate}
    \item The population standard deviations of customer spend between two supermarkets, \textit{The Food Maze} and \textit{Thyme to Shop}, have been previously recorded as £9.50 and £13 respectively. Recent random samples of 21 The Food Maze customers and 7 Thyme to Shop customers produced sample mean customer spends of £34.80 and £42.13 respectively. Stating an assumption required, perform a parametric test to assess whether the data supports a claim that customers at Thyme to Shop spend more on average than those at The Food Maze.
    \item The fuel efficiency in miles per gallon (mpg) is being studied by a car manufacturer for two of their hybrid car models, the \textit{Ugo} and the \textit{Theiris}. Across a month, a randomly selected employee each day drives one of the models from Dundee to Aberdeen and back. It has been previously recorded that the standard deviation of fuel efficiency for similar models of hybrid cars driving the same route is 2.7 mpg. The results from these journeys are shown below:
    \vspace{-0.2cm}
    \begin{center}
        \begin{tabular}{|c|c|c|}
            \hline
            Model name & Ugo & Theiris \\
            \hline
            Sample mean & 52 & 55 \\
            \hline
            Sample size & 16 & 14 \\
            \hline
        \end{tabular}
    \end{center}
    It is assumed that the population standard deviation in fuel efficiency is 2.7 mpg for both models.
    \begin{enumerate}
        \item State a further assumption required for the use of a two-sample $z$-test of a difference in mean fuel efficiency between the two models.
        \item Perform a two-sample $z$-test at the 10\% level of significance.
    \end{enumerate}
    \item A restaurant chain has a branch in Edinburgh and a branch in Glasgow. Waiting times for food are known to be normally distributed for both branches, with standard deviations previously known to be 4 minutes for the Edinburgh branch and 3 minutes for the Glasgow branch.\\[0.5em] This year, waiting times were recorded for random samples of 17 tables at the Edinburgh branch, giving a mean of 23 minutes, and 19 tables at the Glasgow branch, giving a mean of 21 minutes.\\[0.5em] Perform a parametric test to assess whether the data provides evidence to suggest that there is a difference in mean waiting times for food between the two branches, at the 5\% level of significance.
    \item Researchers studying the effects of evening screen time on sleep quality for teenagers gather two random samples: one of teenagers who use their mobile phone in the hour leading up to the time they go to bed, and one of teenagers who do not. Fitness trackers are used to measure the quality of their sleep, giving a score from 0 (very poor) to 10 (excellent). The results are as follows:
    \begin{center}
        \begin{tabular}{|l|c|c|}
            \hline
            Group & Phone use & No phone use\\
            \hline
            Sample mean & 7.9 & 8.4\\
            \hline
            Sample standard deviation & 0.7 & 0.4 \\
            \hline
            Sample size & 34 & 41\\
            \hline
        \end{tabular}
    \end{center}
    It is assumed that the sample size is sufficiently large that the sample standard deviations in sleep quality score are reliable estimates for the population standard deviations.
    \begin{enumerate}
        \item Explain, with reference to the sample sizes, why the researchers do not need to assume that sleep quality scores in the populations are normally distributed.
        \item Conduct a $z$-test to assess, at the 1\% level of significance, whether the data supports a claim that screen use in the evening has a negative impact on sleep quality amongst teenagers.
    \end{enumerate}
\end{enumerate}

\pagebreak

## Two-Sample \textit{z}-test for Population Proportions

If random, independent samples of data are obtained from each of two populations, and the two \textbf{sample proportions} $\hat{p}_1$ and $\hat{p}_2$ are obtained, then a *two-sample* $z$*-test for population proportions* may be used to explore evidence for a difference in the \textbf{population proportions}, $p_1$ and $p_2$.  

The test statistic, provided in the Data Booklet, uses an *estimate of the pooled population proportion*, $\hat{p}$:

\begin{centering}
\tcbset{width=13cm}
\begin{tcolorbox}[adjusted title=For a two-sample $z$-test for population proportions:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
Test statistic: $z=\dfrac{\hat{p}_1-\hat{p}_2}{\sqrt{\hat{p} \hat{q} \left( \dfrac{1}{n_1}+ \dfrac{1}{n_2}\right)}}$ \qquad where \qquad $\hat{p}=\dfrac{n_1\hat{p}_1+n_2\hat{p}_2}{n_1+n_2}$
\end{tcolorbox}
\end{centering}

The test statistic may be derived from the use of the normal approximation to a binomial distribution to describe the approximate distribution of the sample proportion (see section 10.5) and the distribution of the difference of two *independent* sample proportions (similar to section 15.1). The conditions required for the use of this hypothesis test follow.

\begin{centering}
\tcbset{width=14cm}
\begin{tcolorbox}[adjusted title=Conditions for valid use of the two-sample $z$-test for population proportions:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\begin{itemize}
    \item Each of $n_1 \hat{p}_1,n_1 \hat{q}_1,n_2 \hat{p}_2$ and $n_2 \hat{q}_2$ must be \textbf{greater than 5}.
    \item The data was obtained through \textbf{random} and \textbf{independent samples}.
\end{itemize}
\end{tcolorbox}
\end{centering}

This parametric test can take one-tailed or two-tailed hypotheses which relate to the population proportions, $p_1$ and $p_2$:

\vspace{-0.5cm}

\begin{center}
    \begin{tabular}{ccccc}
        $\text{H}_0:p_1=p_2$ & \qquad \qquad & $\text{H}_0:p_1 = p_2$ & \qquad \qquad & $\text{H}_0:p_1=p_2$\\
        $\text{H}_1:p_1 \ne p_2$ & & $\text{H}_1:p_1>p_2$ & & $\text{H}_1:p_1<p_2$ 
    \end{tabular}
\end{center}

\vspace{-0.1cm}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Tyre pressures were checked for a random sample of 80 cars parked on streets in a town centre, and 15\% were found to have at least one tyre with low pressure. For another sample of 75 vans in the town, 8\% were found to have at least one tyre with low pressure. Perform a two-sample $z$-test for proportions, at the 1\% level of significance, to assess whether there is a difference in the proportions of cars and vans that have at least one tyre with low pressure.

\tcblower
\textbf{Solution:}
$\hat{p}_\text{car}=0.15$, $\hat{p}_\text{van}=0.08$, $n_\text{car}=80$, $n_\text{van}=75$\\[0.1em]

\begin{math}
\begin{array}{ll}
      H_0: & p_\text{car}=p_\text{van}\\
      H_1: & p_\text{car} \ne p_\text{van}
    \end{array}
\end{math}

\vspace{0.1cm}

Estimate of pooled population proportion: $\hat{p}=\dfrac{80\times 0.15+75\times 0.08}{80+75}=0.116$ (to 3dp)

\vspace{0.5cm}

Test statistic: $z=\dfrac{0.15-0.08}{\sqrt{0.116 \times 0.884 \left( \dfrac{1}{80}+ \dfrac{1}{75}\right)}}=1.36$\\

Critical value: $z=2.58$\hspace{6cm}
\begin{tikzpicture}[overlay]
\begin{axis}[
  no markers, 
  domain=-3:3, 
  samples=100,
  ymin=0,
  axis lines*=left, 
  every axis y label/.style={at=(current axis.above origin),anchor=south},
  every axis x label/.style={at=(current axis.right of origin),anchor=west},
  height=3cm, 
  width=6.5cm,
  xtick=\empty, 
  ytick=\empty,
  enlargelimits=false, 
  clip=false, 
  axis on top,
  grid = major,
  hide y axis
  ]
\addplot [draw=none, fill=black!50, domain=2.58:3] {gauss(x, 0, 1)} \closedcycle;
\addplot [draw=none, fill=black!50, domain=-3:-2.58] {gauss(x, 0, 1)} \closedcycle;
 \addplot [semithick] {gauss(x, 0, 1)};
\pgfmathsetmacro\valueA{gauss(2.58,0,1)}
\pgfmathsetmacro\valueB{gauss(0,0,1)}
\draw [semithick, black]  (axis cs:2.58,0) -- (axis cs:2.58,\valueA);
\draw [semithick, black]  (axis cs:-2.58,0) -- (axis cs:-2.58,\valueA);
\node[below] at (axis cs: 0,0)  {$0$};
\node[above] at (axis cs: 0,\valueB)  {$z$};
\node[below] at (axis cs: 2.58, 0) {$2.58$};
\node[above] at (axis cs: 2.9,\valueA) {0.5\%};
\node[below] at (axis cs: -2.58, 0) {$-2.58$};
\node[above] at (axis cs: -2.9,\valueA) {0.5\%};
\draw[very thick] (axis cs: 1.36,0) -- (axis cs: 1.36,0.44) node[above] {$1.36$};
\end{axis}
\end{tikzpicture}\\

Since $1.36<2.58$, do not reject $\text{H}_0$ at the 1\% level of significance. There is insufficient evidence to suggest that the proportions of vans and cars with at least one tyre with low pressure parked in the town centre are different.

\end{tcolorbox}

\pagebreak

[]{#ex152q}

#### [Exercise 15.2](#ex152a) {-}

\begin{enumerate}
    \item Two publishing companies' Maths textbooks are known to contain occasional errors in the printed answers. Students randomly select questions from Brand A's textbook and from Brand B's textbook, checking the numbers of correct and incorrect answers for each sample. The results are:
    \begin{center}
        \begin{tabular}{|c|c|c|}
            \hline
            Textbook & Brand A & Brand B\\
            \hline
            Correct & 58 & 43\\
            \hline
            Incorrect & 7 & 9\\
            \hline
        \end{tabular}
    \end{center}
    Test at the 5\% significance level the hypothesis that the Brand B's printed answers contain a higher proportion of incorrect answers.
    \item An online travel magazine is investigating whether the younger or older holidaymakers are more likely to read books whilst on holiday. Random samples of those holidaymakers aged under 40 and those aged over 40 are selected and asked whether they read books whilst on holiday. The results are:
    \vspace{-0.2cm}
    \begin{center}
        \begin{itemize}
            \item 27 of the 66 younger holidaymakers read on holiday.
            \item 34 of the 59 older holidaymakers read on holiday.
        \end{itemize}
    \end{center}
    \vspace{-0.2cm}
    Perform a parametric hypothesis test at the 5\% significance level to assess the hypothesis that there is a difference in the proportion of holidaymakers from each age group who read books whilst on holiday. 
    \item Out of a random sample of 60 customers using the \textit{North East Train Service}, 42 rated their experience as positive, whilst 37 out of a random sample of 50 customers using the \textit{South West Intercity Metro} service rated their experience as positive. Use a parametric test, at the 10\% level of significance, to assess whether the data provides evidence of a difference between the two train services in the proportion of customers rating their experience as positive.
    \item In a random sample of 140 customers in an airport branch of a coffee chain, 52 used a loyalty card. In a random sample of 153 customers in a city centre branch of a coffee chain, 68 used a loyalty card. 
    \begin{enumerate}
        \item Show that the data meets the conditions required for the valid use of a $z$-test.
        \item Perform a $z$-test to determine whether there is evidence of a difference in the proportion of people using a loyalty card between the airport and the city centre branches.
    \end{enumerate}
    \item A recent survey of people living in Dollar showed that in a sample of 80 people, 35\% had visited Islay. In another sample of 70 people living in Dollar, 20\% had visited Orkney. Test at the 5\% significance level the hypothesis that a higher proportion of people from Dollar have visited Islay than Orkney, stating two assumptions required.
    \item An extensive study of two species of trees (one \textit{native} and one \textit{non-native}) commonly found in the Cairngorm National Park recorded the numbers of randomly selected trees from each species observed to be affected by a common disease. The aim of the study was to investigate whether the non-native species was more likely to be affected by the disease than the native species. For the native species, 35 out of 351 trees were observed to be affected, whilst 46 out of 289 non-native trees were affected. The results of a two-sample $z$-test for a difference in population proportions are shown below:\\[0.3em]
    \texttt{two sample z-test for equality of proportions}\\[0.2em]
    \texttt{data: prop1: native, prop2: nonnative}\\[0.2em]
    \texttt{alternative hypothesis: nonnative - native is greater than zero}\\[0.2em]
    \texttt{z = 2.13}\qquad \qquad \texttt{p-value = 0.0165}\\[0.2em]
    \texttt{sample estimates: prop native = 0.0997, prop nonnative = ****}\\[-0.8em]
    \begin{enumerate}
        \item Find the value missing from the output, marked as \texttt{****}.
        \item State suitable hypotheses for the test.
        \item Show the calculations required to obtain the test statistic shown.
        \item Suggest a suitable conclusion to the test, at the 5\% level of significance, using the $p$-value given.
    \end{enumerate}
\end{enumerate}

\pagebreak

## Two-Sample \textit{t}-test for Population Means

If random, independent samples of data are obtained from each of two *normally distributed* populations with **unknown population standard deviations**, then a *two-sample* $t$*-test for population means* may be used to explore evidence for a difference in the \textbf{population means}, $\mu_1$ and $\mu_2$, using the **sample standard deviations**.

\begin{centering}
\tcbset{width=13cm}
\begin{tcolorbox}[adjusted title=Conditions for valid use of the two-sample $t$-test for population means:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\begin{itemize}
    \item The \textit{populations} are \textbf{normally distributed}.
    \item The populations are assumed to have \textbf{equal variance}.
    \item The data was obtained through \textbf{random} and \textbf{independent samples}.
\end{itemize}
\end{tcolorbox}
\end{centering}

The test statistic is provided in the Data Booklet, and follows a $t$-distribution with $\nu=n_1+n_2-2$ degrees of freedom. It requires calculation of a *pooled estimate of the variance*, $s^2$, and as with the two-sample $z$-test, a more streamlined version of the test statistic under a null hypothesis of $\mu_1=\mu_2$ is as follows:

\begin{centering}
\tcbset{width=15.5cm}
\begin{tcolorbox}[adjusted title=For a two-sample $t$-test for population means:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
Test statistic: $t=\dfrac{\bar{x}_1-\bar{x}_2}{s\sqrt{\dfrac{1}{n_1}+ \dfrac{1}{n_2}}}$ \qquad where \qquad $s^2=\dfrac{(n_1-1)s_1^2+(n_2-1)s_2^2}{n_1+n_2-2}$

\vspace{-0.2cm}
\hspace{6.5cm}
with $\nu=n_1+n_2-2$ degrees of freedom
\vspace{0.1cm}
\end{tcolorbox}
\end{centering}

While $t$-tests are especially valuable when dealing with small sample sizes, they remain the statistically *correct* test to use even when dealing with very large samples. Modern computing power reduces the need to switch to a $z$-test for very large samples where critical values for the $t$-distribution may not have been so easily obtained.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} The time taken for runners to complete 5km at each \textit{Parkrun} location is known to be normally distributed. For a random sample of 8 runners at Dundee Parkrun the sample mean 5km time was 30.1 minutes, with a sample standard deviation of 3 minutes. At the Perth Parkrun the sample mean 5km time for 7 runners was 28.6 minutes, with a sample standard deviation of 2 minutes. Perform a $t$-test at the 10\% level of significance to investigate whether the data suggests there is a difference in mean 5km running times between the two Parkrun locations.

\tcblower
\textbf{Solution:}
$\bar{x}_\text{Dundee}=30.1$, $\bar{x}_\text{Perth}=28.6$, $s_\text{Dundee}=3$, $s_\text{Perth}=2$, $n_{\text{Dundee}}=8$, $n_{\text{Perth}}=7$\\[0.1em]

\begin{math}
\begin{array}{ll}
      H_0: & \mu_\text{Dundee}=\mu_\text{Perth}\\
      H_1: & \mu_\text{Dundee} \ne \mu_\text{Perth}
    \end{array}
\end{math}

\vspace{0.5cm}

Estimate of pooled variance: $s^2=\dfrac{(8-1)\times 3^2+(7-1)\times 2^2}{8+7-2}=6.692$\\[0.1em]

$s=\sqrt{6.692}=2.587$

\vspace{0.5cm}

Test statistic: $t=\dfrac{30.1-28.6}{2.587 \times \sqrt{\dfrac{1}{8}+ \dfrac{1}{7}}}=1.120$\\

Critical value: $t=1.771$\hspace{6cm}
\begin{tikzpicture}[overlay]
\begin{axis}[
  no markers, 
  domain=-3:3, 
  samples=100,
  ymin=0,
  axis lines*=left, 
  every axis y label/.style={at=(current axis.above origin),anchor=south},
  every axis x label/.style={at=(current axis.right of origin),anchor=west},
  height=3cm, 
  width=6.5cm,
  xtick=\empty, 
  ytick=\empty,
  enlargelimits=false, 
  clip=false, 
  axis on top,
  grid = major,
  hide y axis,
  hide x axis
  ]
\addplot [draw=none, fill=black!50, domain=-3:-1.771] {gauss(x, 0, 1)} \closedcycle;
\addplot [draw=none, fill=black!50, domain=1.771:3] {gauss(x, 0, 1)} \closedcycle;
\fill[black!50] (axis cs: -3,-0.02) rectangle (axis cs: -1.771,0);
\fill[black!50] (axis cs: 1.771,-0.02) rectangle (axis cs: 3,0);
 \addplot [semithick] {gauss(x, 0, 1)};
\pgfmathsetmacro\valueA{gauss(-1.771,0,1)}
\pgfmathsetmacro\valueB{gauss(0,0,1)}
\draw [semithick, black]  (axis cs:-1.771,-0.02) -- (axis cs:-1.771,\valueA);
\draw [semithick, black]  (axis cs:1.771,-0.02) -- (axis cs:1.771,\valueA);
\node[below] at (axis cs: 0,-0.02)  {$0$};
\node[above] at (axis cs: 0,\valueB)  {$t_{13}$};
\node[below] at (axis cs: -1.771, -0.02) {$-1.771$};
\node[above] at (axis cs: -2.2,\valueA) {5\%};
\node[below] at (axis cs: 1.771, -0.02) {$1.771$};
\node[above] at (axis cs: 2.2,\valueA) {5\%};
\draw[very thick] (axis cs: 1.120,-0.02) -- (axis cs: 1.120,0.44) node[above] {$1.120$};
\draw (axis cs: -3,-0.02) -- (axis cs: 3,-0.02);
\end{axis}
\end{tikzpicture}\\[0.5em]

Since $1.120<1.771$, do not reject $\text{H}_0$ at the 10\% level of significance. There is insufficient evidence to suggest a difference in the mean 5km running times between the two locations.

\end{tcolorbox}


\pagebreak

[]{#ex153q}

#### [Exercise 15.3](#ex153a) {-}

\begin{enumerate}
    \item A two-sample $t$-test for a difference in population means is to be carried out based on two independent random samples of data taken from normally distributed populations (A and B), which are assumed to have equal variances. A sample of 11 observations from A produces a mean of 87 and a standard deviation of 8, whilst a sample of 13 observations from B produces a mean of 92 and a standard deviation of 5.
    \begin{enumerate}
        \item State suitable null and alternative hypotheses.
        \item Show the calculation required to obtain a test statistic of $t=-1.072$.
        \item Conclude the test at the 5\% level of significance.
    \end{enumerate}
    \item A motorist and keen statistician tosses a coin before each of a series of drives to determine whether to use her car's air conditioning or not. The fuel efficiency (in miles per gallon) for those drives are:
    \begin{center}
        \begin{tabular}{l|ccccccc}
        With air conditioning (mpg) & 47 & 48 & 51 & 52 & 52 & 53 & 55\\
        \hline
        Without air conditioning (mpg) & 49 & 50 & 52 & 54 & 55 & 55 &
        \end{tabular}
    \end{center}
    Assume that fuel efficiency is normally distributed for each population (with air conditioning and without), and that the population variances are equal. Perform a parametric test to determine whether the data supports her belief that fuel efficiency is higher when driving without air conditioning, at the 5\% level of significance.
    \item The contents of a random sample of six bags of coffee beans sold by \textit{Brewhemian Rhapsody} were measured. The results, in grams, were:
      \begin{center}
      \begin{tabular}{cccccc}
      254 & 255 & 254 & 248 & 256 & 251
      \end{tabular}
      \end{center}
      The results for a random sample of eight bags sold by \textit{The Bean Supremacy} were:
      \begin{center}
      \begin{tabular}{cccccccc}
      240 & 249 & 244 & 246 & 245 & 250 & 240 & 253
      \end{tabular}
      \end{center}
      It is assumed that the mass of coffee in a bag is normally distributed, for each population. Use a parametric test to assess the evidence that the \textit{Brewhemian Rhapsody} bags contain more coffee, stating one further assumption required.
      \item A medical trial wishes to compare the effectiveness of two new types of mild painkiller. Twenty volunteers are selected and randomly assigned either painkiller A or painkiller B, and an effectiveness score from 0 to 5 is obtained for each person through an industry-recognised pain tolerance test using ice-cold water. Computer output of summary statistics for the samples are shown below:
      \begin{center}
          \begin{tabular}{llll}
            \texttt{data} & \texttt{sample mean} & \texttt{sample sd} & \texttt{n}\\
            \texttt{painkiller A} & \texttt{1.95} & \texttt{0.54} & \texttt{10}\\
            \texttt{painkiller B} & \texttt{2.75} & \texttt{0.74} & \texttt{10}
          \end{tabular}
      \end{center}
    Perform a $t$-test at the 2\% level to assess whether there is evidence of a difference between the effectiveness of the two painkillers, stating two assumptions required.
    \item Times taken to run 5km for a random sample of 7 hockey players and a random sample of 5 rugby players are recorded. The table below gives the results, to the nearest minute:

\begin{center}
    \begin{tikzpicture}
        \draw (-7.6,0) -- (-0.9,0);
        \draw (-6,-0.6) -- (-6,0.6);
        \node[left] at (-6,0.3) {Hockey};
        \node[left] at (-6,-0.3) {Rugby};
        \foreach \x in {0,0.5,...,7.5}{
        \draw (\x,0.1) -- (\x,-0.1);
        }
        \node at (0,-0.3) {18};
        \node at (7.5,0.3) {33};
        \node at (-5.5,0.3) {18};
        \node at (-4.8,0.3) {19};
        \node at (-4.1,0.3) {20};
        \node at (-3.4,0.3) {22};
        \node at (-2.7,0.3) {23};
        \node at (-2,0.3) {24};
        \node at (-1.3,0.3) {27};
        \node at (-5.5,-0.3) {23};
        \node at (-4.8,-0.3) {28};
        \node at (-4.1,-0.3) {29};
        \node at (-3.4,-0.3) {30};
        \node at (-2.7,-0.3) {33};
        \draw (0,0) -- (7.5,0);
        \draw[fill=black!20] (0,0.4) circle (2pt);
        \draw[fill=black!20] (0.5,0.4) circle (2pt);
        \draw[fill=black!20] (1,0.4) circle (2pt);
        \draw[fill=black!20] (2,0.4) circle (2pt);
        \draw[fill=black!20] (2.5,0.4) circle (2pt);
        \draw[fill=black!20] (3,0.4) circle (2pt);
        \draw[fill=black!20] (4.5,0.4) circle (2pt);
        \draw[fill=black!50] (2.5,-0.4) circle (2pt);
        \draw[fill=black!50] (5,-0.4) circle (2pt);
        \draw[fill=black!50] (5.5,-0.4) circle (2pt);
        \draw[fill=black!50] (6,-0.4) circle (2pt);
        \draw[fill=black!50] (7.5,-0.4) circle (2pt);
    \end{tikzpicture}
\end{center}
Assume that the time taken to run 5km is normally distributed for both the hockey and rugby players, and that the population variances in 5km time are equal. Perform a parametric test to assess the data for evidence of a difference in the mean time taken for hockey and rugby players to run 5km.
\end{enumerate}

\pagebreak

## Paired \textit{t}-test for the Population Mean Difference

If six randomly selected athletes have their 100 metre sprint times recorded, and then repeat the sprint a month later after some training, the two datasets (*time before* and *time after*) are *not independent*. Instead, each value from the first dataset pairs with a value from the second dataset; this is called *paired data*. The previous two-sample tests in this chapter would be inappropriate, since they require independent samples. 

Instead, a sample of *differences*, $d_i$, for each pair should be calculated and the mean of the differences (also known as the *mean difference*) assessed using a *paired* $t$*-test*. Possible hypotheses would then relate to the population mean difference, $\mu_d$:

\vspace{-0.4cm}
\begin{center}
    \begin{tabular}{ccccc}
        $\text{H}_0:\mu_d=0$ & \qquad \qquad & $\text{H}_0:\mu_d=0$ & \qquad \qquad & $\text{H}_0:\mu_d=0$\\
        $\text{H}_1:\mu_d \ne 0$ & & $\text{H}_1:\mu_d>0$ & & $\text{H}_1:\mu_d<0$ 
    \end{tabular}
\end{center}

\vspace{-0.2cm}

The test statistic derives from the one-sample $t$-test covered in Chapter 10, with $\bar{d}$ (or $\bar{x}_d$) representing the sample mean difference and  $s_d$ the sample standard deviation in differences. The degrees of freedom are calculated based on the single sample of differences, as $\nu=n-1$.

\begin{figure}[H]
  \centering
\begin{minipage}[c]{.33\textwidth}
  \centering
\begin{centering}
\tcbset{width=6cm,height=2.7cm}
\begin{tcolorbox}[adjusted title=For a paired $t$-test:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
Test statistic: $t=\dfrac{\bar{x}_d-\mu_d}{\dfrac{s_d}{\sqrt{n}}}$\\[-0.8em] with $\nu=n-1$ \phantom{blahblahbl}
\end{tcolorbox}
\end{centering}
\end{minipage}%
  \centering
\begin{minipage}[c]{.66\textwidth}
  \centering
\tcbset{width=11cm,height=2.7cm}
\begin{tcolorbox}[adjusted title=Conditions for valid use of a paired $t$-test:, halign title = center,colback=red!5,colframe=red!70!black, halign = center]
\begin{itemize}
    \item The \textit{population of differences} is \textbf{normally distributed}.
    \item The data was obtained through \textbf{random sampling}.
\end{itemize}
\end{tcolorbox}
\end{minipage}
\end{figure}

Careful attention must be given to how the sample of differences is defined, particularly for one-tailed hypotheses.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=RoyalBlue]
\textbf{Problem:} Six randomly selected teachers have their pulse rates (in beats per minute) checked in at 10am and then four hours later at 2pm.
\begin{center}
\begin{tabular}{l|cccccc}
      Pulse at 10am & 58 & 51 & 68 & 83 & 71 & 78\\
      \hline
      Pulse at 2pm & 65 & 57 & 63 & 98 & 71 & 82\\
\end{tabular}
\end{center}
Assuming that the sample of differences in pulse rate were independent, and that the population of differences is normally distributed, assess whether there is evidence that teachers' pulse rates are higher at 2pm than 10am, at the 5\% level of significance.
\tcblower
\textbf{Solution:}

\vspace{-0.9cm}

\begin{center}
\begin{tabular}{c|cccccc}
      Differences (2pm$-$10am) & 7 & 6 & -5 & 15 & 0 & 4
\end{tabular}
\end{center}

\vspace{-0.3cm}

$\bar{d}=4.5$, $s_d=6.775$, $n=6$\\[0.1em]

\begin{math}
\begin{array}{ll}
      H_0: & \mu_d=0\\
      H_1: & \mu_d > 0
    \end{array}
\end{math}

\vspace{0.3cm}

$\nu=6-1=5$

\vspace{0.3cm}

Test statistic: $t=\dfrac{4.5-0}{\dfrac{6.775}{\sqrt{6}}}=1.627$
\hspace{3cm}
\begin{tikzpicture}[overlay]
\begin{axis}[
  no markers, 
  domain=-3:3, 
  samples=100,
  ymin=0,
  axis lines*=left, 
  every axis y label/.style={at=(current axis.above origin),anchor=south},
  every axis x label/.style={at=(current axis.right of origin),anchor=west},
  height=3cm, 
  width=6.5cm,
  xtick=\empty, 
  ytick=\empty,
  enlargelimits=false, 
  clip=false, 
  axis on top,
  grid = major,
  hide y axis,
  hide x axis
  ]
\addplot [draw=none, fill=black!50, domain=2.015:3] {gauss(x, 0, 1)} \closedcycle;
 \addplot [semithick] {gauss(x, 0, 1)};
\pgfmathsetmacro\valueA{gauss(2.015,0,1)}
\pgfmathsetmacro\valueB{gauss(0,0,1)}
\draw [semithick, black]  (axis cs:2.015,-0.02) -- (axis cs:2.015,\valueA);
\fill[black!50] (axis cs: 2.015,-0.02) rectangle (axis cs: 3,0);
\node[below] at (axis cs: 0,-0.02)  {$0$};
\node[above] at (axis cs: 0,\valueB)  {$t_5$};
\node[below] at (axis cs: 2.015, -0.02) {$2.015$};
\node[above] at (axis cs: 2.9,\valueA) {5\%};
\draw[very thick] (axis cs: 1.627,-0.02) -- (axis cs: 1.627,0.44) node[above] {$1.627$};
\draw (axis cs: -3,-0.02) -- (axis cs: 3,-0.02);
\end{axis}
\end{tikzpicture}\\[0.1em]

Critical value: $t=2.015$\\

Since $1.627<2.015$, do not reject $\text{H}_0$ at the 5\% level of significance. There is insufficient evidence to suggest that teachers' pulse rates are higher at 2pm than 10am.

\end{tcolorbox}

\pagebreak

[]{#ex154q}

#### [Exercise 15.4](#ex154a) {-}

\begin{enumerate}
    \item A paired $t$-test for a population mean difference not equal to zero is to be carried out based on pairs of observations from a sample of six individuals. The population of differences is assumed to be normally distributed. The table below shows the results:
    \begin{center}
        \begin{tabular}{c|cccccc}
            \hline
              Individual & A & B & C & D & E & F\\
            \hline
              Observation 1 & 35 & 65 & 43 & 66 & 58 & 61\\
            \hline
              Observation 2 & 31 & 57 & 39 & 71 & 58 & 60\\
            \hline
        \end{tabular}
    \end{center}
    \begin{enumerate}
        \item State suitable null and alternative hypotheses.
        \item Show the calculation required to obtain a test statistic of $t=0.251$.
        \item Conclude the test at the 5\% level of significance.
    \end{enumerate}
    \item A school is studying whether a digital homework platform is helping pupils improve their times tables knowledge. Seven pupils are randomly selected to answer as many times tables questions correctly as they can in one minute. Six months later, after regular use of the homework platform, the same seven pupils try again to answer as many times tables questions correctly as they can in one minute. The results are:
    \begin{center}
        \begin{tabular}{c|ccccccc}
            \hline
              Pupil & 1 & 2 & 3 & 4 & 5 & 6 & 7\\
            \hline
              Before & 31 & 13 & 27 & 19 & 14 & 25 & 24\\
            \hline
              After & 42 & 15 & 26 & 19 & 18 & 22 & 26\\
            \hline
        \end{tabular}
    \end{center}
    Perform a $t$-test at the 10\% level of significance to assess whether the data suggests that there has been an improvement in the pupils' times tables ability.
    \item Eight amateur runners are selected to study the effects of consuming energy gels before running on runners' performances at middle-distances. Each has their finish time recorded for a 5000m run without consuming energy gels beforehand, then a month later their time is recorded again for a 5000m run before which each consumed two energy gels. The data is shown in the table below, with times recorded to the nearest minute.
    \begin{center}
        \begin{tabular}{c|cccccccc}
            \hline
              Runner & A & B & C & D & E & F & G & H\\
            \hline
              Without gels & 24 & 19 & 21 & 17 & 26 & 32 & 18 & 20\\
            \hline
              With gels  & 22 & 19 & 20 & 18 & 23 & 28 & 15 & 20\\
            \hline
        \end{tabular}
    \end{center}
    Perform a hypothesis test at the 5\% level of significance to assess whether consuming energy gels leads to a difference in running performance
    \item Seven red kites from a region's population have their masses measured using specially adapted feeding posts fitted with electronic scales. A year later, the masses of the same seven red kites are recorded, in kg. For each bird, the \textbf{differences} in mass between the first and second measurement are shown below.
    \begin{center}
    \begin{tabular}{cccccccc}
      differences in kg ($\text{second}-\text{first}$) & 0.3 & -0.2 & 0.4 & 0.0 & 0.1 & 0.2 & 0.1
    \end{tabular}
    \end{center}
    It is assumed that the population of differences in masses is normally distributed, and that the differences in mass for the sample are independent. A hypothesis test is conducted to assess the data for evidence of an increase in mass among the region's red kites:\\[0.5em]
    \texttt{paired t-test}\\
    \texttt{alternative hypothesis: true difference in means is greater than 0}\\
    \texttt{t = 1.722}\qquad \texttt{df=6} \qquad \texttt{p-value = 0.06798}\\
    \texttt{sample estimates:}\\
    \texttt{mean of differences = 0.1286}\qquad \texttt{standard deviation of differences = 0.1976}\\[1em]
    Show the calculation required to obtain the test statistic given, and give an appropriate conclusion to the test at the 10\% level of significance.
\end{enumerate}

\pagebreak

[]{#re15q}

## [Review Exercise](#re15a) {-}

\begin{enumerate}
    \item A commercial timber-selling company is concerned that the pine fence posts they are receiving from their new supplier have a lower density than those received from their old supplier. They measure the density (in kg/$\text{m}^3$) of a random sample of eight of the old fence posts and seven of the new fence posts. The results are:
    \begin{center}
        \begin{tabular}{lcccccccc}
            old & 563 & 576 & 534 & 580 & 556 & 519 & 540 & 548\\
            new & 550 & 571 & 527 & 506 & 524 & 549 & 571
        \end{tabular}
    \end{center}
    Perform a parametric hypothesis test at the 5\% level of significance to assess whether the company's concerns are supported by the data.
    \item A number of fifth year and sixth year pupils studying maths at a school were randomly selected from the school's register by a maths teacher and asked whether or not they had attended at least one support session during this academic year. The results are shown in the table below:
    \begin{center}
        \begin{tabular}{|c|c|c|}
            \hline
            Year & Fifth & Sixth\\
            \hline
            Attended at least one & 14 & 11 \\
            \hline
            Has not attended any & 17 & 16\\
            \hline
        \end{tabular}
    \end{center}
    \begin{enumerate}
        \item Show clearly that the data satisfies the conditions for the use of a $z$-test.
        \item Perform a $z$-test at the 1\% level of significance to assess whether there is evidence of a difference in the proportions of pupils who attend maths support sessions between the two year groups.
    \end{enumerate}
    \item A random sample of nine students from a sports science course completed a 10km course whilst wearing \textit{regular} running shoes. The same nine students then completed the same course again one week later, this time wearing \textit{carbon plates} running shoes. The results are shown below, rounded to the nearest tenth of a minute.
    \begin{center}
    \begin{tabular}{|c|c|c|c|c|c|c|c|c|c|}
      \hline
        Student & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\
      \hline
        Regular & 46.1 & 41.0 & 53.2 & 42.9 & 40.2 & 38.7 & 48.7 & 50.2 & 46.5\\
      \hline
        Carbon plate & 45.6 & 38.7 & 53.3 & 41.8 & 40.2 & 35.6 & 47.5 & 50.0 & 46.1\\
      \hline
    \end{tabular}
    \end{center}
    Assuming the population of differences in times to be normally distributed, test at the 5\% level of significance whether the data gives evidence to suggest \textit{carbon plate} running shoes improve 10km running times.
    \item Last year a road safety campaigner recorded the speeds of randomly selected cars as they drove past a sign in their village which displays the car's speed. This year, after the council claimed average speeds of cars through the village had decreased, the campaigner recorded the speeds of another random sample of cars. The results are shown in the table below, measured in miles per hour:
    \begin{center}
    \begin{tabular}{|c|c|}
      \hline
        Last year & This year\\
      \hline
        $\bar{x}_1=32.4$ & $\bar{x}_2=29.7$\\
      \hline
        $s_1=4.3$ & $s_2=1.3$\\
      \hline
        $n_1=29$ & $n_2=34$\\
      \hline
    \end{tabular}
    \end{center}
    Assume that the sample standard deviations in speed are reliable estimates of the population standard deviations.
    \begin{enumerate}
        \item Perform a $z$-test at the 10\% level of significance to determine whether the data provides evidence to suggest that the council's claim is valid.
        \item By considering the sample standard deviations, explain why a two-sample $t$-test may not be appropriate for this data.
    \end{enumerate}
\end{enumerate}

\pagebreak
