# Wilcoxon Signed Rank Test

The $z$ and $t$ hypothesis tests from chapters 10 and 15 which explore the *locations* of distributions have all focused on the *population mean*, $\mu$. Those *parametric* tests each rely on either normally distributed populations or sample sizes greater than $20$ such that the sample mean is approximately normally distributed.

Given small samples ($n<20$) from populations whose distributions may not be assumed to be normally distributed, a number of **non-parametric** tests may be used which instead explore the locations of distributions by considering the **population median**, $\eta$ (*'eta'*).

## Sign Test

The Sign Test is a simple non-parametric test that, whilst *not required for the Advanced Higher Statistics course*, helps to lay the groundwork for the tests covered later in this chapter. It uses a useful property of the population median, $\eta$, namely that $50\%$ of observations sampled from the population  can be expected to be greater than $\eta$ and $50\%$ can be expected to be less than $\eta$. This means that the number of observations on one side of the population median in a sample of size $n$ should follow a $B(n,0.5)$ distribution. For example, consider the following random sample of values ($n=12$) and a claim that the population median is less than $9$:

\begin{figure}[H]
  \centering
\captionsetup[figure]{labelformat=empty}%
\begin{minipage}[c]{.2\textwidth}
  \centering

\begin{center}
\begin{math}
\begin{array}{ll}
      \text{H}_0: & \eta=9\\[0.5em]
      \text{H}_1: & \eta<9
    \end{array}
\left]
    \begin{array}{l}
      \alpha=0.05\\
      \textnormal{One-tailed}
    \end{array}
  \right.
\end{math}
\end{center}

\end{minipage}%
\begin{minipage}[c]{.1\textwidth}
  \centering
  \qquad \qquad
\end{minipage}%
  \centering
\begin{minipage}[c]{.7\textwidth}
  \centering

\begin{center}
\begin{tikzpicture}

\draw[semithick] (2,0) -- (11,0);
\foreach \x in {2,2.5,...,11}
\draw[semithick] (\x,0) -- (\x,-0.1);
\foreach \x in {5,10,...,20}
\node at (0.5*\x,-0.3) {\x};
\draw[semithick,dashed] (4.5,0) -- (4.5,1);
\node at (4.5,1.4) {$\eta=9$};

\draw[fill=black!25] (7,0.5) circle (3pt);
\draw[fill=black!25] (8,0.5) circle (3pt);
\draw[fill=black!25] (8.5,0.5) circle (3pt);
\draw[fill=black!25] (9,0.5) circle (3pt);
\draw[fill=black!25] (9,0.85) circle (3pt);
\draw[fill=black!25] (9,1.2) circle (3pt);
\draw[fill=black!25] (10,0.5) circle (3pt);
\draw[fill=black!25] (10,0.85) circle (3pt);
\draw[fill=black!25] (4,0.5) circle (3pt);
\draw[fill=black!25] (3.5,0.5) circle (3pt);
\draw[fill=black!25] (3.5,0.85) circle (3pt);
\draw[fill=black!25] (3,0.5) circle (3pt);
    
\end{tikzpicture}
\end{center}

\end{minipage}
\end{figure}

With $4$ out of the $12$ observed values being less than $9$, the $p$-value for this test can be calculated as the probability of observing $4$ or fewer values less than $\eta=9$. Letting random variable $X$ represent the number of such values, which follows a $B(12,0.5)$ distribution under the null hypothesis:

\vspace{-0.3cm}

$$p\text{-value}=P(X\leqslant4)=0.1938$$

\vspace{0.1cm}

Since $0.1938>0.05$, do not reject $\text{H}_0$ at the $5\%$ level of significance. 

There is insufficient evidence to suggest that the population median is less than $9$.

\pagebreak

## Wilcoxon Signed Rank Test

Whilst the Sign Test is only concerned with the number of values that fall on either side of the hypothesised population median, $\eta$, the Wilcoxon Signed Rank test also considers how far from the median these values lie. More specifically, it applies weighting to the values by assigning *rank* $1$ to the value closest to $\eta$, *rank* $2$ to the second closest, and so on.

\textbf{Zeros:} Any values that are exactly equal to the median, $\eta$, are ignored and not given a rank, with the sample size $n$ reduced to reflect the number of *remaining values to be ranked*.

\textbf{Tied ranks:} Values that are equally distant from the median, $\eta$, share ranks. For example, if two values are equally far from $\eta$ when looking to assign rank $4$, then they are each ranked $4.5$, since $\frac{4+5}{2}=4.5$. If three values are equally distant from $\eta$ when assigning rank $7$, then they are each ranked $8$ since $\frac{7+8+9}{3}=8$.

\begin{itemize}
    \item Ranks of values greater than the median are denoted as \textit{positive ranks}, and their total as $W_{+}$.
    \item Ranks of values greater than the median are denoted as \textit{negative ranks}, and their total as $W_{-}$. 
\end{itemize}

Consider a random sample of nine values from a distribution with median $\eta=10$: \qquad $2,4,5,6,10,11,12,13,16$

\begin{center}
\begin{math}
\begin{array}{ll}
      \text{H}_0: & \eta=10\\[0.5em]
      \text{H}_1: & \eta\ne 10
    \end{array}
\left]
    \begin{array}{l}
      \alpha=0.05\\
      \textnormal{Two-tailed}
    \end{array}
  \right.
\end{math}
\end{center}

\begin{center}
\begin{tikzpicture}

\draw[semithick,-stealth] (2,-0.4) -- (18,-0.4);
\foreach \x in {2,3,...,18}
\draw[semithick] (\x,-0.4) -- (\x,-0.5) node[anchor=north] {\x};
\draw[semithick,dashed] (10,-0.4) -- (10,0.5);
\node at (10,0.8) {$\eta$};

\draw[fill=black!35] (11,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 1_{+}}$};
\draw[fill=black!35] (13,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 3_{+}}$};
\draw[fill=black!35] (6,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 4_{-}}$};
\draw[fill=black!35] (16,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 6.5_{+}}$};
\draw[fill=black!35] (2,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 8_{-}}$};
\draw[fill=black!35] (5,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 5_{-}}$};
\draw[fill=black!35] (12,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 2_{+}}$};
\draw[fill=black!35] (4,0) circle (2.5pt) node[anchor=south] {${\scriptstyle 6.5_{-}}$};
\draw[fill=black!75] (10,0) circle (2.5pt);

\node at (14,-1.6) {$W_+=12.5$};
\node at (6,-1.6) {$W_-=23.5$};

\end{tikzpicture}
\end{center}

Note that the sum of $W_+$ and $W_-$ is $12.5+23.5=36$, which will always be the total when ranks are assigned to $n=8$ values, since $1+2+3+4+5+6+7+8=36$. It is recommended to check that the sum of $W_+$ and $W_-$ does give the appropriate total for the sample size, which can be calculated for a sample of size $n$ as $\frac{1}{2}n(n+1)$.

\begin{centering}
\tcbset{width=14cm}
\begin{tcolorbox}[adjusted title=For a Wilcoxon Signed Rank test:, halign title = center,colback=black!5,colframe=black!75, halign = center]
\begin{itemize}
    \item The \textbf{test statistic}, denoted $W$, is the \textit{lower} of $W_+$ and $W_-$. 
    \item The \textbf{critical value} can be obtained from Page 15 of the Data Booklet.
    \item $\text{H}_0$ is rejected if the test statistic $W$ is \textbf{less than or equal to} the critical value.
\end{itemize}
\end{tcolorbox}
\end{centering}

\begin{tabular}{l l l }
Test statistic: & $W=12.5$ & \\[0.5em]
Critical value: & $CV=3$ & \quad ($\alpha=0.05$, $n=8$ \text{ and two-tailed.})
\end{tabular}

Since $12.5>3$, do not reject $\text{H}_0$ at the $5\%$ level of significance.  
There is insufficient evidence to suggest that the population **median** is not $10$.

\pagebreak

The Wilcoxon Signed Rank test will typically be used for small samples for which the Central Limit Theorem cannot be invoked, from populations which cannot be reasonably assumed to be normally distributed in order to use a $t$-test. The table of critical values only extends to samples up to size $n=20$, once zeros have been discarded. 

\begin{centering}
\tcbset{width=10cm}
\begin{tcolorbox}[adjusted title=Conditions for valid use:, halign title = center,colback=black!5,colframe=black!75, halign = center]
\begin{itemize}
    \item The underlying distribution is \textbf{symmetrical}.
    \item The data was obtained through a \textbf{random sample}.
\end{itemize}
\end{tcolorbox}
\end{centering}

A suggested methodical approach to obtaining the signed ranks required without a diagram is:

\begin{itemize}
    \item \textbf{Subtract} $\eta$ from every value in the sample.
    \item Ignoring any \textbf{zeros}, assign ranks to the remaining $n$ values in ascending order by \textbf{absolute} value.
\end{itemize}

The following example should be compared to Example 1 from Section 10.7, Chapter 10, in which a $t$-test was used.

\begin{tcolorbox}[title=Example 1,title filled, colframe=black!50]
\textbf{Problem:} A supermarket sells sharing-sized bags of a particular brand of crisps. A consumer watchdog is asked to investigate a claim that the median mass of crisps contained in a bag is less than the stated contents of 150 grams. A random sample of bags gives the following results, in grams:

  \begin{center}
  \begin{tabular}{c c c c c c c c} 
      148.3 & 151.2 & 149.7 & 152.5 & 145.4 & 151.0 & 146.5 & 151.6\\ 
  \end{tabular}
  \end{center}
  
  \begin{center}
  \begin{tikzpicture}

\draw[semithick] (144,0) -- (154,0);
\foreach \x in {144,144.5,...,154}
\draw[semithick] (\x,0) -- (\x,-0.1);
\foreach \x in {144,146,...,154}
\node at (\x,-0.3) {\x};
\node[below] at (149,-0.7) {Mass of crisps (grams)};
\draw[dashed] (150,0) -- (150,0.8) node[above] {$\eta=150$};

\draw[fill=black!25] (148.3,0.5) circle (2pt);
\draw[fill=black!25] (151.2,0.5) circle (2pt);
\draw[fill=black!25] (149.7,0.5) circle (2pt);
\draw[fill=black!25] (152.5,0.5) circle (2pt);
\draw[fill=black!25] (145.4,0.5) circle (2pt);
\draw[fill=black!25] (151.0,0.5) circle (2pt);
\draw[fill=black!25] (146.5,0.5) circle (2pt);
\draw[fill=black!25] (151.6,0.5) circle (2pt);

\end{tikzpicture}
\end{center}

Stating a necessary assumption, perform a non-parametric test to assess the claim at the 1\% level of significance.

\tcblower
\textbf{Solution:}

Assume that the mass of crisps in a bag is symmetrically distributed.\\

\begin{math}
\begin{array}{ll}
      \text{H}_0: & \eta=150\\[0.5em]
      \text{H}_1: & \eta<150
    \end{array}
\left]
    \begin{array}{l}
      \alpha=0.01\\
      \textnormal{One-tailed}
    \end{array}
  \right.
\end{math}

\begin{center}
\begin{tabular}{c c c c c c c c | c} 
    148.3 & 151.2 & 149.7 & 152.5 & 145.4 & 151.0 & 146.5 & 151.6 & \\
    -1.7 & 1.2 & -0.3 & 2.5 & -4.6 & 1.0 & -3.5 & 1.6 & ($\textit{subtract }\eta=150$)\\
    $5_-$ & $3_+$ & $1_-$ & $6_+$ & $8_-$ & $2_+$ & $7_-$  & $4_+$  & (\textit{assign signed ranks})
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{l c r}
    $W_+=15$ & \qquad & $\frac{1}{2}\times 8 \times 9=36$\\[0.5em]
    $W_-=21$ & & \textit{Check: }$15+21=36$
\end{tabular}
\end{center}

\begin{tabular}{l l l }
Test statistic: & $W=15$ & \\[0.5em]
Critical value: & $CV=1$ & \quad ($\alpha=0.01$, $n=8$ \text{and one-tailed.})
\end{tabular}\\

Since $15>1$, do not reject $\text{H}_0$ at the 1\% level of significance. 
There is insufficient evidence to suggest that the median mass of crisps in the bags is less than the stated value of 150g.

\end{tcolorbox}

\pagebreak

\begin{tcolorbox}[title=Example 2,title filled, colframe=black!50]
\textbf{Problem:} Before learner drivers can sit their practical test, they must sit a theory test. Part of this is a hazard perception test, in which a maximum of 75 points are available. Prior to some changes to the hazard perception test, the median score was 44. The points scored by ten randomly selected learner drivers in the updated hazard perception test are recorded:

  \begin{center}
  \begin{tabular}{c c c c c c c c c c} 
      63 & 38 & 48 & 44 & 50 & 70 & 68 & 39 & 64 & 66 \\ 
  \end{tabular}
  \end{center}

\begin{center}
\begin{tikzpicture}

\draw[semithick] (7,0) -- (15,0);
\foreach \x in {7,7.5,...,15}
\draw[semithick] (\x,0) -- (\x,-0.1);
\foreach \x in {35,40,...,70}
\node at (0.2*\x,-0.3) {\x};
\node[below] at (11,-0.7) {Hazard perception test scores};
\draw[dashed] (0.2*44,0) -- (0.2*44,0.8) node[above] {$\eta=44$};

\draw[fill=black!25] (0.2*63,0.5) circle (2pt);
\draw[fill=black!25] (0.2*38,0.5) circle (2pt);
\draw[fill=black!25] (0.2*48,0.5) circle (2pt);
\draw[fill=black!25] (0.2*44,0.5) circle (2pt);
\draw[fill=black!25] (0.2*50,0.5) circle (2pt);
\draw[fill=black!25] (0.2*70,0.5) circle (2pt);
\draw[fill=black!25] (0.2*68,0.5) circle (2pt);
\draw[fill=black!25] (0.2*39,0.5) circle (2pt);
\draw[fill=black!25] (0.2*64,0.5) circle (2pt);
\draw[fill=black!25] (0.2*66,0.5) circle (2pt);

\end{tikzpicture}
\end{center}

Test whether there is evidence, at the 10\% level of significance, that the median score has changed from 44.

\tcblower
\textbf{Solution:}\\

\begin{math}
\begin{array}{ll}
      \text{H}_0: & \eta=44\\[0.5em]
      \text{H}_1: & \eta\ne 44
    \end{array}
\left]
    \begin{array}{l}
      \alpha=0.1\\
      \textnormal{Two-tailed}
    \end{array}
  \right.
\end{math}

\begin{center}
\begin{tabular}{c c c c c c c c c c | c} 
    63 & 38 & 48 & 44 & 50 & 70 & 68 & 39 & 64 & 66 & \\
    19 & -6 & 4 & 0 & 6 & 26 & 24 & -5 & 20 & 22 & ($\textit{subtract }\eta=44$)\\
    $5_+$ & $3.5_-$ & $1_+$ &  & $3.5_+$ & $9_+$ & $8_+$ & $2_-$ & $6_+$ & $7_+$ & (\textit{assign signed ranks})
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{l c r}
    $W_+=39.5$ & \qquad & $\frac{1}{2}\times 9 \times 10=45$\\[0.5em]
    $W_-=5.5$ & & \textit{Check: }$39.5+5.5=45$
\end{tabular}
\end{center}

\begin{tabular}{l l l }
Test statistic: & $W=5.5$ & \\[0.5em]
Critical value: & $CV=8$ & \quad ($\alpha=0.1$, $n=9$ \text{and two-tailed.})
\end{tabular}\\

Since $5.5<8$, reject $H_0$ at the 10\% level of significance. 
There is evidence to suggest that the median score achieved in the hazard perception tests has changed from 44 points.

\end{tcolorbox}

#### Exercise 16A {-}

\begin{enumerate}
    \item It is known that a certain tree produces apples with a median mass of 150g. Eight apples are chosen at random from a crate containing apples picked from the tree. The masses, in grams, are:
\begin{center}
\begin{tabular}{cccccccc}
			147	& 138 &	171 &	142 &	152 &	145 &	141 &	143
\end{tabular}
\end{center}
Use a non-parametric test, at the 5\% significance level, to test whether the median mass of the apples is different from 150g.
\item For number of social media posts made in the last week are recorded for a random sample of eight UK teenagers, with the results:
    \begin{center}
    \begin{tabular}{c c c c c c c c} 
      5 & 2 & 18 & 11 & 0 & 6 & 1 & 0\\ 
    \end{tabular}
    \end{center}
    Test at the 5\% significance level the claim that the median number of social media posts made per week by a UK teenager is 10.
\pagebreak
    \item A recycling centre allows residents to deposit their metal waste into a skip set aside for it. The decision as to how often the skip will need to be emptied is based on an understanding that the median daily mass of metal waste deposited into the skip is 15kg, based on previous records. It has been suggested that this figure is no longer accurate. The recycling centre recorded the amount of metal waste deposited on eight randomly selected days. The results, in kg, were:
\begin{center}
\begin{tabular}{cccccccc}
    11.6 & 14.7 & 15.1 & 14.3 & 16.2 & 9.7 & 15.2 & 10.7
\end{tabular}
\end{center}
Perform a non-parametric test to assess, at the 10\% level of significance, whether this sample provides evidence to support the suggestion that the median daily mass of metal waste deposited has changed.
    \item The lifetimes of a random sample of a particular brand of candle, measured in minutes, are:
\begin{center}
\begin{tabular}{cccccccccc}
    372 & 352 & 335 & 364 & 345 & 360 & 354 & 358 & 348 & 341
\end{tabular}
\end{center}
Determine if there is evidence at the 5\% significance level that the median lifetime of this brand of candles is different from 6 hours.
    \item A company's complaints department has a policy that states that the median length of time its customers should have to wait before receiving a response to any complaint should not exceed 14 days. A sample of ten customers who have received responses to complaints were asked how long they had to wait. The results, in days, were:
\begin{center}
\begin{tabular}{cccccccccc}
    15 & 10 & 17 & 13 & 18 & 12 & 23 & 20 & 19 & 21
\end{tabular}
\end{center}
    \begin{enumerate}
        \item State two assumptions required in order for a Wilcoxon Signed Rank Test to be performed.
        \item Assess whether there is evidence to support a claim that the complaint department's policy is being breached, at the 5\% level of significance.
    \end{enumerate}
    \item A company is concerned about the length of time customers have to wait on a helpline before being connected to an agent. Previous records shows that the median waiting time was 34 minutes, and following additional training for the agents the company wishes to gauge the impact it may have had. Customer waiting times, in minutes, for a random sample of ten calls are recorded:
\begin{center}
\begin{tabular}{cccccccccc}
    55 & 20 & 31 & 12 & 18 & 32 & 28 & 16 & 14 & 33
\end{tabular}
\end{center}
Stating an assumption required, perform a non-parametric test at the 5\% level of significance to assess whether there is evidence the median waiting time has reduced from 34 minutes.
    \item A medical centre schedules doctors appointments for patients on the basis of a median appointment duration of 8 minutes. Wishing to determine whether this figure is reasonable, the length of ten randomly chosen appointments are recorded, and displayed below (in minutes).
\begin{center}
\begin{tabular}{cccccccccc}
    7 & 8 & 6 & 5 & 9 & 5 & 7 & 5 & 10 & 4
\end{tabular}
\end{center}
Assess at the 5\% level whether the data suggests the median appointment duration is not 8 minutes.
\end{enumerate}

\pagebreak

## Wilcoxon Signed Rank Test for Paired Data

In Chapter 15, the *paired* $t$-*test* was introduced. It is used for assessing the *mean of the differences between paired values* from small samples, and a key assumption for the test is that the *population of differences is normally distributed*. Where this assumption cannot reasonably be made, a **Wilcoxon Signed Rank Test for Paired Data** can instead be used to assesses the **median of the differences**, $\eta_d$.

\begin{centering}
\tcbset{width=10cm}
\begin{tcolorbox}[adjusted title=Conditions for valid use of the Wilcoxon Signed Rank Test for Paired Data:, halign title = center,colback=black!5,colframe=black!75, halign = center]
\begin{itemize}
    \item The \textbf{population of differences are symmetrical}.
    \item The data was obtained through \textbf{random sampling}.
\end{itemize}
\end{tcolorbox}
\end{centering}

Just as with the paired $t$-test, the paired samples are considered as a *single sample of differences*, allowing a similar process to the one-sample Wilcoxon Signed Rank Test.

\begin{tcolorbox}[title=Example,title filled, colframe=black!50]
\textbf{Problem:} An athletics coach wishes to assess the value to athletes of an intensive period of weight training. Twelve 400-metre runners are selected at random and their times to complete this distance, in seconds, are recorded. Following a programme of weight training they run the distance again, with their times in seconds again recorded. The table below summarises the results.

\begin{center}
\begin{tabular}{c|cccccccccccc} 
    Athlete & A & B & C & D & E & F & G & H & I & J & K & L\\
  \hline
    Before & 51.0 & 49.8 & 49.5 & 50.1 & 51.6 & 48.9 & 52.4 & 50.6 & 53.1 & 48.6 & 52.9 & 53.4\\  
    After & 50.6 & 50.4 & 48.9 & 49.1 & 51.6 & 47.6 & 53.5 & 49.9 & 51.0 & 48.5 & 50.6 & 51.7
\end{tabular}
\end{center}
  
Stating an assumption required, perform a non-parametric test to assess the evidence that the training programme will improve athletes’ times for the 400 metre distance.

\tcblower
\textbf{Solution:}

(Note that $d=\textit{Before}-\textit{After}$ will give differences such that a positive number represents an improvement in running time, and $\eta_d$ represents the population median of differences).\\

\begin{math}
\begin{array}{ll}
      H_0: & \eta_d=0\\
      H_1: & \eta_d>0
    \end{array}
\left]
    \begin{array}{l}
      \alpha=0.05\\
      \textnormal{One-tailed}
    \end{array}
  \right.
\end{math}

\begin{center}
\begin{tabular}{c c c c c c c c c c c c | c} 
    0.4 & -0.6 & 0.6 & 1.0 & 0.0 & 1.3 & -1.1 & 0.7 & 2.1 & 0.1 & 2.3 & 1.7 & \\
    $2_+$ & $3.5_-$ & $3.5_+$ & $6_+$ &  & $8_+$ & $7_-$ & $5_+$ & $10_+$ & $1_+$ & $11_+$ & $9_+$ & (\textit{assign signed ranks})
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{l c r}
    $W_+=55.5$ & \qquad & $\frac{1}{2}\times 11 \times 12=66$\\
    $W_-=10.5$ & & \textit{Check: }$55.5+10.5=66$
\end{tabular}
\end{center}

\begin{tabular}{l l l }
Test statistic: & $W=10.5$ & \\
Critical value: & $CV=13$ & \quad ($\alpha=0.05$, $n=11$ \text{and one-tailed.})
\end{tabular}\\

Since $10.5<13$, reject $H_0$ at the 5\% level of significance. 
There is evidence to suggest that the median difference in 400 metres times is greater than zero, meaning times have improved after the weight training programme.

\end{tcolorbox}

#### Exercise 16B {-}

\begin{enumerate}
    \item To measure the effectiveness of a drug for asthmatic relief, twelve subjects, all susceptible to asthma, were each randomly administered either the drug or a placebo during two separate asthma attacks. After one hour an asthmatic index was obtained on each subject with the following results:
\begin{center}
\begin{tabular}{c|cccccccccccc}
    Subject & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12\\
  \hline
    Drug & 28 & 31 & 17 & 18 & 31 & 12 & 33 & 24 & 18 & 25 & 19 & 17\\
    Placebo & 32 & 33 & 23 & 26 & 34 & 17 & 30 & 24 & 19 & 23 & 21 & 24
\end{tabular}
\end{center}
Investigate the claim that the drug reduces the asthmatic index.
    \item A group of 8 patients with a particular illness were given a special diet and it was desired to test the assess the impact at the end of a 2-week period. Their masses, measured before and after the diet, are shown below, in kg.
\begin{center}
\begin{tabular}{c|cccccccc}
    Patient & A & B & C & D & E & F & G & H\\
  \hline
    Before & 82.27 & 78.18 & 86.36 & 85.00 & 95.45 & 75.45 & 83.18 & 83.64\\
    After & 82.87 & 79.54 & 87.36 & 86.10 & 94.99 & 75.48 & 83.54 & 82.15
\end{tabular}
\end{center}
Use a non-parametric test to determine if there is evidence at the 5\% level that the diet increases patient mass, stating any assumptions made.
    \item As part of her research into the behaviour of the human memory, a psychologist asked 15 randomly selected school pupils to talk for five minutes on ‘my day at school’.  Each pupil was then asked to estimate how many times they thought that they had used the word “like” during the five minutes.  The table below gives their estimates together with the true values.
\begin{center}
\begin{tabular}{c|ccccccccccccccc}
    Pupil & A & B & C & D & E & F & G & H & I & J & K & L & M & N & O\\
  \hline
    True value & 12 & 20 & 1 & 8 & 0 & 12 & 12 & 17 & 6 & 5 & 24 & 23 & 10 & 18 & 16\\
    Estimated value & 9 & 19 & 3 & 14 & 4 & 12 & 16 & 14 & 5 & 9 & 20 & 16 & 11 & 17 & 19
\end{tabular}
\end{center}
Use a non-parametric test to investigate whether pupils can remember accurately the frequency with which they use a particular word in a verbal description.
\item Eight amateur runners are selected to study the effects of consuming energy gels before running on runners' performances at middle-distances. Each has their finish time recorded for a 5000m run without consuming energy gels beforehand, then a month later their time is recorded again for a 5000m run before which each consumed two energy gels. The data is shown in the table below, with times recorded to the nearest minute.
    \begin{center}
        \begin{tabular}{c|cccccccc}
            \hline
              Runners & A & B & C & D & E & F & G & H\\
            \hline
              Without gels & 24 & 19 & 21 & 17 & 26 & 32 & 18 & 20\\
            \hline
              With gels  & 22 & 19 & 20 & 18 & 23 & 28 & 15 & 20\\
            \hline
        \end{tabular}
    \end{center}
    Perform a hypothesis test at the 5\% level of significance to assess whether the data supports a conclusion that consuming energy gels improves performances for runners.
    \item The delay in sound transmission through an audio interface is called \textit{latency}. A music technology website wishes to investigate whether a company's new audio interface, really offers low latency than its older one. A random sample of ten computers each have their audio latency measured, first with the older interface and then with the new interface. The results are as follows, measured in milliseconds:
\begin{center}
\begin{tabular}{c|cccccccccc}
    Computer & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
  \hline
    Old interface & 5.7 & 3.6 & 7.3 & 6.1 & 2.8 & 4.8 & 5.3 & 2.9 & 6.7 & 11.7\\
    New interface & 5.4 & 3.5 & 7.5 & 5.4 & 2.7 & 4.0 & 5.3 & 2.6 & 6.3 & 11.6
\end{tabular}
\end{center}
Stating an assumption required, perform a non-parametric test to assess whether the newer interface offers lower latency, at the 5\% level of significance.
\end{enumerate}
\pagebreak

## Normal Approximation to the Wilcoxon Signed Rank Test

The Data Booklet only provides Wilcoxon critical values for effective sample sizes where $n\leqslant20$, due to the complexity of obtaining exact critical values as $n$ increases. When dealing with a larger sample, where $n>20$ after zeros have been removed, a Wilcoxon Signed Rank Test may still be performed using a **normal approximation**. Page 15 of the Data Booklet  provides the required properties of the distribution of the test statistic, $W$:

$$E(W)=\frac{1}{4}n(n+1) \quad \text{and} \quad V(W)=\frac{1}{24}n(n+1)(2n+1)$$

Since here a *discrete* distribution is being approximated by the *continuous* normal distribution, a **continuity correction** is required. If the test statistic $W$ is taken as the lower of $W_+$ and $W_-$, a continuity correction of $+0.5$ should be used.

\begin{tcolorbox}[title=Example,title filled, colframe=black!50]
\textbf{Problem:} It is claimed by a local resident that more than 50\% of all the vehicles on an urban road exceed the 30 mph speed limit.  The speed of each of a random sample of 24 vehicles is recorded with the following results:

\begin{center}
\begin{tabular}{cccccccccccc} 
    22 & 24 & 26 & 28 & 29 & 30 & 30 & 32 & 33 & 34 & 35 & 35\\
		37 & 38 & 38 & 39 & 40 & 41 & 42 & 45 & 48 & 56 & 62 & 72
\end{tabular}
\end{center}
  
Use a non-parametric test to investigate the resident’s claim.

\tcblower
\textbf{Solution:}

\begin{math}
\begin{array}{ll}
      H_0: & \eta=30\\
      H_1: & \eta>30
    \end{array}
\left]
    \begin{array}{l}
      \alpha=0.05\\
      \textnormal{One-tailed}
    \end{array}
  \right.
\end{math}

\begin{center}
\begin{tabular}{cccccccccccc | c} 
    22 & 24 & 26 & 28 & 29 & 30 & 30 & 32 & 33 & 34 & 35 & 35 & \\
    37 & 38 & 38 & 39 & 40 & 41 & 42 & 45 & 48 & 56 & 62 & 72 & \\
  \hline
    -8 & -6 & -4 & -2 & -1 & 0 & 0 & 2 & 3 & 4 & 5 & 5 & ($\textit{subtract }\eta=30$)\\
    7 & 8 & 8 & 9 & 10 & 11 & 12 & 15 & 18 & 26 & 32 & 42 & \\
  \hline
    $12_-$ & $9_-$ & $5.5_-$ & $2.5_-$ & $1_-$ &  &  & $2.5_+$ & $4_+$ & $5.5_+$ & $7.5_+$ & $7.5_+$ & (\textit{assign signed ranks})\\
    $10_+$ & $12_+$ & $12_+$ & $13_+$ & $14_+$ & $15_+$ & $16_+$ & $17_+$ & $18_+$ & $19_+$ & $20_+$ & $21_+$ & $22_+$
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{l c r}
    $W_+=223$ & \qquad & $\frac{1}{2}\times 22 \times 23=253$\\
    $W_-=30$ & & \textit{Check: }$223+30=253$
\end{tabular}
\end{center}

$$E(W)=\frac{1}{4}\times 22\times23=126.5 \quad \text{and} \quad V(W)=\frac{1}{24}\times 22\times 23\times 45=948.75$$

\vspace{0.5cm}    

Test statistic: $z=\cfrac{30.5-126.5}{\sqrt{948.75}}=-3.12$\\

\vspace{0.3cm}

Critical value: $-1.64$
\hspace{8cm}
\begin{tikzpicture}[overlay]
\begin{axis}[
  no markers, 
  domain=-3:3, 
  samples=100,
  ymin=0,
  axis lines*=left, 
  every axis y label/.style={at=(current axis.above origin),anchor=south},
  every axis x label/.style={at=(current axis.right of origin),anchor=west},
  height=3cm, 
  width=6.5cm,
  xtick=\empty, 
  ytick=\empty,
  enlargelimits=false, 
  clip=false, 
  axis on top,
  grid = major,
  hide y axis
  ]
\addplot [draw=none, fill=black!50, domain=-3:-1.64] {gauss(x, 0, 1)} \closedcycle;
 \addplot [semithick] {gauss(x, 0, 1)};
\pgfmathsetmacro\valueA{gauss(1.64,0,1)}
\pgfmathsetmacro\valueB{gauss(0,0,1)}
\draw [semithick, black]  (axis cs:-1.64,0) -- (axis cs:-1.64,\valueA);
\node[below] at (axis cs: 0,0)  {$0$};
\node[above] at (axis cs: 0,\valueB)  {$z$};
\node[below] at (axis cs: -1.64, 0) {$-1.64$};
\node[above] at (axis cs: -1.9,\valueA) {5\%};
\end{axis}
\end{tikzpicture}\\

\vspace{0.3cm}

Since $-3.12<-1.64$, reject $H_0$ at the 5\% level of significance. 
There is evidence to suggest that the median speed of the vehicles on the road is greater than 30 mph, and so more than 50\% of the vehicles are speeding..

\end{tcolorbox}

\pagebreak

#### Exercise 16C {-}

*Note: sums of signed ranks are often provided in questions that require a normal approximation to the Wilcoxon test. The data must still be inspected to check whether any values have been be discarded, to determine the effective sample size*

\begin{enumerate}
    \item Twenty six apples are chosen at random from a crate containing a large number of apples. The masses (to the nearest gram) are:
\begin{center}
\begin{tabular}{ccccccccccccc}
    136&137&138&139&141&141&142&142&143&145&146&146&147\\
    148&149&150&152&152&156&157&159&161&162&167&171&173
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{c c c}
    $W_+=149.5$ & \qquad & $W_-=175.5$
\end{tabular}
\end{center}

Use a Wilcoxon Signed Rank test, at the 5\% significance level, to test whether the median mass of the apples is different than 150 grams, stating any assumptions made.
    \item The lifetimes of a random sample of a particular type of candle, measured to the nearest minute, are:
\begin{center}
\begin{tabular}{cccccccccccc}
    268&335&339&341&341&345&346&348&352&354&355&356\\
    357&358&359&361&362&363&364&367&371&373&374&374
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{c c c}
    $W_+=91$ & \qquad & $W_-=209$
\end{tabular}
\end{center}

The manufacturer claims that the average lifetime is at least 6 hours. Use a non-parametric test to assess whether the sample gives evidence to suggest the manufacturer's claim is not correct.
    \item A local politician stated that the median hourly wage paid to young people aged 16-17 in the area is £9.20. Believing that the true median hourly wage paid is lower than this, a newspaper randomly selected 28 young people currently doing paid work and recorded their hourly wage (in £):
\begin{center}
\begin{tabular}{cccccccccccccc}
    8.65 & 9.10 & 8.71 & 9.80 & 8.60 & 8.95 & 10.35 & 8.60 & 8.86 & 9.25 & 8.60 & 8.70 & 9.20 & 8.92\\
    8.82 & 8.60 & 9.83 & 13.95 & 9.00 & 8.60 & 8.63 & 9.35 & 8.90 & 9.70 & 8.70 & 9.00 & 10.10 & 9.50
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{c c c}
    $W_+=152$ & \qquad & $W_-=173$
\end{tabular}
\end{center}

Use a non-parametric test to determine whether the sample supports the newspaper's suspicions.
\item A hillwalking website publishes details of popular hiking routes around Scotland. One particular route states that it takes 1 hour and 50 minutes to complete. Following upgrades to some of the paths which the route follows, the time taken to complete the route is recorded for a random sample of 32 hikers. The results of a non-parametric test conducted on the resulting data is shown below, with times recorded in minutes:\vspace{0.5cm}\\
    \texttt{Wilcoxon test for the population median}\\
    \texttt{data: hike times}\\
    \texttt{alternative hypothesis: true location is less than 110}\\
    \texttt{n = 32}\qquad \texttt{sample median = 102}\\
    \texttt{W = }\texttt{148}\qquad \texttt{p-value = 0.0154}\\
    \vspace{0.1cm}
    \begin{enumerate}
        \item State the null and alternative hypotheses for the test conducted.
        \item Use the value of $W$ provided in the computer output to perform a test of the above hypotheses at the 5\% level of significance.
        \item State an assumption required for the test.
    \end{enumerate}
\end{enumerate}

\pagebreak

## Review Exercise {-}

\begin{enumerate}
    \item A random sample of nine primary school pupils are selected to test the number of times tables questions they can answer correctly in one minute. The results are are follows:
\begin{center}
\begin{tabular}{ccccccccc}
    24 & 33 & 36 & 19 & 37 & 21 & 16 & 47 & 20
\end{tabular}
\end{center}
Perform a test to determine whether the data supports a claim that the median number of times tables questions a primary school pupil can answer in a minute is greater than 20.
    \item To test whether displaying the speeds of cars travelling up a school drive on a digital display is effective in reducing driving speeds, ten cars that regularly drive up the school drive are randomly selected. For each, a speed is recorded on an occasion in which their speed is not displayed on a digital sign, and a speed is recorded when their speed is displayed. The results are as follows, in mph:
\begin{center}
\begin{tabular}{c|cccccccccc}
    Vehicle & A & B & C & D & E & F & G & H & I & J\\
  \hline
    Speed not displayed  & 8 & 9 & 11 & 9 & 11 & 13 & 9 & 16 & 7 & 21\\
    Speed is displayed  & 7 & 10 & 10 & 9 & 10 & 14 & 8 & 10 & 9 & 14
\end{tabular}
\end{center}
Use a non-parametric tests to assess whether this suggests displaying the driving speeds of cars travelling up the school drive is effective in reducing speeds, stating an assumption required.
    \item A national newspaper states that the median amount of fuel motorists put into their vehicles' tanks when stopping at a petrol station is 20 litres. To investigate this claim, a motoring magazine stops thirty people at random whilst leaving a petrol station and asks how much fuel they just bought. The results, to the nearest litre, are:
\begin{center}
\begin{tabular}{cccccccccc}
        32 & 45 & 17 & 54 & 20 & 9 & 15 & 34 & 38 & 26\\
        40 & 24 & 61 & 6 & 18 & 21 & 34 & 48 & 28 & 25\\
        9 & 10 & 13 & 10 & 25 & 22 & 38 & 41 & 23 & 29
\end{tabular}
\end{center}
\begin{center}
\begin{tabular}{c c c}
    $W_+=106$ & \qquad & $W_-=329$
\end{tabular}
\end{center}
Perform a non-parametric test to assess whether there is evidence to suggest that the figure claimed by the national newspaper is incorrect, at the 5\% level of significance. 
\item A car company wishes to check that a new machine at their factory producing front bumpers is still maintaining the median mass of 2.8kg for the part as the old machine it replaced. Eight bumpers produced by the machine are randomly selected and weighed, in kilograms. Computer output from a test performed on the data is as follows:\vspace{0.5cm}\\
    \texttt{Wilcoxon test for the population median}\\
    \texttt{data: bumper mass}\\
    \texttt{alternative hypothesis: true location is not equal to 2.8}\\
    \texttt{W = 25}\qquad \texttt{n = 7 ranks assigned}\qquad \texttt{sample median = 2.95}\\
    \vspace{0.1cm}\\
    By first calculating the required test statistic, perform a non-parametric test at the 5\% level of significance to determine whether there is evidence to suggest that the median mass of the part produced by the new machine has changed, stating an assumption required.
\end{enumerate}

\pagebreak

#### Chapter 16 Answers{-}

*For any questions for which a level of significance is not specified, a 5\% level of significance has been used. Full answers should include, of course, conclusions in context*

#### Exercise 16A {-}
\begin{enumerate}
    \item $9>3\implies\text{ do not reject }H_0$
    \item $5.5<3\implies\text{ reject }H_0$
    \item $8>5\implies\text{ do not reject }H_0$
    \item $7.5>5\implies\text{ do not reject }H_0$
    \item $10\leqslant 10\implies\text{ reject }H_0$
    \item $9<10\implies\text{ reject }H_0$
    \item $6.5>5\implies\text{ do not reject }H_0$
\end{enumerate}

#### Exercise 16B {-}
\begin{enumerate}
    \item $8.5<13\implies\text{ reject }H_0$
    \item $11>5\implies\text{ do not reject }H_0$
    \item $46>21\implies\text{ do not reject }H_0$
    \item $1.5<2\implies\text{ reject }H_0$
    \item $4<8\implies\text{ reject }H_0$
\end{enumerate}

#### Exercise 16C {-}
\begin{enumerate}
    \item $-0.34>-1.96\implies\text{ do not reject }H_0$
    \item $-1.67<-1.64\implies\text{ reject }H_0$
    \item $-0.27>-1.64\implies\text{ do not reject }H_0$
    \item
    \begin{enumerate}
        \item $H_0: \eta =110, \quad H_1: \eta<110$
        \item $-2.16>-1.64\implies\text{reject }H_0$
        \item Assume that time taken to complete the hike is symmetrically distributed.
    \end{enumerate}
\end{enumerate}

#### Review Exercise {-}
\begin{enumerate}
    \item $5\leqslant5\implies\text{ reject }H_0$
    \item $14>8\implies\text{ do not reject }H_0$
    \item $-2.40>-1.96\implies\text{ reject }H_0$
    \item $3>2\implies\text{do not reject }H_0$
\end{enumerate}
