---
title: "_sampling3b"
output: html_document
---

#### Exercise 3B {-}

*For each, state the sampling method that most closely matches the approach used, and suggest a suitable sampling frame.*

\begin{enumerate}
    \item A company produces 800 bottles of shampoo every 30 minutes. For quality control purposes 10 bottles are selected every 30 mins to be checked.  Each bottle passes through the machine in a single file and every 80th bottle is selected after a random starting point is chosen.
    \item A researcher wishes to find out local opinion about a new playpark and goes to a parent and toddler group to speak to those attending. 
    \item A TV show selects 5 audience members to take part in the show by using a random number generator to select seat numbers.
    \item A ferry company wants to survey its customers one day, so 5 ferries are randomly selected that day and a questionnaire given to every passenger on each ferry.
    \item A business employs staff across a number of different departments and wishes to canvass opinion about a new policy being implemented so that each department is proportionally represented. 
    \item 4 researchers are in a shopping centre and have been allocated one of 4 age-groups. They have been tasked with speaking to 15 people from their allocated age-group.
\end{enumerate}

\pagebreak
